import {
  createContext,
  useContext,
  useReducer,
  useCallback,
  useEffect,
  useRef,
  type ReactNode,
} from 'react';
import {
  type Trip,
  ODO_START,
  getTripOdoStart,
  getTripOdoEnd,
  generateConnectorTrips,
} from './trip-data';
import {
  getVehicles,
  getExpenses,
  getTrips,
  getProfile,
  getLogbookPeriods,
  getReports as fetchReports,
  classifyTrip,
  updateTrip,
  saveTrip,
  deleteTrip,
  saveReport,
  deleteReport,
  logAuditEvent,
} from './data-service';
import type {
  AppVehicle,
  AppExpense,
  AppProfile,
  AppLogbookPeriod,
  AppReport,
  AppTrip,
} from '@shared/types';
import { getCurrentFY } from '@shared/types';
import { getVehicleCostsDetailed } from './deduction-estimator';
import type {
  VehicleSpecs,
  VehiclePurchase,
  ExpenseRecord,
  AppSettings,
} from './deduction-estimator';

// ── Screen type ──────────────────────────────────────────────

export type Screen =
  | 'dashboard'
  | 'sort'
  | 'classify'
  | 'review'
  | 'notes'
  | 'odometer'
  | 'reports'
  | 'export'
  | 'input'
  | 'expenses'
  | 'stats'
  | 'find-keys'
  | 'account';

export const INDUSTRY_BIZ_AVG = 65;

// ── Audit score ──────────────────────────────────────────────

export function calcAuditScore(params: {
  totalTrips: number;
  sortedTrips: number;
  verifiedCount: number;
  photoCount: number;
  bizPct: number;
  notesCount?: number;
  bizCount?: number;
}) {
  const {
    totalTrips,
    sortedTrips,
    verifiedCount,
    photoCount,
    bizPct,
    notesCount = 0,
    bizCount = 0,
  } = params;

  if (sortedTrips === 0) {
    return {
      classifiedPct: 0, verifiedPct: 0, photoPct: 0, ratioPct: 0, notesPct: 0,
      classifiedContrib: 0, verifiedContrib: 0, photoContrib: 0, ratioContrib: 0,
      notesContrib: 0, total: 0,
    };
  }

  const classifiedPct = sortedTrips > 0 ? 100 : 0;
  const verifiedPct = (verifiedCount / sortedTrips) * 100;
  const photoPct = (photoCount / sortedTrips) * 100;
  const notesPct = bizCount > 0 ? (notesCount / bizCount) * 100 : 0;
  const deviation = Math.abs(bizPct - INDUSTRY_BIZ_AVG);
  const ratioPct = Math.max(0, 100 - (deviation / INDUSTRY_BIZ_AVG) * 100);

  const classifiedContrib = Math.round(classifiedPct * 0.30);
  const verifiedContrib = Math.round(verifiedPct * 0.25);
  const photoContrib = Math.round(photoPct * 0.10);
  const notesContrib = Math.round(notesPct * 0.10);
  const ratioContrib = Math.round(ratioPct * 0.24);
  const total = Math.min(
    99,
    classifiedContrib + verifiedContrib + photoContrib + notesContrib + ratioContrib
  );

  return {
    classifiedPct, verifiedPct, photoPct, ratioPct, notesPct,
    classifiedContrib, verifiedContrib, photoContrib, ratioContrib, notesContrib, total,
  };
}

// ── Saved report shape ───────────────────────────────────────

interface SavedTripSummary {
  from: string;
  to: string;
  km: number;
  date: string;
  time: string;
  type: 'business' | 'personal' | null;
  purposeLabel: string | null;
  verified: boolean;
  photo: boolean;
  odoStart: number;
  odoEnd: number;
  notes: string;
  autoGenerated?: boolean;
}

interface SavedReport {
  sessionId: string;
  dbId?: string;         // Supabase reports.id when persisted
  timestamp: string;
  bizCount: number;
  perCount: number;
  classified: number;
  unclassified: number;
  est: string;
  totalKm: string;
  auditScore: number;
  lastOdoReading: number | null;
  lastOdoVerifiedAt: string | null;
  odoRangeStart: number;
  odoRangeEnd: number;
  trips: SavedTripSummary[];
  auditLog: { time: string; desc: string }[];
  areasToCheck: string[];
  revision: number;
  supersedes: boolean;
}

// ── App state ────────────────────────────────────────────────

interface AppState {
  // Core trip state
  trips: Trip[];
  currentScreen: Screen;
  currentIndex: number;
  dedTotal: number;
  bizCount: number;
  perCount: number;
  lastAction: { idx: number; type: string; ded: number } | null;
  verifiedSet: Set<number>;
  auditLog: { time: string; desc: string; hasPhoto: boolean }[];
  savedReports: SavedReport[];
  lastOdoReading: number | null;
  lastOdoVerifiedAt: string | null;
  classifyStep: number;
  classifyBizTrips: number[];
  sessionStartTime: number;
  editModalOpen: boolean;
  editTripIndex: number;
  atoModalOpen: boolean;
  summaryModalOpen: boolean;
  conflictResolved: boolean;
  freshSession: boolean;
  pendingFinalise: boolean;
  sessionId: string;
  baseOdo: number;
  queuedTrips: Trip[];

  // Supabase-loaded data
  vehicle: AppVehicle | null;
  vehicleId: string | null;
  profile: AppProfile | null;
  expenses: AppExpense[];
  logbookPeriods: AppLogbookPeriod[];

  // Loading / error states
  isLoading: boolean;
  isInitialised: boolean;
  error: string | null;
}

// ── Actions ──────────────────────────────────────────────────

type Action =
  // All original actions — unchanged
  | { type: 'CLASSIFY_TRIP'; tripType: 'business' | 'personal' }
  | { type: 'UNDO_LAST' }
  | { type: 'GO_SCREEN'; screen: Screen }
  | { type: 'SET_PURPOSE'; tripIndex: number; purposeLabel: string; purposeIndex: number | null }
  | { type: 'CLASSIFY_NEXT' }
  | { type: 'INIT_CLASSIFY' }
  | { type: 'RECLASSIFY'; tripIndex: number; tripType: 'business' | 'personal' }
  | { type: 'VERIFY_TRIP'; tripIndex: number; startReading: number; reading: number; photo: boolean }
  | { type: 'ADD_PHOTO'; tripIndex: number }
  | { type: 'UPDATE_TRIP'; tripIndex: number; updates: Partial<Trip> }
  | { type: 'OPEN_EDIT'; tripIndex: number }
  | { type: 'CLOSE_EDIT' }
  | { type: 'OPEN_ATO' }
  | { type: 'CLOSE_ATO' }
  | { type: 'OPEN_SUMMARY' }
  | { type: 'CLOSE_SUMMARY' }
  | { type: 'SAVE_SESSION' }
  | { type: 'ADD_LOG'; desc: string; hasPhoto: boolean }
  | { type: 'SET_MANUAL_ODO'; reading: number }
  | { type: 'RESET_DEMO' }
  | { type: 'LOAD_BATCH2' }
  | { type: 'DELETE_ALL_TRIPS' }
  | { type: 'DELETE_SESSION'; sessionId: string }
  | { type: 'PROMOTE_REPORT'; reportIndex: number }
  | { type: 'COME_BACK_LATER' }
  | { type: 'RESUME_SORTING' }
  | { type: 'ADD_TRIP'; trip: Trip }
  | { type: 'CONFIRM_GAP'; tripIndex: number; km: number }
  | { type: 'DELETE_GAP'; tripIndex: number }
  // New actions for Supabase integration
  | { type: 'DB_LOADED'; trips: Trip[]; vehicle: AppVehicle | null; vehicleId: string | null; profile: AppProfile | null; expenses: AppExpense[]; logbookPeriods: AppLogbookPeriod[]; baseOdo: number }
  | { type: 'DB_ERROR'; error: string }
  | { type: 'SET_VEHICLE'; vehicle: AppVehicle; vehicleId: string }
  | { type: 'SET_EXPENSES'; expenses: AppExpense[] }
  | { type: 'SET_PROFILE'; profile: AppProfile }
  | { type: 'REPORT_SAVED_TO_DB'; sessionId: string; dbId: string }
  | { type: 'REPORT_DELETED_FROM_DB'; dbId: string };


// ── Helpers ──────────────────────────────────────────────────

function nowStr(): string {
  const n = new Date();
  return (
    n.toLocaleDateString('en-AU', { day: '2-digit', month: 'short' }) +
    ' ' +
    n.toLocaleTimeString('en-AU', { hour: '2-digit', minute: '2-digit' })
  );
}

const BATCH_SIZE = 6;

/** Convert AppTrip from data-service to Trip for local state (id = index, dbId = Supabase id) */
function appTripToTrip(app: AppTrip, index: number): Trip {
  return {
    id: index,
    dbId: app.id,
    date: app.date,
    day: app.day,
    month: app.month,
    year: app.year,
    time: app.time,
    duration: app.duration,
    km: app.km,
    from: app.from,
    fromSub: app.fromSub,
    to: app.to,
    toSub: app.toSub,
    type: app.type,
    verified: app.verified,
    photo: app.photo,
    odoReading: app.odoReading,
    odoStartReading: app.odoStartReading,
    purposeLabel: app.purposeLabel,
    purposeIndex: app.purposeIndex,
    stops: app.stops,
    notes: app.notes,
    autoGenerated: app.autoGenerated,
    gapConfirmed: app.gapConfirmed,
  };
}

// ── Initial state ────────────────────────────────────────────

const initialState: AppState = {
  trips: [],
  currentScreen: 'dashboard',
  currentIndex: 0,
  dedTotal: 0,
  bizCount: 0,
  perCount: 0,
  lastAction: null,
  verifiedSet: new Set(),
  auditLog: [],
  savedReports: [],
  lastOdoReading: null,
  lastOdoVerifiedAt: null,
  classifyStep: 0,
  classifyBizTrips: [],
  sessionStartTime: Date.now(),
  editModalOpen: false,
  editTripIndex: 0,
  atoModalOpen: false,
  summaryModalOpen: false,
  conflictResolved: false,
  freshSession: true,
  pendingFinalise: false,
  sessionId: 'session_' + Date.now(),
  baseOdo: ODO_START,
  queuedTrips: [],
  vehicle: null,
  vehicleId: null,
  profile: null,
  expenses: [],
  logbookPeriods: [],
  isLoading: true,
  isInitialised: false,
  error: null,
};

// ── Deduction computation (uses Supabase-loaded data) ────────

function buildEstimatorInputs(state: AppState): {
  vehicleSpecs: VehicleSpecs;
  vehiclePurchase: VehiclePurchase;
  expenses: ExpenseRecord[];
  settings: AppSettings;
} {
  const v = state.vehicle;
  const vehicleSpecs: VehicleSpecs = {
    vehicleCategory: v?.vehicleCategory || undefined,
    bodyType: v?.bodyType || undefined,
    fuelConsumption: v?.fuelConsumption ?? undefined,
  };
  const vehiclePurchase: VehiclePurchase = {
    purchasePrice: v?.purchasePrice ?? undefined,
    purchaseDate: v?.purchaseDate ?? undefined,
    currentWDV: v?.wdvAtStartOfFy ?? undefined,
    vehicleHistoryStatus: v?.vehicleHistoryStatus ?? undefined,
    depreciationInputMode: v?.depreciationInputMode ?? undefined,
    previouslyClaimed: v?.priorDepreciationClaimed ?? undefined,
    approxYearsOwned: v?.approxYearsOwned ?? undefined,
    approxYearsBusinessUse: v?.approxYearsBusinessUse ?? undefined,
    dateFirstUsed: v?.dateFirstBusinessUse ?? undefined,
  };
  const expenses: ExpenseRecord[] = state.expenses.map(e => ({
    amount: e.amount,
    isEstimated: e.isEstimated,
  }));
  const settings: AppSettings = {
    useIndustryAverages: state.profile?.estimatorMode !== 'personalised',
  };
  return { vehicleSpecs, vehiclePurchase, expenses, settings };
}

function computeDedTotal(state: AppState, trips: Trip[], upToIndex: number): number {
  const params = buildEstimatorInputs(state);
  const costs = getVehicleCostsDetailed(params);
  const ANNUAL_KM = 15000;
  const perKmRate = costs.total / ANNUAL_KM;
  const slice = trips.slice(0, upToIndex);
  const bizKm = slice.filter(t => t.type === 'business').reduce((s, t) => s + t.km, 0);
  return Math.round(bizKm * perKmRate * 100) / 100;
}

/** Build params for deduction-estimator (getReadinessChecks, getDeductionState, getMissingItems, etc.) from app state */
export function getEstimatorParamsFromState(state: AppState, hasBizTrips: boolean): {
  taxProfile?: { salary?: string | number };
  vehiclePurchase?: import('./deduction-estimator').VehiclePurchase;
  vehicleSpecs?: VehicleSpecs;
  expenses?: ExpenseRecord[];
  hasBizTrips: boolean;
  settings?: AppSettings;
} {
  const v = state.vehicle;
  const vehicleSpecs: VehicleSpecs = {
    vehicleCategory: v?.vehicleCategory || undefined,
    bodyType: v?.bodyType || undefined,
    fuelConsumption: v?.fuelConsumption ?? undefined,
  };
  const vehiclePurchase: VehiclePurchase = {
    purchasePrice: v?.purchasePrice ?? undefined,
    purchaseDate: v?.purchaseDate ?? undefined,
    currentWDV: v?.wdvAtStartOfFy ?? undefined,
    vehicleHistoryStatus: v?.vehicleHistoryStatus ?? undefined,
    depreciationInputMode: v?.depreciationInputMode ?? undefined,
    previouslyClaimed: v?.priorDepreciationClaimed ?? undefined,
    approxYearsOwned: v?.approxYearsOwned ?? undefined,
    approxYearsBusinessUse: v?.approxYearsBusinessUse ?? undefined,
    dateFirstUsed: v?.dateFirstBusinessUse ?? undefined,
  };
  const taxProfile = state.profile ? { salary: (state.profile as { incomeBracket?: string }).incomeBracket } : undefined;
  const expenses: ExpenseRecord[] = state.expenses.map(e => ({ amount: e.amount, isEstimated: e.isEstimated }));
  const settings: AppSettings = { useIndustryAverages: state.profile?.estimatorMode !== 'personalised' };
  return { taxProfile, vehiclePurchase, vehicleSpecs, expenses, hasBizTrips, settings };
}

function reducer(state: AppState, action: Action): AppState {
  switch (action.type) {

    // ── Supabase lifecycle ──

    case 'DB_LOADED': {
      const batch = action.trips.slice(0, BATCH_SIZE).map(t => ({ ...t }));
      const queued = action.trips.slice(BATCH_SIZE).map(t => ({ ...t }));
      const sorted = batch.filter(t => t.type !== null);
      const newCurrentIndex = sorted.length;
      return {
        ...state,
        trips: batch,
        queuedTrips: queued,
        vehicle: action.vehicle,
        vehicleId: action.vehicleId,
        profile: action.profile,
        expenses: action.expenses,
        logbookPeriods: action.logbookPeriods,
        baseOdo: action.baseOdo,
        currentIndex: newCurrentIndex,
        bizCount: sorted.filter(t => t.type === 'business').length,
        perCount: sorted.filter(t => t.type === 'personal').length,
        isLoading: false,
        isInitialised: true,
        error: null,
      };
    }

    case 'DB_ERROR':
      return { ...state, isLoading: false, error: action.error };

    case 'SET_VEHICLE':
      return { ...state, vehicle: action.vehicle, vehicleId: action.vehicleId };

    case 'SET_EXPENSES':
      return { ...state, expenses: action.expenses };

    case 'SET_PROFILE':
      return { ...state, profile: action.profile };

    case 'REPORT_SAVED_TO_DB': {
      const updated = state.savedReports.map(r =>
        r.sessionId === action.sessionId && !r.dbId ? { ...r, dbId: action.dbId } : r
      );
      return { ...state, savedReports: updated };
    }

    case 'REPORT_DELETED_FROM_DB': {
      const filtered = state.savedReports.filter(r => r.dbId !== action.dbId);
      return { ...state, savedReports: filtered };
    }

    // ── All original actions ──

    case 'CLASSIFY_TRIP': {
      const trip = state.trips[state.currentIndex];
      if (!trip) return state;
      const newTrips = [...state.trips];
      newTrips[state.currentIndex] = { ...trip, type: action.tripType };
      const isBiz = action.tripType === 'business';
      const newIdx = state.currentIndex + 1;
      const newDedTotal = computeDedTotal(state, newTrips, newIdx);
      return {
        ...state,
        trips: newTrips,
        dedTotal: newDedTotal,
        bizCount: state.bizCount + (isBiz ? 1 : 0),
        perCount: state.perCount + (isBiz ? 0 : 1),
        lastAction: { idx: state.currentIndex, type: action.tripType, ded: newDedTotal - state.dedTotal },
        currentIndex: newIdx,
        freshSession: true,
      };
    }
    case 'UNDO_LAST': {
      if (!state.lastAction) return state;
      const { idx } = state.lastAction;
      const newTrips = [...state.trips];
      newTrips[idx] = { ...newTrips[idx], type: null };
      const undoSlice = newTrips.slice(0, idx);
      return {
        ...state,
        trips: newTrips,
        currentIndex: idx,
        dedTotal: computeDedTotal(state, newTrips, idx),
        bizCount: undoSlice.filter(t => t.type === 'business').length,
        perCount: undoSlice.filter(t => t.type === 'personal').length,
        lastAction: null,
      };
    }
    case 'GO_SCREEN':
      return { ...state, currentScreen: action.screen };
    case 'SET_PURPOSE': {
      const newTrips = [...state.trips];
      newTrips[action.tripIndex] = {
        ...newTrips[action.tripIndex],
        purposeLabel: action.purposeLabel,
        purposeIndex: action.purposeIndex,
      };
      return { ...state, trips: newTrips };
    }
    case 'INIT_CLASSIFY': {
      const mergedTrips = state.trips;
      const newCurrentIndex = mergedTrips.filter(t => t.type !== null).length;
      const sortedSlice = mergedTrips.slice(0, newCurrentIndex);
      const newDedTotal = computeDedTotal(state,mergedTrips, newCurrentIndex);
      const newBizCount = sortedSlice.filter(t => t.type === 'business').length;
      const newPerCount = sortedSlice.filter(t => t.type === 'personal').length;
      const bizTrips = mergedTrips.map((t, i) => i).filter(i => mergedTrips[i].type === 'business');
      return {
        ...state,
        trips: mergedTrips,
        currentIndex: newCurrentIndex,
        dedTotal: newDedTotal,
        bizCount: newBizCount,
        perCount: newPerCount,
        classifyStep: 0,
        classifyBizTrips: bizTrips,
        currentScreen: bizTrips.length > 0 ? 'classify' : 'review',
      };
    }
    case 'CLASSIFY_NEXT': {
      const nextStep = state.classifyStep + 1;
      if (nextStep >= state.classifyBizTrips.length) {
        return { ...state, classifyStep: nextStep, currentScreen: 'review' };
      }
      return { ...state, classifyStep: nextStep };
    }
    case 'RECLASSIFY': {
      const newTrips = [...state.trips];
      const trip = newTrips[action.tripIndex];
      const oldType = trip.type;
      newTrips[action.tripIndex] = { ...trip, type: action.tripType };
      const sortedSlice = newTrips.slice(0, state.currentIndex);
      const newBiz = sortedSlice.filter(t => t.type === 'business').length;
      const newPer = sortedSlice.filter(t => t.type === 'personal').length;
      const newDed = computeDedTotal(state, newTrips, state.currentIndex);
      const reclassDesc = `Reclassified "${trip.from} \u2192 ${trip.to}" from ${oldType || 'unsorted'} to ${action.tripType}`;
      return {
        ...state,
        trips: newTrips,
        dedTotal: newDed,
        bizCount: newBiz,
        perCount: newPer,
        auditLog: [{ time: nowStr(), desc: reclassDesc, hasPhoto: false }, ...state.auditLog],
      };
    }
    case 'VERIFY_TRIP': {
      const newTrips = [...state.trips];
      newTrips[action.tripIndex] = {
        ...newTrips[action.tripIndex],
        verified: true,
        odoStartReading: action.startReading,
        odoReading: action.reading,
        photo: action.photo || newTrips[action.tripIndex].photo,
      };
      const newVerified = new Set(state.verifiedSet);
      newVerified.add(action.tripIndex);
      return {
        ...state,
        trips: newTrips,
        verifiedSet: newVerified,
        lastOdoReading: action.reading,
        lastOdoVerifiedAt: nowStr(),
        auditLog: [{ time: nowStr(), desc: `Trip verified: ${newTrips[action.tripIndex].from} \u2192 ${newTrips[action.tripIndex].to}`, hasPhoto: action.photo }, ...state.auditLog],
      };
    }
    case 'ADD_PHOTO': {
      const newTrips = [...state.trips];
      newTrips[action.tripIndex] = { ...newTrips[action.tripIndex], photo: true };
      return {
        ...state,
        trips: newTrips,
        auditLog: [{ time: nowStr(), desc: `Photo added: ${newTrips[action.tripIndex].from} \u2192 ${newTrips[action.tripIndex].to}`, hasPhoto: true }, ...state.auditLog],
      };
    }
    case 'UPDATE_TRIP': {
      const newTrips = [...state.trips];
      const oldTrip = newTrips[action.tripIndex];
      const kmChanged = action.updates.km != null && action.updates.km !== oldTrip.km;
      const routeChanged = kmChanged || action.updates.from != null || action.updates.to != null || action.updates.stops != null;
      newTrips[action.tripIndex] = { ...oldTrip, ...action.updates };
      if (routeChanged) {
        newTrips[action.tripIndex].odoReading = null;
        newTrips[action.tripIndex].odoStartReading = null;
        newTrips[action.tripIndex].verified = false;
      }
      const newVerified = new Set(state.verifiedSet);
      if (routeChanged) {
        newVerified.delete(action.tripIndex);
        for (let i = action.tripIndex + 1; i < newTrips.length; i++) {
          if (newTrips[i].odoStartReading != null || newTrips[i].odoReading != null) {
            newTrips[i] = { ...newTrips[i], odoStartReading: null, odoReading: null, verified: false };
            newVerified.delete(i);
          }
        }
      }
      const sortedForCount = newTrips.slice(0, state.currentIndex);
      const newBizCount = sortedForCount.filter(t => t.type === 'business').length;
      const newPerCount = sortedForCount.filter(t => t.type === 'personal').length;
      const newDedTotal = computeDedTotal(state, newTrips, state.currentIndex);
      const editDesc = routeChanged
        ? `Route edited: ${newTrips[action.tripIndex].from} → ${newTrips[action.tripIndex].to} (${newTrips[action.tripIndex].km.toFixed(1)} km)`
        : `Edited trip: ${newTrips[action.tripIndex].from} → ${newTrips[action.tripIndex].to}`;
      return {
        ...state,
        trips: newTrips,
        verifiedSet: newVerified,
        bizCount: newBizCount,
        perCount: newPerCount,
        dedTotal: newDedTotal,
        auditLog: [{ time: nowStr(), desc: editDesc, hasPhoto: false }, ...state.auditLog],
      };
    }
    case 'OPEN_EDIT':
      return { ...state, editModalOpen: true, editTripIndex: action.tripIndex };
    case 'CLOSE_EDIT':
      return { ...state, editModalOpen: false };
    case 'OPEN_ATO':
      return { ...state, atoModalOpen: true };
    case 'CLOSE_ATO':
      return { ...state, atoModalOpen: false };
    case 'OPEN_SUMMARY':
      return { ...state, summaryModalOpen: true };
    case 'CLOSE_SUMMARY':
      return { ...state, summaryModalOpen: false };
    case 'SAVE_SESSION': {
      const biz = state.trips.filter(t => t.type === 'business');
      const per = state.trips.filter(t => t.type === 'personal');
      const classified = biz.filter(t => t.purposeLabel).length;
      const now = new Date();
      const ts = now.toLocaleDateString('en-AU', { weekday: 'short', day: '2-digit', month: 'short', year: 'numeric' }) +
        ' \u00B7 ' + now.toLocaleTimeString('en-AU', { hour: '2-digit', minute: '2-digit' });
      const sortedTrips = state.trips.filter(t => t.type !== null);
      const tripSummaries: SavedTripSummary[] = sortedTrips.map(t => {
        const origIdx = state.trips.indexOf(t);
        return {
          from: t.from, to: t.to, km: t.km, date: t.date, time: t.time,
          type: t.type, purposeLabel: t.purposeLabel, verified: t.verified, photo: t.photo,
          odoStart: getTripOdoStart(state.trips, origIdx, state.baseOdo),
          odoEnd: getTripOdoEnd(state.trips, origIdx, state.baseOdo),
          notes: t.notes || '',
          autoGenerated: t.autoGenerated || false,
        };
      });
      const areas: string[] = [];
      const unverifiedBiz = biz.filter(t => !t.verified);
      if (unverifiedBiz.length > 0) areas.push(`${unverifiedBiz.length} business trip${unverifiedBiz.length > 1 ? 's' : ''} not odometer-verified`);
      const noPurpose = biz.filter(t => !t.purposeLabel);
      if (noPurpose.length > 0) areas.push(`${noPurpose.length} business trip${noPurpose.length > 1 ? 's' : ''} missing purpose category`);
      const noNotes = biz.filter(t => !t.notes || t.notes.length === 0);
      if (noNotes.length > 0) areas.push(`${noNotes.length} business trip${noNotes.length > 1 ? 's' : ''} without trip notes`);
      const noPhoto = biz.filter(t => !t.photo);
      if (noPhoto.length > 0) areas.push(`${noPhoto.length} business trip${noPhoto.length > 1 ? 's' : ''} without photo evidence`);
      if (!state.lastOdoReading) areas.push('No odometer reading recorded for this session');
      const unsorted = state.trips.filter(t => t.type === null);
      if (unsorted.length > 0) areas.push(`${unsorted.length} trip${unsorted.length > 1 ? 's' : ''} not sorted yet`);
      if (areas.length === 0) areas.push('All clear \u2014 looking good for ATO compliance');
      const sameSessionReports = state.savedReports.filter(r => r.sessionId === state.sessionId);
      const revisionNum = sameSessionReports.length + 1;
      const isRevision = sameSessionReports.length > 0;
      if (isRevision) {
        areas.unshift('This is a revised report \u2014 verify changes against previous version');
      }
      const report: SavedReport = {
        sessionId: state.sessionId,
        timestamp: ts,
        bizCount: biz.length,
        perCount: per.length,
        classified,
        unclassified: biz.length - classified,
        est: '$' + Math.round(state.dedTotal).toLocaleString('en-AU'),
        totalKm: biz.reduce((s, t) => s + t.km, 0).toFixed(1),
        auditScore: (() => {
          const st = state.trips.filter(t => t.type !== null);
          const tot = st.length;
          if (tot === 0) return 0;
          const bizKmLocal = biz.reduce((s, t) => s + t.km, 0);
          const totKmLocal = state.trips.reduce((s, t) => s + t.km, 0);
          const bizPctLocal = totKmLocal > 0 ? (bizKmLocal / totKmLocal) * 100 : 0;
          return calcAuditScore({
            totalTrips: state.trips.length,
            sortedTrips: tot,
            verifiedCount: state.verifiedSet.size,
            photoCount: state.trips.filter(t => t.photo).length,
            bizPct: bizPctLocal,
            notesCount: biz.filter(t => t.notes && t.notes.length > 0).length,
            bizCount: biz.length,
          }).total;
        })(),
        lastOdoReading: state.lastOdoReading,
        lastOdoVerifiedAt: state.lastOdoVerifiedAt,
        odoRangeStart: getTripOdoStart(state.trips, 0, state.baseOdo),
        odoRangeEnd: getTripOdoEnd(state.trips, state.trips.length - 1, state.baseOdo),
        trips: tripSummaries,
        auditLog: state.auditLog.map(e => ({ time: e.time, desc: e.desc })),
        areasToCheck: areas,
        revision: revisionNum,
        supersedes: false,
      };
      const updatedPrevious = state.savedReports.map(r =>
        r.sessionId === state.sessionId ? { ...r, supersedes: true } : r
      );
      return {
        ...state,
        savedReports: [report, ...updatedPrevious],
        summaryModalOpen: false,
        conflictResolved: false,
        freshSession: false,
        currentScreen: 'reports',
      };
    }
    case 'SET_MANUAL_ODO':
      return {
        ...state,
        lastOdoReading: action.reading,
        lastOdoVerifiedAt: nowStr(),
        auditLog: [{ time: nowStr(), desc: `Odometer manually set to ${action.reading.toLocaleString('en-AU')} km`, hasPhoto: false }, ...state.auditLog],
      };
    case 'ADD_LOG':
      return {
        ...state,
        auditLog: [{ time: nowStr(), desc: action.desc, hasPhoto: action.hasPhoto }, ...state.auditLog],
      };
    case 'RESET_DEMO':
      return {
        ...initialState,
        vehicle: state.vehicle,
        vehicleId: state.vehicleId,
        profile: state.profile,
        expenses: state.expenses,
        logbookPeriods: state.logbookPeriods,
        isLoading: false,
        isInitialised: true,
        savedReports: state.savedReports,
        sessionStartTime: Date.now(),
      };
    case 'LOAD_BATCH2': {
      const prevActive = state.savedReports.filter(r => !r.supersedes && r.sessionId !== 'batch2');
      const prevOdoEnd =
        prevActive.length > 0
          ? Math.max(...prevActive.map(r => r.odoRangeEnd ?? ODO_START))
          : ODO_START;
      const queued = state.queuedTrips;
      const batch = queued.slice(0, BATCH_SIZE).map(t => ({ ...t }));
      const stillQueued = queued.slice(BATCH_SIZE).map(t => ({ ...t }));
      return {
        ...initialState,
        trips: batch,
        queuedTrips: stillQueued,
        vehicle: state.vehicle,
        vehicleId: state.vehicleId,
        profile: state.profile,
        expenses: state.expenses,
        logbookPeriods: state.logbookPeriods,
        isLoading: false,
        isInitialised: true,
        savedReports: state.savedReports,
        sessionStartTime: Date.now(),
        sessionId: 'batch2',
        baseOdo: prevOdoEnd,
      };
    }
    case 'DELETE_ALL_TRIPS': {
      const nextBatch = state.queuedTrips.slice(0, BATCH_SIZE).map(t => ({ ...t }));
      const stillQueued = state.queuedTrips.slice(BATCH_SIZE).map(t => ({ ...t }));
      const hasMore = nextBatch.length > 0;
      const latestReport = state.savedReports.find(r => !r.supersedes);
      const reportOdoEnd = latestReport?.odoRangeEnd;
      const manualOdo = state.lastOdoReading;
      const calcOdo =
        state.trips.length > 0
          ? Math.round(getTripOdoEnd(state.trips, state.trips.length - 1, state.baseOdo))
          : state.baseOdo;
      const newBaseOdo = manualOdo ?? reportOdoEnd ?? calcOdo;
      const newSessionId = 'session_' + Date.now();
      return {
        ...initialState,
        trips: nextBatch,
        queuedTrips: stillQueued,
        vehicle: state.vehicle,
        vehicleId: state.vehicleId,
        profile: state.profile,
        expenses: state.expenses,
        logbookPeriods: state.logbookPeriods,
        isLoading: false,
        isInitialised: true,
        savedReports: state.savedReports,
        baseOdo: newBaseOdo,
        lastOdoReading: newBaseOdo,
        sessionId: newSessionId,
        sessionStartTime: Date.now(),
        freshSession: hasMore,
        auditLog: [
          ...(hasMore
            ? [{ time: nowStr(), desc: `Next batch loaded — ${nextBatch.length} trip${nextBatch.length !== 1 ? 's' : ''} ready to sort`, hasPhoto: false }]
            : []),
          { time: nowStr(), desc: 'All sort cards deleted by user', hasPhoto: false },
          ...state.auditLog,
        ],
      };
    }
    case 'DELETE_SESSION': {
      const remaining = state.savedReports.filter(r => r.sessionId !== action.sessionId);
      const isCurrentSession = state.sessionId === action.sessionId;
      return {
        ...initialState,
        trips: isCurrentSession ? [] : state.trips,
        vehicle: state.vehicle,
        vehicleId: state.vehicleId,
        profile: state.profile,
        expenses: state.expenses,
        logbookPeriods: state.logbookPeriods,
        isLoading: false,
        isInitialised: true,
        savedReports: remaining,
        sessionId: state.sessionId,
        baseOdo: isCurrentSession ? initialState.baseOdo : state.baseOdo,
        sessionStartTime: Date.now(),
        freshSession: true,
        auditLog: [
          {
            time: nowStr(),
            desc: `Session "${action.sessionId}" deleted — reports removed. Can be re-sorted anytime.`,
            hasPhoto: false,
          },
          ...state.auditLog,
        ],
      };
    }
    case 'COME_BACK_LATER':
      return {
        ...state,
        pendingFinalise: true,
        currentScreen: 'sort' as Screen,
        auditLog: [{ time: nowStr(), desc: 'User paused session — will return to finalise', hasPhoto: false }, ...state.auditLog],
      };
    case 'RESUME_SORTING':
      return {
        ...state,
        pendingFinalise: false,
        auditLog: [{ time: nowStr(), desc: 'User resumed sorting session', hasPhoto: false }, ...state.auditLog],
      };
    case 'ADD_TRIP': {
      const newTrips = [...state.trips];
      const tripTime = new Date(action.trip.year, action.trip.month, action.trip.day).getTime();
      let insertIdx = newTrips.length;
      for (let i = 0; i < newTrips.length; i++) {
        const tTime = new Date(newTrips[i].year, newTrips[i].month, newTrips[i].day).getTime();
        if (tTime > tripTime) {
          insertIdx = i;
          break;
        }
        if (tTime === tripTime && (action.trip.time || '') < (newTrips[i].time || '')) {
          insertIdx = i;
          break;
        }
      }
      newTrips.splice(insertIdx, 0, action.trip);
      const newCurrentIndex = state.currentIndex + 1;
      const sortedSlice = newTrips.slice(0, newCurrentIndex);
      const newBiz = sortedSlice.filter(t => t.type === 'business').length;
      const newPer = sortedSlice.filter(t => t.type === 'personal').length;
      const newDed = computeDedTotal(state, newTrips, newCurrentIndex);
      const newVerified = new Set(state.verifiedSet);
      for (let i = insertIdx; i < newTrips.length; i++) {
        if (newTrips[i].odoReading != null || newTrips[i].odoStartReading != null) {
          newTrips[i] = { ...newTrips[i], odoReading: null, odoStartReading: null, verified: false };
          newVerified.delete(i);
        }
      }
      return {
        ...state,
        trips: newTrips,
        currentIndex: newCurrentIndex,
        bizCount: newBiz,
        perCount: newPer,
        dedTotal: newDed,
        verifiedSet: newVerified,
        auditLog: [{ time: nowStr(), desc: `Trip added: ${action.trip.from} → ${action.trip.to} (${action.trip.km} km, ${action.trip.type})`, hasPhoto: false }, ...state.auditLog],
      };
    }
    case 'CONFIRM_GAP': {
      const newTrips = state.trips.map((t, i) =>
        i === action.tripIndex ? { ...t, gapConfirmed: true, km: action.km } : t
      );
      return {
        ...state,
        trips: newTrips,
        auditLog: [{ time: nowStr(), desc: `Gap confirmed: ${state.trips[action.tripIndex].from} → ${state.trips[action.tripIndex].to} (${action.km} km)`, hasPhoto: false }, ...state.auditLog],
      };
    }
    case 'DELETE_GAP': {
      const newTrips = state.trips.filter((_, i) => i !== action.tripIndex);
      return {
        ...state,
        trips: newTrips,
        auditLog: [{ time: nowStr(), desc: `Gap deleted: ${state.trips[action.tripIndex].from} → ${state.trips[action.tripIndex].to}`, hasPhoto: false }, ...state.auditLog],
      };
    }
    case 'PROMOTE_REPORT': {
      const idx = action.reportIndex;
      const targetSessionId = state.savedReports[idx].sessionId;
      const updated = state.savedReports.map((r, i) => ({
        ...r,
        supersedes: r.sessionId === targetSessionId ? i !== idx : r.supersedes,
      }));
      return {
        ...state,
        savedReports: updated,
        conflictResolved: true,
        auditLog: [{ time: nowStr(), desc: `Report Rev ${state.savedReports[idx].revision} promoted to active`, hasPhoto: false }, ...state.auditLog],
      };
    }
    default:
      return state;
  }
}

// ── Context ──────────────────────────────────────────────────

const AppContext = createContext<{
  state: AppState;
  dispatch: React.Dispatch<Action>;
} | null>(null);

// ── Provider with Supabase sync ──────────────────────────────

export function AppProvider({ children }: { children: ReactNode }) {
  const [state, dispatch] = useReducer(reducer, initialState);
  const stateRef = useRef(state);
  stateRef.current = state;

  // ── Initial data load ──────────────────────────────────────
  useEffect(() => {
    let cancelled = false;

    async function loadInitialData() {
      try {
        const fy = getCurrentFY();

        const [profile, vehicles] = await Promise.all([
          getProfile(),
          getVehicles(),
        ]);

        const vehicle = vehicles[0] ?? null;
        const vehicleId = vehicle?.id ?? null;

        const [trips, expenses, logbookPeriods] = vehicleId
          ? await Promise.all([
              getTrips(vehicleId, fy),
              getExpenses(vehicleId, fy),
              getLogbookPeriods(vehicleId),
            ])
          : [[], [], []];

        if (cancelled) return;

        const baseOdo = vehicle?.odometerAtStart ?? ODO_START;
        const tripList = (trips as AppTrip[]).map((t, i) => appTripToTrip(t, i));

        dispatch({
          type: 'DB_LOADED',
          trips: tripList,
          vehicle,
          vehicleId,
          profile,
          expenses: expenses as AppExpense[],
          logbookPeriods: logbookPeriods as AppLogbookPeriod[],
          baseOdo,
        });
      } catch (err) {
        if (!cancelled) {
          dispatch({ type: 'DB_ERROR', error: String(err) });
        }
      }
    }

    loadInitialData();
    return () => { cancelled = true; };
  }, []);

  // ── Supabase side-effects ────────────────
  const dispatchWithSync = useCallback(async (action: Action) => {
    dispatch(action);

    const s = stateRef.current;
    const vehicleId = s.vehicleId;

    try {
      switch (action.type) {
        case 'CLASSIFY_TRIP': {
          const trip = s.trips[s.currentIndex];
          if (trip?.dbId && vehicleId) {
            await classifyTrip(trip.dbId, action.tripType);
          }
          break;
        }
        case 'RECLASSIFY': {
          const trip = s.trips[action.tripIndex];
          if (trip?.dbId) {
            await classifyTrip(trip.dbId, action.tripType);
          }
          break;
        }
        case 'SET_PURPOSE': {
          const trip = s.trips[action.tripIndex];
          if (trip?.dbId) {
            await updateTrip(trip.dbId, { purposeLabel: action.purposeLabel });
          }
          break;
        }
        case 'VERIFY_TRIP': {
          const trip = s.trips[action.tripIndex];
          if (trip?.dbId) {
            await updateTrip(trip.dbId, {
              verified: true,
              odoStartReading: action.startReading,
              odoReading: action.reading,
              photo: action.photo || trip.photo,
            });
          }
          break;
        }
        case 'ADD_PHOTO': {
          const trip = s.trips[action.tripIndex];
          if (trip?.dbId) {
            await updateTrip(trip.dbId, { photo: true });
          }
          break;
        }
        case 'UPDATE_TRIP': {
          const trip = s.trips[action.tripIndex];
          if (trip?.dbId) {
            await updateTrip(trip.dbId, action.updates as Partial<AppTrip>);
          }
          break;
        }
        case 'ADD_TRIP': {
          if (vehicleId) {
            const saved = await saveTrip(vehicleId, action.trip as unknown as Partial<AppTrip> & { startTime?: string; endTime?: string });
            if (saved?.id) {
              const idx = stateRef.current.trips.findIndex(
                t => t.from === action.trip.from && t.to === action.trip.to && t.time === action.trip.time
              );
              if (idx >= 0) {
                dispatch({ type: 'UPDATE_TRIP', tripIndex: idx, updates: { dbId: saved.id } });
              }
            }
          }
          break;
        }
        case 'DELETE_GAP': {
          const trip = s.trips[action.tripIndex];
          if (trip?.dbId) {
            await deleteTrip(trip.dbId);
          }
          break;
        }
        case 'CONFIRM_GAP': {
          const trip = s.trips[action.tripIndex];
          if (trip?.dbId) {
            await updateTrip(trip.dbId, { gapConfirmed: true, km: action.km });
          }
          break;
        }
        case 'SET_MANUAL_ODO': {
          await logAuditEvent('vehicle', vehicleId, 'manual_odo_set', { reading: action.reading });
          break;
        }
        case 'SAVE_SESSION': {
          if (vehicleId) {
            setTimeout(async () => {
              const currentState = stateRef.current;
              const report = currentState.savedReports[0];
              if (report && !report.dbId) {
                const saved = await saveReport(
                  vehicleId,
                  'session_summary',
                  {
                    sessionId: report.sessionId,
                    bizCount: report.bizCount,
                    perCount: report.perCount,
                    classified: report.classified,
                    unclassified: report.unclassified,
                    est: report.est,
                    totalKm: report.totalKm,
                    auditScore: report.auditScore,
                    lastOdoReading: report.lastOdoReading,
                    odoRangeStart: report.odoRangeStart,
                    odoRangeEnd: report.odoRangeEnd,
                    trips: report.trips,
                    auditLog: report.auditLog,
                    areasToCheck: report.areasToCheck,
                    revision: report.revision,
                  },
                  `Session Report — ${report.timestamp}`
                );
                if (saved?.id) {
                  dispatch({ type: 'REPORT_SAVED_TO_DB', sessionId: report.sessionId, dbId: saved.id });
                }
              }
            }, 0);
          }
          break;
        }
        case 'DELETE_SESSION': {
          const toDelete = s.savedReports.filter(r => r.sessionId === action.sessionId && r.dbId);
          await Promise.all(toDelete.map(r => deleteReport(r.dbId!)));
          break;
        }
        default:
          break;
      }
    } catch (err) {
      console.warn('[AppContext] Supabase sync failed for action', action.type, err);
    }
  }, []);

  return (
    <AppContext.Provider value={{ state, dispatch: dispatchWithSync }}>
      {children}
    </AppContext.Provider>
  );
}

// ── Hooks ────────────────────────────────────────────────────

export function useApp() {
  const ctx = useContext(AppContext);
  if (!ctx) throw new Error('useApp must be used within AppProvider');
  return ctx;
}

export function useComputedStats() {
  const { state } = useApp();
  const currentBizKm = state.trips.slice(0, state.currentIndex).filter(x => x.type === 'business').reduce((a, x) => a + x.km, 0);
  const currentTotKm = state.trips.slice(0, state.currentIndex).reduce((a, x) => a + x.km, 0);
  const currentSessionHasReport = state.savedReports.some(r => r.sessionId === state.sessionId && !r.supersedes);
  const savedBizKm = state.savedReports
    .filter(r => !r.supersedes)
    .reduce((a, r) => a + (r.trips || []).filter(t => t.type === 'business').reduce((s, t) => s + t.km, 0), 0);
  const savedTotKm = state.savedReports
    .filter(r => !r.supersedes)
    .reduce((a, r) => a + (r.trips || []).reduce((s, t) => s + t.km, 0), 0);
  const bizKm = savedBizKm + (currentSessionHasReport ? 0 : currentBizKm);
  const totKm = savedTotKm + (currentSessionHasReport ? 0 : currentTotKm);
  const bizPct = totKm > 0 ? (bizKm / totKm * 100) : 0;
  const remaining = state.trips.length - state.currentIndex;
  const progress = state.trips.length > 0 ? (state.currentIndex / state.trips.length * 100) : 0;
  const sortedTripsArr = state.trips.filter(t => t.type !== null);
  const bizTripsArr = state.trips.filter(t => t.type === 'business');
  const auditResult = calcAuditScore({
    totalTrips: state.trips.length,
    sortedTrips: sortedTripsArr.length,
    verifiedCount: state.verifiedSet.size,
    photoCount: state.trips.filter(t => t.photo).length,
    bizPct,
    notesCount: bizTripsArr.filter(t => t.notes && t.notes.length > 0).length,
    bizCount: bizTripsArr.length,
  });
  const auditScore = auditResult.total;
  return { bizKm, totKm, bizPct, remaining, progress, auditScore };
}
