import { createContext, useContext, useReducer, useCallback, type ReactNode } from 'react';
import { type Trip, initialTrips, batch2Trips, RATE, ODO_START, getTripOdoStart, getTripOdoEnd, generateConnectorTrips } from './trip-data';

export type Screen = 'dashboard' | 'sort' | 'classify' | 'review' | 'notes' | 'odometer' | 'reports' | 'export' | 'input' | 'expenses' | 'stats' | 'find-keys';

export const INDUSTRY_BIZ_AVG = 65;

export function calcAuditScore(params: {
  totalTrips: number;
  sortedTrips: number;
  verifiedCount: number;
  photoCount: number;
  bizPct: number;
  notesCount?: number;
  bizCount?: number;
}) {
  const { totalTrips, sortedTrips, verifiedCount, photoCount, bizPct, notesCount = 0, bizCount = 0 } = params;
  if (sortedTrips === 0) return { classifiedPct: 0, verifiedPct: 0, photoPct: 0, ratioPct: 0, notesPct: 0, classifiedContrib: 0, verifiedContrib: 0, photoContrib: 0, ratioContrib: 0, notesContrib: 0, total: 0 };
  const classifiedPct = sortedTrips > 0 ? 100 : 0;
  const verifiedPct = (verifiedCount / sortedTrips) * 100;
  const photoPct = (photoCount / sortedTrips) * 100;
  const notesPct = bizCount > 0 ? (notesCount / bizCount) * 100 : 0;
  const deviation = Math.abs(bizPct - INDUSTRY_BIZ_AVG);
  const ratioPct = Math.max(0, 100 - (deviation / INDUSTRY_BIZ_AVG) * 100);
  const classifiedContrib = Math.round(classifiedPct * 0.30);
  const verifiedContrib = Math.round(verifiedPct * 0.25);
  const photoContrib = Math.round(photoPct * 0.10);
  const notesContrib = Math.round(notesPct * 0.10);
  const ratioContrib = Math.round(ratioPct * 0.24);
  const total = Math.min(99, classifiedContrib + verifiedContrib + photoContrib + notesContrib + ratioContrib);
  return { classifiedPct, verifiedPct, photoPct, ratioPct, notesPct, classifiedContrib, verifiedContrib, photoContrib, ratioContrib, notesContrib, total };
}

interface SavedTripSummary {
  from: string;
  to: string;
  km: number;
  date: string;
  time: string;
  type: 'business' | 'personal' | null;
  purposeLabel: string | null;
  verified: boolean;
  photo: boolean;
  odoStart: number;
  odoEnd: number;
  notes: string;
  autoGenerated?: boolean;
}

interface SavedReport {
  sessionId: string;
  timestamp: string;
  bizCount: number;
  perCount: number;
  classified: number;
  unclassified: number;
  est: string;
  totalKm: string;
  auditScore: number;
  lastOdoReading: number | null;
  lastOdoVerifiedAt: string | null;
  odoRangeStart: number;
  odoRangeEnd: number;
  trips: SavedTripSummary[];
  auditLog: { time: string; desc: string }[];
  areasToCheck: string[];
  revision: number;
  supersedes: boolean;
}

interface AppState {
  trips: Trip[];
  currentScreen: Screen;
  currentIndex: number;
  dedTotal: number;
  bizCount: number;
  perCount: number;
  lastAction: { idx: number; type: string; ded: number } | null;
  verifiedSet: Set<number>;
  auditLog: { time: string; desc: string; hasPhoto: boolean }[];
  savedReports: SavedReport[];
  lastOdoReading: number | null;
  lastOdoVerifiedAt: string | null;
  classifyStep: number;
  classifyBizTrips: number[];
  sessionStartTime: number;
  editModalOpen: boolean;
  editTripIndex: number;
  atoModalOpen: boolean;
  summaryModalOpen: boolean;
  conflictResolved: boolean;
  freshSession: boolean;
  pendingFinalise: boolean;
  sessionId: string;
  baseOdo: number;
}

type Action =
  | { type: 'CLASSIFY_TRIP'; tripType: 'business' | 'personal' }
  | { type: 'UNDO_LAST' }
  | { type: 'GO_SCREEN'; screen: Screen }
  | { type: 'SET_PURPOSE'; tripIndex: number; purposeLabel: string; purposeIndex: number | null }
  | { type: 'CLASSIFY_NEXT' }
  | { type: 'INIT_CLASSIFY' }
  | { type: 'RECLASSIFY'; tripIndex: number; tripType: 'business' | 'personal' }
  | { type: 'VERIFY_TRIP'; tripIndex: number; startReading: number; reading: number; photo: boolean }
  | { type: 'ADD_PHOTO'; tripIndex: number }
  | { type: 'UPDATE_TRIP'; tripIndex: number; updates: Partial<Trip> }
  | { type: 'OPEN_EDIT'; tripIndex: number }
  | { type: 'CLOSE_EDIT' }
  | { type: 'OPEN_ATO' }
  | { type: 'CLOSE_ATO' }
  | { type: 'OPEN_SUMMARY' }
  | { type: 'CLOSE_SUMMARY' }
  | { type: 'SAVE_SESSION' }
  | { type: 'ADD_LOG'; desc: string; hasPhoto: boolean }
  | { type: 'SET_MANUAL_ODO'; reading: number }
  | { type: 'RESET_DEMO' }
  | { type: 'LOAD_BATCH2' }
  | { type: 'DELETE_ALL_TRIPS' }
  | { type: 'DELETE_SESSION'; sessionId: string }
  | { type: 'PROMOTE_REPORT'; reportIndex: number }
  | { type: 'COME_BACK_LATER' }
  | { type: 'RESUME_SORTING' }
  | { type: 'ADD_TRIP'; trip: Trip }
  | { type: 'CONFIRM_GAP'; tripIndex: number; km: number }
  | { type: 'DELETE_GAP'; tripIndex: number };


function nowStr(): string {
  const n = new Date();
  return n.toLocaleDateString('en-AU', { day: '2-digit', month: 'short' }) + ' ' + n.toLocaleTimeString('en-AU', { hour: '2-digit', minute: '2-digit' });
}

const initialState: AppState = {
  trips: initialTrips.map(t => ({ ...t })),
  currentScreen: 'dashboard',
  currentIndex: 0,
  dedTotal: 0,
  bizCount: 0,
  perCount: 0,
  lastAction: null,
  verifiedSet: new Set(),
  auditLog: [],
  savedReports: [],
  lastOdoReading: null,
  lastOdoVerifiedAt: null,
  classifyStep: 0,
  classifyBizTrips: [],
  sessionStartTime: Date.now(),
  editModalOpen: false,
  editTripIndex: 0,
  atoModalOpen: false,
  summaryModalOpen: false,
  conflictResolved: false,
  freshSession: true,
  pendingFinalise: false,
  sessionId: 'batch1',
  baseOdo: ODO_START,
};

function reducer(state: AppState, action: Action): AppState {
  switch (action.type) {
    case 'CLASSIFY_TRIP': {
      const trip = state.trips[state.currentIndex];
      if (!trip) return state;
      const newTrips = [...state.trips];
      newTrips[state.currentIndex] = { ...trip, type: action.tripType };
      const isBiz = action.tripType === 'business';
      const earned = isBiz ? trip.km * RATE : 0;
      return {
        ...state,
        trips: newTrips,
        dedTotal: state.dedTotal + earned,
        bizCount: state.bizCount + (isBiz ? 1 : 0),
        perCount: state.perCount + (isBiz ? 0 : 1),
        lastAction: { idx: state.currentIndex, type: action.tripType, ded: earned },
        currentIndex: state.currentIndex + 1,
        freshSession: true,
      };
    }
    case 'UNDO_LAST': {
      if (!state.lastAction) return state;
      const { idx } = state.lastAction;
      const newTrips = [...state.trips];
      newTrips[idx] = { ...newTrips[idx], type: null };
      const undoSlice = newTrips.slice(0, idx);
      return {
        ...state,
        trips: newTrips,
        currentIndex: idx,
        dedTotal: undoSlice.filter(t => t.type === 'business').reduce((s, t) => s + t.km * RATE, 0),
        bizCount: undoSlice.filter(t => t.type === 'business').length,
        perCount: undoSlice.filter(t => t.type === 'personal').length,
        lastAction: null,
      };
    }
    case 'GO_SCREEN':
      return { ...state, currentScreen: action.screen };
    case 'SET_PURPOSE': {
      const newTrips = [...state.trips];
      newTrips[action.tripIndex] = {
        ...newTrips[action.tripIndex],
        purposeLabel: action.purposeLabel,
        purposeIndex: action.purposeIndex,
      };
      return { ...state, trips: newTrips };
    }
    case 'INIT_CLASSIFY': {
      const existingConnectors = state.trips.filter(t => t.autoGenerated);
      const realTrips = existingConnectors.length > 0
        ? state.trips.filter(t => !t.autoGenerated)
        : state.trips;
      const connectors = generateConnectorTrips(realTrips);
      let mergedTrips: Trip[];
      if (connectors.length > 0) {
        const all = [...realTrips, ...connectors];
        all.sort((a, b) => {
          const da = new Date(a.year, a.month, a.day).getTime();
          const db = new Date(b.year, b.month, b.day).getTime();
          if (da !== db) return da - db;
          if (a.autoGenerated && !b.autoGenerated) return 1;
          if (!a.autoGenerated && b.autoGenerated) return -1;
          return (a.time || '').localeCompare(b.time || '');
        });
        mergedTrips = all;
      } else {
        mergedTrips = realTrips;
      }
      const newCurrentIndex = mergedTrips.filter(t => t.type !== null).length;
      const sortedSlice = mergedTrips.slice(0, newCurrentIndex);
      const newDedTotal = sortedSlice.filter(t => t.type === 'business').reduce((s, t) => s + t.km * RATE, 0);
      const newBizCount = sortedSlice.filter(t => t.type === 'business').length;
      const newPerCount = sortedSlice.filter(t => t.type === 'personal').length;
      const bizTrips = mergedTrips.map((t, i) => i).filter(i => mergedTrips[i].type === 'business');
      return {
        ...state,
        trips: mergedTrips,
        currentIndex: newCurrentIndex,
        dedTotal: newDedTotal,
        bizCount: newBizCount,
        perCount: newPerCount,
        classifyStep: 0,
        classifyBizTrips: bizTrips,
        currentScreen: bizTrips.length > 0 ? 'classify' : 'review',
      };
    }
    case 'CLASSIFY_NEXT': {
      const nextStep = state.classifyStep + 1;
      if (nextStep >= state.classifyBizTrips.length) {
        return { ...state, classifyStep: nextStep, currentScreen: 'review' };
      }
      return { ...state, classifyStep: nextStep };
    }
    case 'RECLASSIFY': {
      const newTrips = [...state.trips];
      const trip = newTrips[action.tripIndex];
      const oldType = trip.type;
      newTrips[action.tripIndex] = { ...trip, type: action.tripType };
      const sortedSlice = newTrips.slice(0, state.currentIndex);
      const newBiz = sortedSlice.filter(t => t.type === 'business').length;
      const newPer = sortedSlice.filter(t => t.type === 'personal').length;
      const newDed = sortedSlice
        .filter(t => t.type === 'business')
        .reduce((s, t) => s + t.km * RATE, 0);
      const reclassDesc = `Reclassified "${trip.from} \u2192 ${trip.to}" from ${oldType || 'unsorted'} to ${action.tripType}`;
      return {
        ...state,
        trips: newTrips,
        dedTotal: newDed,
        bizCount: newBiz,
        perCount: newPer,
        auditLog: [{ time: nowStr(), desc: reclassDesc, hasPhoto: false }, ...state.auditLog],
      };
    }
    case 'VERIFY_TRIP': {
      const newTrips = [...state.trips];
      newTrips[action.tripIndex] = {
        ...newTrips[action.tripIndex],
        verified: true,
        odoStartReading: action.startReading,
        odoReading: action.reading,
        photo: action.photo || newTrips[action.tripIndex].photo,
      };
      const newVerified = new Set(state.verifiedSet);
      newVerified.add(action.tripIndex);
      return {
        ...state,
        trips: newTrips,
        verifiedSet: newVerified,
        lastOdoReading: action.reading,
        lastOdoVerifiedAt: nowStr(),
        auditLog: [{ time: nowStr(), desc: `Trip verified: ${newTrips[action.tripIndex].from} \u2192 ${newTrips[action.tripIndex].to}`, hasPhoto: action.photo }, ...state.auditLog],
      };
    }
    case 'ADD_PHOTO': {
      const newTrips = [...state.trips];
      newTrips[action.tripIndex] = { ...newTrips[action.tripIndex], photo: true };
      return {
        ...state,
        trips: newTrips,
        auditLog: [{ time: nowStr(), desc: `Photo added: ${newTrips[action.tripIndex].from} \u2192 ${newTrips[action.tripIndex].to}`, hasPhoto: true }, ...state.auditLog],
      };
    }
    case 'UPDATE_TRIP': {
      const newTrips = [...state.trips];
      const oldTrip = newTrips[action.tripIndex];
      const kmChanged = action.updates.km != null && action.updates.km !== oldTrip.km;
      const routeChanged = kmChanged || action.updates.from != null || action.updates.to != null || action.updates.stops != null;
      newTrips[action.tripIndex] = { ...oldTrip, ...action.updates };
      if (routeChanged) {
        newTrips[action.tripIndex].odoReading = null;
        newTrips[action.tripIndex].odoStartReading = null;
        newTrips[action.tripIndex].verified = false;
      }
      const newVerified = new Set(state.verifiedSet);
      if (routeChanged) {
        newVerified.delete(action.tripIndex);
        for (let i = action.tripIndex + 1; i < newTrips.length; i++) {
          if (newTrips[i].odoStartReading != null || newTrips[i].odoReading != null) {
            newTrips[i] = { ...newTrips[i], odoStartReading: null, odoReading: null, verified: false };
            newVerified.delete(i);
          }
        }
      }
      const sortedForCount = newTrips.slice(0, state.currentIndex);
      const newBizCount = sortedForCount.filter(t => t.type === 'business').length;
      const newPerCount = sortedForCount.filter(t => t.type === 'personal').length;
      const newDedTotal = sortedForCount
        .filter(t => t.type === 'business')
        .reduce((s, t) => s + t.km * RATE, 0);
      const editDesc = routeChanged
        ? `Route edited: ${newTrips[action.tripIndex].from} → ${newTrips[action.tripIndex].to} (${newTrips[action.tripIndex].km.toFixed(1)} km)`
        : `Edited trip: ${newTrips[action.tripIndex].from} → ${newTrips[action.tripIndex].to}`;
      return {
        ...state,
        trips: newTrips,
        verifiedSet: newVerified,
        bizCount: newBizCount,
        perCount: newPerCount,
        dedTotal: newDedTotal,
        auditLog: [{ time: nowStr(), desc: editDesc, hasPhoto: false }, ...state.auditLog],
      };
    }
    case 'OPEN_EDIT':
      return { ...state, editModalOpen: true, editTripIndex: action.tripIndex };
    case 'CLOSE_EDIT':
      return { ...state, editModalOpen: false };
    case 'OPEN_ATO':
      return { ...state, atoModalOpen: true };
    case 'CLOSE_ATO':
      return { ...state, atoModalOpen: false };
    case 'OPEN_SUMMARY':
      return { ...state, summaryModalOpen: true };
    case 'CLOSE_SUMMARY':
      return { ...state, summaryModalOpen: false };
    case 'SAVE_SESSION': {
      const biz = state.trips.filter(t => t.type === 'business');
      const per = state.trips.filter(t => t.type === 'personal');
      const classified = biz.filter(t => t.purposeLabel).length;
      const now = new Date();
      const ts = now.toLocaleDateString('en-AU', { weekday: 'short', day: '2-digit', month: 'short', year: 'numeric' }) +
        ' \u00B7 ' + now.toLocaleTimeString('en-AU', { hour: '2-digit', minute: '2-digit' });
      const sortedTrips = state.trips.filter(t => t.type !== null);
      const tripSummaries: SavedTripSummary[] = sortedTrips.map(t => {
        const origIdx = state.trips.indexOf(t);
        return {
          from: t.from, to: t.to, km: t.km, date: t.date, time: t.time,
          type: t.type, purposeLabel: t.purposeLabel, verified: t.verified, photo: t.photo,
          odoStart: getTripOdoStart(state.trips, origIdx, state.baseOdo),
          odoEnd: getTripOdoEnd(state.trips, origIdx, state.baseOdo),
          notes: t.notes || '',
          autoGenerated: t.autoGenerated || false,
        };
      });
      const areas: string[] = [];
      const unverifiedBiz = biz.filter(t => !t.verified);
      if (unverifiedBiz.length > 0) areas.push(`${unverifiedBiz.length} business trip${unverifiedBiz.length > 1 ? 's' : ''} not odometer-verified`);
      const noPurpose = biz.filter(t => !t.purposeLabel);
      if (noPurpose.length > 0) areas.push(`${noPurpose.length} business trip${noPurpose.length > 1 ? 's' : ''} missing purpose category`);
      const noNotes = biz.filter(t => !t.notes || t.notes.length === 0);
      if (noNotes.length > 0) areas.push(`${noNotes.length} business trip${noNotes.length > 1 ? 's' : ''} without trip notes`);
      const noPhoto = biz.filter(t => !t.photo);
      if (noPhoto.length > 0) areas.push(`${noPhoto.length} business trip${noPhoto.length > 1 ? 's' : ''} without photo evidence`);
      if (!state.lastOdoReading) areas.push('No odometer reading recorded for this session');
      const unsorted = state.trips.filter(t => t.type === null);
      if (unsorted.length > 0) areas.push(`${unsorted.length} trip${unsorted.length > 1 ? 's' : ''} not sorted yet`);
      if (areas.length === 0) areas.push('All clear \u2014 looking good for ATO compliance');
      const sameSessionReports = state.savedReports.filter(r => r.sessionId === state.sessionId);
      const revisionNum = sameSessionReports.length + 1;
      const isRevision = sameSessionReports.length > 0;
      if (isRevision) {
        areas.unshift('This is a revised report \u2014 verify changes against previous version');
      }
      const report: SavedReport = {
        sessionId: state.sessionId,
        timestamp: ts,
        bizCount: biz.length,
        perCount: per.length,
        classified,
        unclassified: biz.length - classified,
        est: '$' + Math.round(state.dedTotal).toLocaleString('en-AU'),
        totalKm: biz.reduce((s, t) => s + t.km, 0).toFixed(1),
        auditScore: (() => {
          const st = state.trips.filter(t => t.type !== null);
          const tot = st.length;
          if (tot === 0) return 0;
          const bizKmLocal = biz.reduce((s, t) => s + t.km, 0);
          const totKmLocal = state.trips.reduce((s, t) => s + t.km, 0);
          const bizPctLocal = totKmLocal > 0 ? (bizKmLocal / totKmLocal) * 100 : 0;
          return calcAuditScore({
            totalTrips: state.trips.length,
            sortedTrips: tot,
            verifiedCount: state.verifiedSet.size,
            photoCount: state.trips.filter(t => t.photo).length,
            bizPct: bizPctLocal,
            notesCount: biz.filter(t => t.notes && t.notes.length > 0).length,
            bizCount: biz.length,
          }).total;
        })(),
        lastOdoReading: state.lastOdoReading,
        lastOdoVerifiedAt: state.lastOdoVerifiedAt,
        odoRangeStart: getTripOdoStart(state.trips, 0, state.baseOdo),
        odoRangeEnd: getTripOdoEnd(state.trips, state.trips.length - 1, state.baseOdo),
        trips: tripSummaries,
        auditLog: state.auditLog.map(e => ({ time: e.time, desc: e.desc })),
        areasToCheck: areas,
        revision: revisionNum,
        supersedes: false,
      };
      const updatedPrevious = state.savedReports.map(r =>
        r.sessionId === state.sessionId ? { ...r, supersedes: true } : r
      );
      return {
        ...state,
        savedReports: [report, ...updatedPrevious],
        summaryModalOpen: false,
        conflictResolved: false,
        freshSession: false,
        currentScreen: 'reports',
      };
    }
    case 'SET_MANUAL_ODO':
      return {
        ...state,
        lastOdoReading: action.reading,
        lastOdoVerifiedAt: nowStr(),
        auditLog: [{ time: nowStr(), desc: `Odometer manually set to ${action.reading.toLocaleString('en-AU')} km`, hasPhoto: false }, ...state.auditLog],
      };
    case 'ADD_LOG':
      return {
        ...state,
        auditLog: [{ time: nowStr(), desc: action.desc, hasPhoto: action.hasPhoto }, ...state.auditLog],
      };
    case 'RESET_DEMO':
      return {
        ...initialState,
        trips: initialTrips.map(t => ({ ...t })),
        savedReports: state.savedReports,
        sessionStartTime: Date.now(),
      };
    case 'LOAD_BATCH2': {
      const prevActive = state.savedReports.filter(r => !r.supersedes && r.sessionId !== 'batch2');
      const prevOdoEnd = prevActive.length > 0
        ? Math.max(...prevActive.map(r => r.odoRangeEnd ?? ODO_START))
        : ODO_START;
      return {
        ...initialState,
        trips: batch2Trips.map(t => ({ ...t })),
        savedReports: state.savedReports,
        sessionStartTime: Date.now(),
        sessionId: 'batch2',
        baseOdo: prevOdoEnd,
      };
    }
    case 'DELETE_ALL_TRIPS':
      return {
        ...initialState,
        trips: [],
        savedReports: state.savedReports,
        sessionStartTime: Date.now(),
        auditLog: [{ time: nowStr(), desc: 'All sort cards deleted by user', hasPhoto: false }, ...state.auditLog],
      };
    case 'DELETE_SESSION': {
      const remaining = state.savedReports.filter(r => r.sessionId !== action.sessionId);
      const isCurrentSession = state.sessionId === action.sessionId;
      return {
        ...initialState,
        trips: isCurrentSession ? [] : state.trips,
        savedReports: remaining,
        sessionId: isCurrentSession ? state.sessionId : state.sessionId,
        baseOdo: isCurrentSession ? initialState.baseOdo : state.baseOdo,
        sessionStartTime: Date.now(),
        freshSession: true,
        auditLog: [{ time: nowStr(), desc: `Session "${action.sessionId}" deleted — reports removed. Can be re-sorted anytime.`, hasPhoto: false }, ...state.auditLog],
      };
    }
    case 'COME_BACK_LATER':
      return {
        ...state,
        pendingFinalise: true,
        currentScreen: 'sort' as Screen,
        auditLog: [{ time: nowStr(), desc: 'User paused session — will return to finalise', hasPhoto: false }, ...state.auditLog],
      };
    case 'RESUME_SORTING':
      return {
        ...state,
        pendingFinalise: false,
        auditLog: [{ time: nowStr(), desc: 'User resumed sorting session', hasPhoto: false }, ...state.auditLog],
      };
    case 'ADD_TRIP': {
      const newTrips = [...state.trips];
      const tripTime = new Date(action.trip.year, action.trip.month, action.trip.day).getTime();
      let insertIdx = newTrips.length;
      for (let i = 0; i < newTrips.length; i++) {
        const tTime = new Date(newTrips[i].year, newTrips[i].month, newTrips[i].day).getTime();
        if (tTime > tripTime) {
          insertIdx = i;
          break;
        }
        if (tTime === tripTime && (action.trip.time || '') < (newTrips[i].time || '')) {
          insertIdx = i;
          break;
        }
      }
      newTrips.splice(insertIdx, 0, action.trip);
      const newCurrentIndex = state.currentIndex + 1;
      const sortedSlice = newTrips.slice(0, newCurrentIndex);
      const newBiz = sortedSlice.filter(t => t.type === 'business').length;
      const newPer = sortedSlice.filter(t => t.type === 'personal').length;
      const newDed = sortedSlice.filter(t => t.type === 'business').reduce((s, t) => s + t.km * RATE, 0);
      const newVerified = new Set(state.verifiedSet);
      for (let i = insertIdx; i < newTrips.length; i++) {
        if (newTrips[i].odoReading != null || newTrips[i].odoStartReading != null) {
          newTrips[i] = { ...newTrips[i], odoReading: null, odoStartReading: null, verified: false };
          newVerified.delete(i);
        }
      }
      return {
        ...state,
        trips: newTrips,
        currentIndex: newCurrentIndex,
        bizCount: newBiz,
        perCount: newPer,
        dedTotal: newDed,
        verifiedSet: newVerified,
        auditLog: [{ time: nowStr(), desc: `Trip added: ${action.trip.from} → ${action.trip.to} (${action.trip.km} km, ${action.trip.type})`, hasPhoto: false }, ...state.auditLog],
      };
    }
    case 'CONFIRM_GAP': {
      const newTrips = state.trips.map((t, i) =>
        i === action.tripIndex ? { ...t, gapConfirmed: true, km: action.km } : t
      );
      return {
        ...state,
        trips: newTrips,
        auditLog: [{ time: nowStr(), desc: `Gap confirmed: ${state.trips[action.tripIndex].from} → ${state.trips[action.tripIndex].to} (${action.km} km)`, hasPhoto: false }, ...state.auditLog],
      };
    }
    case 'DELETE_GAP': {
      const newTrips = state.trips.filter((_, i) => i !== action.tripIndex);
      return {
        ...state,
        trips: newTrips,
        auditLog: [{ time: nowStr(), desc: `Gap deleted: ${state.trips[action.tripIndex].from} → ${state.trips[action.tripIndex].to}`, hasPhoto: false }, ...state.auditLog],
      };
    }
    case 'PROMOTE_REPORT': {
      const idx = action.reportIndex;
      const targetSessionId = state.savedReports[idx].sessionId;
      const updated = state.savedReports.map((r, i) => ({
        ...r,
        supersedes: r.sessionId === targetSessionId ? i !== idx : r.supersedes,
      }));
      return {
        ...state,
        savedReports: updated,
        conflictResolved: true,
        auditLog: [{ time: nowStr(), desc: `Report Rev ${state.savedReports[idx].revision} promoted to active`, hasPhoto: false }, ...state.auditLog],
      };
    }
    default:
      return state;
  }
}

const AppContext = createContext<{
  state: AppState;
  dispatch: React.Dispatch<Action>;
} | null>(null);

export function AppProvider({ children }: { children: ReactNode }) {
  const [state, dispatch] = useReducer(reducer, initialState);
  return (
    <AppContext.Provider value={{ state, dispatch }}>
      {children}
    </AppContext.Provider>
  );
}

export function useApp() {
  const ctx = useContext(AppContext);
  if (!ctx) throw new Error('useApp must be used within AppProvider');
  return ctx;
}

export function useComputedStats() {
  const { state } = useApp();
  const currentBizKm = state.trips.slice(0, state.currentIndex).filter(x => x.type === 'business').reduce((a, x) => a + x.km, 0);
  const currentTotKm = state.trips.slice(0, state.currentIndex).reduce((a, x) => a + x.km, 0);
  const currentSessionHasReport = state.savedReports.some(r => r.sessionId === state.sessionId && !r.supersedes);
  const savedBizKm = state.savedReports
    .filter(r => !r.supersedes)
    .reduce((a, r) => a + (r.trips || []).filter(t => t.type === 'business').reduce((s, t) => s + t.km, 0), 0);
  const savedTotKm = state.savedReports
    .filter(r => !r.supersedes)
    .reduce((a, r) => a + (r.trips || []).reduce((s, t) => s + t.km, 0), 0);
  const bizKm = savedBizKm + (currentSessionHasReport ? 0 : currentBizKm);
  const totKm = savedTotKm + (currentSessionHasReport ? 0 : currentTotKm);
  const bizPct = totKm > 0 ? (bizKm / totKm * 100) : 0;
  const remaining = state.trips.length - state.currentIndex;
  const progress = state.trips.length > 0 ? (state.currentIndex / state.trips.length * 100) : 0;
  const sortedTripsArr = state.trips.filter(t => t.type !== null);
  const bizTripsArr = state.trips.filter(t => t.type === 'business');
  const auditResult = calcAuditScore({
    totalTrips: state.trips.length,
    sortedTrips: sortedTripsArr.length,
    verifiedCount: state.verifiedSet.size,
    photoCount: state.trips.filter(t => t.photo).length,
    bizPct,
    notesCount: bizTripsArr.filter(t => t.notes && t.notes.length > 0).length,
    bizCount: bizTripsArr.length,
  });
  const auditScore = auditResult.total;
  return { bizKm, totKm, bizPct, remaining, progress, auditScore };
}
