// ============================================================
// TRIP DATA
// Categories, helpers, and pure utility functions only.
// Hardcoded demo trips have been removed.
// Vehicle costs are passed as parameters (no localStorage).
// ============================================================

import type { VehicleSpecs, VehiclePurchase, ExpenseRecord, AppSettings } from './deduction-estimator';
import { getVehicleCostsDetailed } from './deduction-estimator';

export const ODO_START = 84280;

/** Get total vehicle costs for deduction calculation. Delegates to deduction-estimator. */
export function getVehicleCosts(params: {
  vehicleSpecs?: VehicleSpecs;
  vehiclePurchase?: VehiclePurchase;
  expenses?: ExpenseRecord[];
  settings?: AppSettings;
  fuelConsumptionOverride?: number;
}): number {
  return getVehicleCostsDetailed(params).total;
}

// ── Categories ───────────────────────────────────────────────

export const CATEGORIES = [
  { icon: 'Wrench', label: 'Tool Run' },
  { icon: 'Building2', label: 'Job Site' },
  { icon: 'Package', label: 'Pickup / Delivery' },
  { icon: 'ClipboardList', label: 'Quote / Inspect' },
  { icon: 'Handshake', label: 'Client Meeting' },
  { icon: 'Store', label: 'Supplier / Trade' },
  { icon: 'Zap', label: 'Emergency Call' },
  { icon: 'FileText', label: 'Admin / Office' },
  { icon: 'GraduationCap', label: 'Training' },
  { icon: 'Landmark', label: 'Council / Permit' },
] as const;

// ── Trip shape ───────────────────────────────────────────────

export interface Trip {
  id: number | string;
  // DB reference (present when loaded from Supabase)
  dbId?: string;
  vehicleId?: string;
  logbookPeriodId?: string;
  fy?: string;
  // Display fields
  date: string;
  day: number;
  month: number;
  year: number;
  time: string;
  duration: string;
  km: number;
  from: string;
  fromSub: string;
  to: string;
  toSub: string;
  type: 'business' | 'personal' | null;
  verified: boolean;
  photo: boolean;
  odoReading: number | null;
  odoStartReading: number | null;
  purposeLabel: string | null;
  purposeIndex: number | null;
  stops: string[];
  notes: string;
  autoGenerated?: boolean;
  gapConfirmed?: boolean;
}

// ── Deduction calculation ────────────────────────────────────

/**
 * Calculate the logbook deduction for a given period.
 * vehicleCosts is passed in from the data layer — never read from localStorage.
 */
export function calcLogbookDeduction(
  bizKm: number,
  totalKm: number,
  vehicleCosts: number
): number {
  if (totalKm <= 0 || vehicleCosts <= 0) return 0;
  const bizPct = bizKm / totalKm;
  return Math.round(bizPct * vehicleCosts * 100) / 100;
}

// ── Odometer helpers ─────────────────────────────────────────

export function getTripOdoStart(
  trips: Trip[],
  idx: number,
  baseOdo?: number | null
): number {
  if (trips[idx].odoStartReading != null) return trips[idx].odoStartReading!;
  for (let i = idx - 1; i >= 0; i--) {
    if (trips[i].odoReading != null) {
      let o = trips[i].odoReading!;
      for (let j = i + 1; j < idx; j++) o += trips[j].km;
      return o;
    }
  }
  const base = baseOdo ?? ODO_START;
  let o = base;
  for (let i = 0; i < idx; i++) o += trips[i].km;
  return o;
}

export function getTripOdoEnd(
  trips: Trip[],
  idx: number,
  baseOdo?: number | null
): number {
  if (trips[idx].odoReading != null) return trips[idx].odoReading!;
  return getTripOdoStart(trips, idx, baseOdo) + trips[idx].km;
}

// ── Connector trip generation ────────────────────────────────

function normLoc(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9]/g, '').replace(/^(the|at)/, '');
}

function locsMatch(a: string, b: string): boolean {
  const na = normLoc(a);
  const nb = normLoc(b);
  if (na === nb) return true;
  if (na.includes(nb) || nb.includes(na)) return true;
  return false;
}

let connectorIdCounter = 9000;

export function generateConnectorTrips(trips: Trip[]): Trip[] {
  const sorted = [...trips].filter(t => t.type !== null);
  sorted.sort((a, b) => {
    const da = new Date(a.year, a.month, a.day).getTime();
    const db = new Date(b.year, b.month, b.day).getTime();
    if (da !== db) return da - db;
    return (a.time || '').localeCompare(b.time || '');
  });

  const connectors: Trip[] = [];
  for (let i = 0; i < sorted.length - 1; i++) {
    const curr = sorted[i];
    const next = sorted[i + 1];
    if (!locsMatch(curr.to, next.from)) {
      const sameDay =
        curr.day === next.day &&
        curr.month === next.month &&
        curr.year === next.year;
      connectors.push({
        id: connectorIdCounter++,
        date: sameDay ? curr.date : next.date,
        day: sameDay ? curr.day : next.day,
        month: sameDay ? curr.month : next.month,
        year: sameDay ? curr.year : next.year,
        time: '',
        duration: '',
        km: 0,
        from: curr.to,
        fromSub: curr.toSub,
        to: next.from,
        toSub: next.fromSub,
        type: 'personal',
        verified: false,
        photo: false,
        odoReading: null,
        odoStartReading: null,
        purposeLabel: null,
        purposeIndex: null,
        stops: [],
        notes: '',
        autoGenerated: true,
      });
    }
  }
  return connectors;
}
