export const ODO_START = 84280;

export function getVehicleCosts(): number {
  let manual = 0;
  try {
    const exps = JSON.parse(localStorage.getItem('wc_expenses') || '[]');
    manual = exps.filter((e: any) => !e.estimated).reduce((s: number, e: any) => s + (e.amount || 0), 0);
  } catch {}

  let fuelConsumption = 10;
  try {
    const fc = parseFloat(localStorage.getItem('wc_fuel_consumption') || '');
    if (fc > 0) fuelConsumption = fc;
  } catch {}

  let avgFuelPrice = 1.95;
  try {
    const settings = JSON.parse(localStorage.getItem('wc_settings') || '{}');
    const p = parseFloat(settings.avgFuelPrice);
    if (p > 0) avgFuelPrice = p;
  } catch {}

  const totalAnnualKm = 15000;
  const fuelEstimate = Math.round(totalAnnualKm / 100 * fuelConsumption * avgFuelPrice * 100) / 100;

  let depAmount = 0;
  try {
    const purchase = JSON.parse(localStorage.getItem('wc_vehicle_purchase') || '{}');
    const price = Math.min(parseFloat(purchase.purchasePrice) || 0, 68108);
    if (price > 0) {
      const purchDate = purchase.purchaseDate ? new Date(purchase.purchaseDate) : null;
      const now = new Date();
      const fyStart = new Date(now.getMonth() >= 6 ? now.getFullYear() : now.getFullYear() - 1, 6, 1);
      const fyEnd = new Date(fyStart.getFullYear() + 1, 5, 30);
      const daysInFY = Math.round((fyEnd.getTime() - fyStart.getTime()) / 86400000);
      let daysOwned = daysInFY;
      if (purchDate && purchDate > fyStart) {
        daysOwned = Math.max(0, Math.min(Math.round((fyEnd.getTime() - purchDate.getTime()) / 86400000), daysInFY));
      }
      depAmount = Math.round(price * 0.25 * (daysOwned / daysInFY) * 100) / 100;
    }
  } catch {}

  return manual + fuelEstimate + depAmount;
}

export function calcLogbookDeduction(bizKm: number, totalKm: number): number {
  if (totalKm <= 0) return 0;
  const bizPct = bizKm / totalKm;
  const vehicleCosts = getVehicleCosts();
  return Math.round(bizPct * vehicleCosts * 100) / 100;
}

export const CATEGORIES = [
  { icon: 'Wrench', label: 'Tool Run' },
  { icon: 'Building2', label: 'Job Site' },
  { icon: 'Package', label: 'Pickup / Delivery' },
  { icon: 'ClipboardList', label: 'Quote / Inspect' },
  { icon: 'Handshake', label: 'Client Meeting' },
  { icon: 'Store', label: 'Supplier / Trade' },
  { icon: 'Zap', label: 'Emergency Call' },
  { icon: 'FileText', label: 'Admin / Office' },
  { icon: 'GraduationCap', label: 'Training' },
  { icon: 'Landmark', label: 'Council / Permit' },
] as const;

export interface Trip {
  id: number;
  date: string;
  day: number;
  month: number;
  year: number;
  time: string;
  duration: string;
  km: number;
  from: string;
  fromSub: string;
  to: string;
  toSub: string;
  type: 'business' | 'personal' | null;
  verified: boolean;
  photo: boolean;
  odoReading: number | null;
  odoStartReading: number | null;
  purposeLabel: string | null;
  purposeIndex: number | null;
  stops: string[];
  notes: string;
  autoGenerated?: boolean;
  gapConfirmed?: boolean;
}

function normLoc(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9]/g, '').replace(/^(the|at)/, '');
}

function locsMatch(a: string, b: string): boolean {
  const na = normLoc(a);
  const nb = normLoc(b);
  if (na === nb) return true;
  if (na.includes(nb) || nb.includes(na)) return true;
  return false;
}

let connectorIdCounter = 9000;

export function generateConnectorTrips(trips: Trip[]): Trip[] {
  const sorted = [...trips].filter(t => t.type !== null);
  sorted.sort((a, b) => {
    const da = new Date(a.year, a.month, a.day).getTime();
    const db = new Date(b.year, b.month, b.day).getTime();
    if (da !== db) return da - db;
    return (a.time || '').localeCompare(b.time || '');
  });

  const connectors: Trip[] = [];
  for (let i = 0; i < sorted.length - 1; i++) {
    const curr = sorted[i];
    const next = sorted[i + 1];
    const currTo = curr.to;
    const nextFrom = next.from;
    if (!locsMatch(currTo, nextFrom)) {
      const sameDay = curr.day === next.day && curr.month === next.month && curr.year === next.year;
      connectors.push({
        id: connectorIdCounter++,
        date: sameDay ? curr.date : next.date,
        day: sameDay ? curr.day : next.day,
        month: sameDay ? curr.month : next.month,
        year: sameDay ? curr.year : next.year,
        time: '',
        duration: '',
        km: 0,
        from: currTo,
        fromSub: curr.toSub,
        to: nextFrom,
        toSub: next.fromSub,
        type: 'personal',
        verified: false,
        photo: false,
        odoReading: null,
        odoStartReading: null,
        purposeLabel: null,
        purposeIndex: null,
        stops: [],
        notes: '',
        autoGenerated: true,
      });
    }
  }
  return connectors;
}

export const initialTrips: Trip[] = [
  { id: 0, date: 'Thu, 27 Feb', day: 27, month: 1, year: 2026, time: '9:02\u20139:50 AM', duration: '48 min', km: 16.2, from: '15 Smith St', fromSub: 'Fitzroy VIC 3065', to: 'Bunnings Warehouse', toSub: '123 King Rd, Sunshine VIC', type: null, verified: false, photo: false, odoReading: null, odoStartReading: null, purposeLabel: null, purposeIndex: null, stops: [], notes: '' },
  { id: 1, date: 'Thu, 27 Feb', day: 27, month: 1, year: 2026, time: '11:15\u201312:02 PM', duration: '47 min', km: 14.8, from: 'Bunnings Warehouse', fromSub: 'Sunshine VIC 3020', to: '44 Acacia Ave', toSub: 'Williamstown VIC 3016', type: null, verified: false, photo: false, odoReading: null, odoStartReading: null, purposeLabel: null, purposeIndex: null, stops: [], notes: '' },
  { id: 2, date: 'Wed, 26 Feb', day: 26, month: 1, year: 2026, time: '7:45\u20138:30 AM', duration: '45 min', km: 12.4, from: 'Home', fromSub: 'Spotswood VIC 3015', to: 'Job Site \u2014 Altona', toSub: '15 Industry Rd, Altona VIC', type: null, verified: false, photo: false, odoReading: null, odoStartReading: null, purposeLabel: null, purposeIndex: null, stops: [], notes: '' },
  { id: 3, date: 'Wed, 26 Feb', day: 26, month: 1, year: 2026, time: '3:30\u20134:10 PM', duration: '40 min', km: 18.6, from: 'Job Site \u2014 Altona', fromSub: 'Altona VIC 3018', to: 'Reece Plumbing', toSub: '45 Parker St, Footscray VIC', type: null, verified: false, photo: false, odoReading: null, odoStartReading: null, purposeLabel: null, purposeIndex: null, stops: [], notes: '' },
  { id: 4, date: 'Tue, 25 Feb', day: 25, month: 1, year: 2026, time: '8:10\u20139:05 AM', duration: '55 min', km: 22.1, from: 'Home', fromSub: 'Spotswood VIC 3015', to: 'Newport Client', toSub: '77 Bay Rd, Newport VIC', type: null, verified: false, photo: false, odoReading: null, odoStartReading: null, purposeLabel: null, purposeIndex: null, stops: [], notes: '' },
  { id: 5, date: 'Tue, 25 Feb', day: 25, month: 1, year: 2026, time: '2:00\u20132:35 PM', duration: '35 min', km: 9.8, from: 'Newport Client', fromSub: 'Newport VIC 3015', to: 'Trade Depot', toSub: '88 Williamstown Rd, VIC', type: null, verified: false, photo: false, odoReading: null, odoStartReading: null, purposeLabel: null, purposeIndex: null, stops: [], notes: '' },
  { id: 6, date: 'Mon, 24 Feb', day: 24, month: 1, year: 2026, time: '7:30\u20138:22 AM', duration: '52 min', km: 19.4, from: 'Home', fromSub: 'Spotswood VIC 3015', to: 'Commercial Job \u2014 CBD', toSub: '123 Collins St, Melbourne VIC', type: null, verified: false, photo: false, odoReading: null, odoStartReading: null, purposeLabel: null, purposeIndex: null, stops: [], notes: '' },
  { id: 7, date: 'Mon, 24 Feb', day: 24, month: 1, year: 2026, time: '4:45\u20135:30 PM', duration: '45 min', km: 21.2, from: 'Commercial Job \u2014 CBD', fromSub: 'Melbourne VIC 3000', to: 'Home', toSub: 'Spotswood VIC 3015', type: null, verified: false, photo: false, odoReading: null, odoStartReading: null, purposeLabel: null, purposeIndex: null, stops: [], notes: '' },
];

export const batch2Trips: Trip[] = [
  { id: 100, date: 'Fri, 28 Feb', day: 28, month: 1, year: 2026, time: '6:45\u20137:38 AM', duration: '53 min', km: 24.3, from: 'Home', fromSub: 'Spotswood VIC 3015', to: 'Residential Reno \u2014 Kew', toSub: '9 Cotham Rd, Kew VIC 3101', type: null, verified: false, photo: false, odoReading: null, odoStartReading: null, purposeLabel: null, purposeIndex: null, stops: [], notes: '' },
  { id: 101, date: 'Fri, 28 Feb', day: 28, month: 1, year: 2026, time: '12:10\u201312:45 PM', duration: '35 min', km: 8.7, from: 'Residential Reno \u2014 Kew', fromSub: 'Kew VIC 3101', to: 'Highpoint Bunnings', toSub: 'Aquatic Dr, Maribyrnong VIC', type: null, verified: false, photo: false, odoReading: null, odoStartReading: null, purposeLabel: null, purposeIndex: null, stops: [], notes: '' },
  { id: 102, date: 'Fri, 28 Feb', day: 28, month: 1, year: 2026, time: '1:20\u20131:55 PM', duration: '35 min', km: 11.2, from: 'Highpoint Bunnings', fromSub: 'Maribyrnong VIC 3032', to: 'Residential Reno \u2014 Kew', toSub: '9 Cotham Rd, Kew VIC 3101', type: null, verified: false, photo: false, odoReading: null, odoStartReading: null, purposeLabel: null, purposeIndex: null, stops: [], notes: '' },
  { id: 103, date: 'Fri, 28 Feb', day: 28, month: 1, year: 2026, time: '5:15\u20136:02 PM', duration: '47 min', km: 23.8, from: 'Residential Reno \u2014 Kew', fromSub: 'Kew VIC 3101', to: 'Home', toSub: 'Spotswood VIC 3015', type: null, verified: false, photo: false, odoReading: null, odoStartReading: null, purposeLabel: null, purposeIndex: null, stops: [], notes: '' },
  { id: 104, date: 'Sat, 1 Mar', day: 1, month: 2, year: 2026, time: '8:30\u20139:10 AM', duration: '40 min', km: 15.6, from: 'Home', fromSub: 'Spotswood VIC 3015', to: 'Coles Yarraville', toSub: '12 Anderson St, Yarraville VIC', type: null, verified: false, photo: false, odoReading: null, odoStartReading: null, purposeLabel: null, purposeIndex: null, stops: [], notes: '' },
  { id: 105, date: 'Sat, 1 Mar', day: 1, month: 2, year: 2026, time: '10:45\u201311:30 AM', duration: '45 min', km: 17.9, from: 'Coles Yarraville', fromSub: 'Yarraville VIC 3013', to: 'Emergency \u2014 Tenant Call', toSub: '33 Moore St, Footscray VIC', type: null, verified: false, photo: false, odoReading: null, odoStartReading: null, purposeLabel: null, purposeIndex: null, stops: [], notes: '' },
  { id: 106, date: 'Sun, 2 Mar', day: 2, month: 2, year: 2026, time: '9:00\u20139:35 AM', duration: '35 min', km: 13.1, from: 'Home', fromSub: 'Spotswood VIC 3015', to: 'Gym \u2014 Essendon Fields', toSub: 'English St, Essendon Fields VIC', type: null, verified: false, photo: false, odoReading: null, odoStartReading: null, purposeLabel: null, purposeIndex: null, stops: [], notes: '' },
  { id: 107, date: 'Sun, 2 Mar', day: 2, month: 2, year: 2026, time: '11:00\u201311:42 AM', duration: '42 min', km: 14.5, from: 'Gym \u2014 Essendon Fields', fromSub: 'Essendon Fields VIC 3041', to: 'Home', toSub: 'Spotswood VIC 3015', type: null, verified: false, photo: false, odoReading: null, odoStartReading: null, purposeLabel: null, purposeIndex: null, stops: [], notes: '' },
];

export function getTripOdoStart(trips: Trip[], idx: number, baseOdo?: number | null): number {
  if (trips[idx].odoStartReading != null) return trips[idx].odoStartReading!;
  for (let i = idx - 1; i >= 0; i--) {
    if (trips[i].odoReading != null) {
      let o = trips[i].odoReading!;
      for (let j = i + 1; j < idx; j++) o += trips[j].km;
      return o;
    }
  }
  const base = baseOdo ?? ODO_START;
  let o = base;
  for (let i = 0; i < idx; i++) o += trips[i].km;
  return o;
}

export function getTripOdoEnd(trips: Trip[], idx: number, baseOdo?: number | null): number {
  if (trips[idx].odoReading != null) return trips[idx].odoReading!;
  return getTripOdoStart(trips, idx, baseOdo) + trips[idx].km;
}
