import { useState, useMemo, useRef } from 'react';
import { useApp } from '@/lib/app-context';
import { BottomNav } from './bottom-nav';
import {
  ArrowLeft, Plus, Receipt, Trash2, Check, ChevronDown, ChevronUp,
  Camera, Image, Pencil, X, Download, AlertTriangle, Sparkles, FileText
} from 'lucide-react';

const ATO_CATEGORIES = [
  'Fuel / Electricity',
  'Oil',
  'Repairs & Maintenance',
  'Registration',
  'Insurance',
  'Lease Payments',
  'Loan Interest',
  'Depreciation',
] as const;

type ATOCategory = typeof ATO_CATEGORIES[number];

interface Expense {
  id: number;
  date: string;
  category: ATOCategory;
  amount: number;
  vendor: string;
  receiptUri: string;
  estimated: boolean;
}

const FUEL_CONSUMPTION_FALLBACK: Record<string, number> = {
  'ute-4x4': 12.5, 'ute-4x2': 10.5, 'suv-medium': 9.8,
  'suv-small': 8.2, 'sedan': 7.5, 'van': 11.0, default: 10.0,
};

function getVehicleFuelConsumption(): number {
  const fromSpecs = parseFloat(localStorage.getItem('wc_fuel_consumption') || '');
  if (fromSpecs > 0) return fromSpecs;
  const vType = localStorage.getItem('wc_vehicle_type') || 'default';
  return FUEL_CONSUMPTION_FALLBACK[vType] || FUEL_CONSUMPTION_FALLBACK.default;
}

function getAvgFuelPrice(): number {
  try {
    const settings = JSON.parse(localStorage.getItem('wc_settings') || '{}');
    const price = parseFloat(settings.avgFuelPrice);
    if (price > 0) return price;
  } catch {}
  return 1.95;
}

const DV_RATE = 0.25;
const ATO_CAR_LIMIT = 68108;

function getExpenses(): Expense[] {
  try { return JSON.parse(localStorage.getItem('wc_expenses') || '[]'); }
  catch { return []; }
}
function saveExpenses(exps: Expense[]) {
  localStorage.setItem('wc_expenses', JSON.stringify(exps));
}

let _nextId = Date.now();

export function ExpensesScreen() {
  const { state, dispatch } = useApp();
  const [tab, setTab] = useState<'entries' | 'report'>('entries');
  const [expenses, setExpenses] = useState<Expense[]>(getExpenses);
  const [adding, setAdding] = useState(false);
  const [editing, setEditing] = useState<Expense | null>(null);
  const [expanded, setExpanded] = useState<number | null>(null);
  const fileRef = useRef<HTMLInputElement>(null);

  const [fCat, setFCat] = useState<ATOCategory>(ATO_CATEGORIES[2]);
  const [fAmount, setFAmount] = useState('');
  const [fDate, setFDate] = useState(() => new Date().toISOString().slice(0, 10));
  const [fVendor, setFVendor] = useState('');
  const [fReceipt, setFReceipt] = useState('');
  const [aiExtracting, setAiExtracting] = useState(false);

  const bizKm = useMemo(
    () => state.trips.filter(t => t.type === 'business').reduce((s, t) => s + t.km, 0),
    [state.trips]
  );
  const totalKm = useMemo(
    () => state.trips.filter(t => t.type !== null && !t.autoGenerated).reduce((s, t) => s + t.km, 0),
    [state.trips]
  );
  const bizPct = totalKm > 0 ? Math.round(bizKm / totalKm * 100) : 0;

  const litresPer100 = getVehicleFuelConsumption();
  const avgFuelPrice = getAvgFuelPrice();
  const fuelEstimate = Math.round(bizKm / 100 * litresPer100 * avgFuelPrice * 100) / 100;

  const depAmount = useMemo(() => {
    try {
      const purchase = JSON.parse(localStorage.getItem('wc_vehicle_purchase') || '{}');
      const price = Math.min(parseFloat(purchase.purchasePrice) || 0, ATO_CAR_LIMIT);
      if (price <= 0) return 0;
      const purchDate = purchase.purchaseDate ? new Date(purchase.purchaseDate) : null;
      const now = new Date();
      const fyStart = new Date(now.getMonth() >= 6 ? now.getFullYear() : now.getFullYear() - 1, 6, 1);
      const fyEnd = new Date(fyStart.getFullYear() + 1, 5, 30);
      const daysInFY = Math.round((fyEnd.getTime() - fyStart.getTime()) / 86400000);
      let daysOwned = daysInFY;
      if (purchDate && purchDate > fyStart) {
        daysOwned = Math.max(0, Math.min(Math.round((fyEnd.getTime() - purchDate.getTime()) / 86400000), daysInFY));
      }
      return Math.round(price * DV_RATE * (daysOwned / daysInFY) * 100) / 100;
    } catch { return 0; }
  }, []);

  const userExpenses = expenses.filter(e => !e.estimated);

  const reportData = useMemo(() => {
    const map: Record<string, number> = {};
    ATO_CATEGORIES.forEach(c => { map[c] = 0; });
    map['Fuel / Electricity'] = fuelEstimate;
    map['Depreciation'] = depAmount;
    expenses.filter(e => !e.estimated).forEach(e => { map[e.category] = (map[e.category] || 0) + e.amount; });
    const totalVehicle = Object.values(map).reduce((s, v) => s + v, 0);
    const deductible = Math.round(totalVehicle * bizPct) / 100;
    return { map, totalVehicle, deductible };
  }, [expenses, fuelEstimate, depAmount, bizPct]);

  const resetForm = () => {
    setFCat(ATO_CATEGORIES[2]);
    setFAmount('');
    setFDate(new Date().toISOString().slice(0, 10));
    setFVendor('');
    setFReceipt('');
    setEditing(null);
    setAdding(false);
  };

  const handleSave = () => {
    const amt = parseFloat(fAmount) || 0;
    if (amt <= 0) return;
    if (editing) {
      const updated = expenses.map(e =>
        e.id === editing.id ? { ...e, category: fCat, amount: amt, date: fDate, vendor: fVendor.trim(), receiptUri: fReceipt } : e
      );
      setExpenses(updated);
      saveExpenses(updated);
    } else {
      const exp: Expense = { id: _nextId++, date: fDate, category: fCat, amount: amt, vendor: fVendor.trim(), receiptUri: fReceipt, estimated: false };
      const updated = [exp, ...expenses];
      setExpenses(updated);
      saveExpenses(updated);
    }
    resetForm();
  };

  const handleDelete = (id: number) => {
    const updated = expenses.filter(e => e.id !== id);
    setExpenses(updated);
    saveExpenses(updated);
    setExpanded(null);
  };

  const startEdit = (exp: Expense) => {
    setFCat(exp.category);
    setFAmount(String(exp.amount));
    setFDate(exp.date);
    setFVendor(exp.vendor);
    setFReceipt(exp.receiptUri);
    setEditing(exp);
    setAdding(true);
  };

  const handleReceiptUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    const reader = new FileReader();
    reader.onload = () => {
      const dataUri = reader.result as string;
      setFReceipt(dataUri);
      setAiExtracting(true);
      setTimeout(() => {
        setAiExtracting(false);
      }, 1500);
    };
    reader.readAsDataURL(file);
  };

  const handleExportCSV = () => {
    const headers = 'Category,Amount,Business Use %,Deductible,Note\n';
    const rows = ATO_CATEGORIES.map(cat => {
      const amt = cat === 'Fuel / Electricity' ? fuelEstimate : cat === 'Depreciation' ? depAmount : (reportData.map[cat] || 0);
      const ded = Math.round(amt * bizPct) / 100;
      const note = cat === 'Fuel / Electricity' ? 'Estimated' : cat === 'Depreciation' ? 'Auto-calculated' : '';
      return `"${cat}",${amt.toFixed(2)},${bizPct}%,${ded.toFixed(2)},${note}`;
    }).join('\n');
    const total = `\n"TOTAL",${reportData.totalVehicle.toFixed(2)},${bizPct}%,${reportData.deductible.toFixed(2)},`;
    const blob = new Blob([headers + rows + total], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `expenses-${new Date().toISOString().slice(0, 10)}.csv`;
    a.click();
    URL.revokeObjectURL(url);
  };

  if (adding) {
    return (
      <div className="flex flex-col h-full" data-testid="expense-add-screen">
        <div className="flex items-center gap-[10px] px-4 pt-2 pb-[5px] flex-shrink-0">
          <button
            className="w-[34px] h-[34px] rounded-lg flex items-center justify-center"
            style={{ background: 'rgba(255,255,255,.06)', border: '1px solid var(--wc-border)' }}
            onClick={resetForm}
            data-testid="button-cancel-expense"
          >
            <X className="w-[16px] h-[16px]" style={{ color: 'var(--wc-t2)' }} />
          </button>
          <span className="font-heading font-extrabold text-[22px] uppercase tracking-[.04em] text-white">
            {editing ? 'Edit Expense' : 'Add Expense'}
          </span>
        </div>

        <div className="flex-1 px-[14px] pb-[20px] overflow-y-auto scrollbar-thin" style={{ overscrollBehavior: 'contain', WebkitOverflowScrolling: 'touch' } as any}>
          <div className="rounded-[14px] p-[16px]" style={{ background: 'var(--wc-card)', border: '1px solid var(--wc-border)' }}>

            <label className="font-data text-[9px] uppercase tracking-[.1em] block mb-[4px]" style={{ color: 'var(--wc-t3)' }}>Receipt Photo</label>
            <input type="file" accept="image/*" capture="environment" ref={fileRef} className="hidden" onChange={handleReceiptUpload} data-testid="expense-receipt-input" />
            {fReceipt ? (
              <div className="relative mb-[12px]">
                <img src={fReceipt} className="w-full h-[140px] object-cover rounded-[10px]" alt="Receipt" />
                <button
                  className="absolute top-[6px] right-[6px] w-[28px] h-[28px] rounded-full flex items-center justify-center"
                  style={{ background: 'rgba(0,0,0,.7)' }}
                  onClick={() => setFReceipt('')}
                  data-testid="expense-remove-receipt"
                >
                  <X className="w-[14px] h-[14px] text-white" />
                </button>
                {aiExtracting && (
                  <div className="absolute inset-0 rounded-[10px] flex items-center justify-center" style={{ background: 'rgba(0,0,0,.6)' }}>
                    <div className="flex items-center gap-[8px]">
                      <Sparkles className="w-[18px] h-[18px] animate-pulse" style={{ color: 'var(--wc-y)' }} />
                      <span className="font-heading font-bold text-[14px] uppercase" style={{ color: 'var(--wc-y)' }}>Reading receipt...</span>
                    </div>
                  </div>
                )}
              </div>
            ) : (
              <div className="flex gap-[8px] mb-[12px]">
                <button
                  className="flex-1 rounded-[10px] p-[14px] flex flex-col items-center gap-[6px] cursor-pointer"
                  style={{ background: 'rgba(255,255,255,.04)', border: '1.5px dashed rgba(255,255,255,.3)' }}
                  onClick={() => fileRef.current?.click()}
                  data-testid="expense-upload-receipt"
                >
                  <Camera className="w-[24px] h-[24px]" style={{ color: 'var(--wc-y)' }} />
                  <span className="font-heading font-bold text-[12px] uppercase" style={{ color: 'var(--wc-y)' }}>Take Photo</span>
                </button>
                <button
                  className="flex-1 rounded-[10px] p-[14px] flex flex-col items-center gap-[6px] cursor-pointer"
                  style={{ background: 'rgba(255,255,255,.03)', border: '1.5px dashed var(--wc-border)' }}
                  onClick={() => { if (fileRef.current) { fileRef.current.removeAttribute('capture'); fileRef.current.click(); fileRef.current.setAttribute('capture', 'environment'); } }}
                  data-testid="expense-gallery-receipt"
                >
                  <Image className="w-[24px] h-[24px]" style={{ color: 'var(--wc-t2)' }} />
                  <span className="font-heading font-bold text-[12px] uppercase" style={{ color: 'var(--wc-t2)' }}>Gallery</span>
                </button>
              </div>
            )}

            <label className="font-data text-[9px] uppercase tracking-[.1em] block mb-[4px]" style={{ color: 'var(--wc-t3)' }}>Category</label>
            <div className="flex flex-wrap gap-[5px] mb-[12px]">
              {ATO_CATEGORIES.filter(c => c !== 'Fuel / Electricity' && c !== 'Depreciation').map(cat => (
                <button
                  key={cat}
                  className="rounded-[8px] px-[10px] py-[8px] font-heading font-bold text-[12px] uppercase tracking-[.03em] cursor-pointer transition-all"
                  style={{
                    background: fCat === cat ? 'rgba(255,255,255,.15)' : 'rgba(255,255,255,.04)',
                    border: fCat === cat ? '1px solid rgba(255,255,255,.4)' : '1px solid var(--wc-border)',
                    color: fCat === cat ? 'var(--wc-y)' : 'var(--wc-t2)',
                  }}
                  onClick={() => setFCat(cat)}
                  data-testid={`expense-cat-${cat.replace(/[^a-zA-Z]/g, '').toLowerCase()}`}
                >
                  {cat}
                </button>
              ))}
            </div>

            <div className="flex gap-[8px] mb-[12px]">
              <div className="flex-1">
                <label className="font-data text-[9px] uppercase tracking-[.1em] block mb-[3px]" style={{ color: 'var(--wc-t3)' }}>Amount ($)</label>
                <input
                  type="number"
                  step="0.01"
                  inputMode="decimal"
                  className="w-full rounded-[8px] p-[12px] text-[16px] text-white outline-none font-data"
                  style={{ background: 'rgba(255,255,255,.05)', border: '1px solid var(--wc-border)' }}
                  value={fAmount}
                  onChange={e => setFAmount(e.target.value)}
                  placeholder="0.00"
                  data-testid="expense-amount"
                />
              </div>
              <div className="flex-1">
                <label className="font-data text-[9px] uppercase tracking-[.1em] block mb-[3px]" style={{ color: 'var(--wc-t3)' }}>Date</label>
                <input
                  type="date"
                  className="w-full rounded-[8px] p-[12px] text-[16px] text-white outline-none"
                  style={{ background: 'rgba(255,255,255,.05)', border: '1px solid var(--wc-border)' }}
                  value={fDate}
                  onChange={e => setFDate(e.target.value)}
                  data-testid="expense-date"
                />
              </div>
            </div>

            <label className="font-data text-[9px] uppercase tracking-[.1em] block mb-[3px]" style={{ color: 'var(--wc-t3)' }}>Vendor (optional)</label>
            <input
              className="w-full rounded-[8px] p-[12px] text-[16px] text-white outline-none mb-[14px]"
              style={{ background: 'rgba(255,255,255,.05)', border: '1px solid var(--wc-border)' }}
              value={fVendor}
              onChange={e => setFVendor(e.target.value)}
              placeholder="e.g. Repco, NRMA, Shell"
              data-testid="expense-vendor"
            />

            <div className="rounded-[10px] p-[12px] mb-[14px] flex items-start gap-[10px]" style={{ background: 'rgba(255,255,255,.04)', border: '1px solid rgba(255,255,255,.15)' }}>
              <Check className="w-[18px] h-[18px] flex-shrink-0 mt-[2px]" style={{ color: 'var(--wc-y)' }} />
              <div>
                <div className="font-heading font-bold text-[12px] uppercase" style={{ color: 'var(--wc-y)' }}>Verify Before Save</div>
                <div className="text-[11px] mt-[2px]" style={{ color: 'var(--wc-t3)' }}>
                  {fCat} &middot; ${parseFloat(fAmount || '0').toFixed(2)} &middot; {fDate}
                  {fVendor ? ` · ${fVendor}` : ''}{fReceipt ? ' · Receipt attached' : ''}
                </div>
              </div>
            </div>
          </div>
        </div>

        <div className="px-[14px] py-[8px] flex gap-[8px] flex-shrink-0">
          <button
            className="flex-1 py-[14px] rounded-[12px] font-heading font-bold text-[15px] uppercase tracking-[.04em] cursor-pointer"
            style={{ background: 'rgba(255,255,255,.04)', border: '1px solid var(--wc-border)', color: 'var(--wc-t3)' }}
            onClick={resetForm}
            data-testid="expense-cancel-btn"
          >
            Cancel
          </button>
          <button
            className="flex-[2] py-[14px] rounded-[12px] font-heading font-bold text-[15px] uppercase tracking-[.04em] text-black cursor-pointer transition-all active:scale-[.98]"
            style={{
              background: parseFloat(fAmount) > 0 ? 'var(--wc-y)' : 'rgba(255,255,255,.3)',
              opacity: parseFloat(fAmount) > 0 ? 1 : 0.5,
              boxShadow: parseFloat(fAmount) > 0 ? '0 4px 20px rgba(255,255,255,.25)' : 'none',
            }}
            onClick={handleSave}
            data-testid="expense-save-btn"
          >
            {editing ? 'Update Expense' : 'Save Expense'}
          </button>
        </div>
        <BottomNav />
      </div>
    );
  }

  return (
    <div className="flex flex-col h-full" data-testid="expenses-screen">
      <div className="flex items-center gap-[10px] px-4 pt-2 pb-[5px] flex-shrink-0">
        <button
          className="w-[34px] h-[34px] rounded-lg flex items-center justify-center"
          style={{ background: 'rgba(255,255,255,.06)', border: '1px solid var(--wc-border)' }}
          onClick={() => dispatch({ type: 'GO_SCREEN', screen: 'dashboard' })}
          data-testid="button-back-expenses"
        >
          <ArrowLeft className="w-[16px] h-[16px]" style={{ color: 'var(--wc-t2)' }} />
        </button>
        <span className="font-heading font-extrabold text-[22px] uppercase tracking-[.04em] text-white">Expenses</span>
      </div>

      <div className="flex mx-[14px] mb-[8px] rounded-[10px] overflow-hidden flex-shrink-0" style={{ background: 'var(--wc-card)', border: '1px solid var(--wc-border)' }}>
        {(['entries', 'report'] as const).map(t => (
          <button
            key={t}
            className="flex-1 py-[10px] font-heading font-bold text-[14px] uppercase tracking-[.05em] cursor-pointer transition-all"
            style={{
              background: tab === t ? 'rgba(255,255,255,.12)' : 'transparent',
              color: tab === t ? 'var(--wc-y)' : 'var(--wc-t3)',
              borderBottom: tab === t ? '2px solid var(--wc-y)' : '2px solid transparent',
            }}
            onClick={() => setTab(t)}
            data-testid={`tab-${t}`}
          >
            {t === 'entries' ? 'Entries' : 'Report'}
          </button>
        ))}
      </div>

      {tab === 'entries' && (
        <div className="flex-1 px-[14px] pb-[20px] flex flex-col gap-[6px] overflow-y-auto scrollbar-thin" style={{ overscrollBehavior: 'contain', WebkitOverflowScrolling: 'touch' } as any}>
          {userExpenses.length === 0 && (
            <div className="flex flex-col items-center justify-center py-[40px]">
              <Receipt className="w-[40px] h-[40px] mb-[12px]" style={{ color: 'var(--wc-t3)' }} />
              <div className="font-heading font-bold text-[16px] uppercase text-center" style={{ color: 'var(--wc-t3)' }}>No expenses yet</div>
              <div className="text-[12px] text-center mt-[4px] px-[20px]" style={{ color: 'var(--wc-t3)' }}>
                Tap the button below to add your first vehicle expense. Fuel and depreciation are estimated automatically.
              </div>
            </div>
          )}

          {userExpenses.map(exp => {
            const isOpen = expanded === exp.id;
            return (
              <div
                key={exp.id}
                className="rounded-[12px] transition-all"
                style={{ background: 'var(--wc-card)', border: '1px solid var(--wc-border)' }}
                data-testid={`expense-item-${exp.id}`}
              >
                <div className="flex items-center gap-[10px] p-[12px_14px] cursor-pointer" onClick={() => setExpanded(isOpen ? null : exp.id)}>
                  {exp.receiptUri ? (
                    <img src={exp.receiptUri} className="w-[38px] h-[38px] rounded-[8px] object-cover flex-shrink-0" alt="" />
                  ) : (
                    <div className="w-[38px] h-[38px] rounded-[8px] flex items-center justify-center flex-shrink-0" style={{ background: 'rgba(255,255,255,.06)', border: '1px solid rgba(255,255,255,.15)' }}>
                      <Receipt className="w-[18px] h-[18px]" style={{ color: 'var(--wc-y)' }} />
                    </div>
                  )}
                  <div className="flex-1 min-w-0">
                    <div className="font-semibold text-[14px] text-white truncate">{exp.category}</div>
                    <div className="text-[11px] mt-[1px] truncate" style={{ color: 'var(--wc-t3)' }}>
                      {exp.date}{exp.vendor ? ` · ${exp.vendor}` : ''}
                    </div>
                  </div>
                  <div className="font-heading font-bold text-[15px] flex-shrink-0" style={{ color: 'var(--wc-y)' }}>${exp.amount.toFixed(2)}</div>
                  {isOpen ? <ChevronUp className="w-[14px] h-[14px] flex-shrink-0" style={{ color: 'var(--wc-t3)' }} /> : <ChevronDown className="w-[14px] h-[14px] flex-shrink-0" style={{ color: 'var(--wc-t3)' }} />}
                </div>
                {isOpen && (
                  <div className="px-[14px] pb-[12px] flex gap-[8px] border-t" style={{ borderColor: 'var(--wc-border)' }}>
                    <button
                      className="flex-1 flex items-center justify-center gap-[6px] mt-[8px] py-[8px] rounded-[8px] cursor-pointer"
                      style={{ background: 'rgba(255,255,255,.06)', border: '1px solid rgba(255,255,255,.2)', color: 'var(--wc-y)' }}
                      onClick={(e) => { e.stopPropagation(); startEdit(exp); }}
                      data-testid={`expense-edit-${exp.id}`}
                    >
                      <Pencil className="w-[13px] h-[13px]" />
                      <span className="font-heading font-bold text-[11px] uppercase">Edit</span>
                    </button>
                    <button
                      className="flex items-center justify-center gap-[6px] mt-[8px] px-[16px] py-[8px] rounded-[8px] cursor-pointer"
                      style={{ background: 'rgba(239,68,68,.06)', border: '1px solid rgba(239,68,68,.2)', color: 'var(--wc-re)' }}
                      onClick={(e) => { e.stopPropagation(); handleDelete(exp.id); }}
                      data-testid={`expense-delete-${exp.id}`}
                    >
                      <Trash2 className="w-[13px] h-[13px]" />
                      <span className="font-heading font-bold text-[11px] uppercase">Delete</span>
                    </button>
                  </div>
                )}
              </div>
            );
          })}
        </div>
      )}

      {tab === 'report' && (
        <div className="flex-1 px-[14px] pb-[20px] flex flex-col gap-[8px] overflow-y-auto scrollbar-thin" style={{ overscrollBehavior: 'contain', WebkitOverflowScrolling: 'touch' } as any}>
          <div className="flex gap-[6px]">
            <div className="flex-1 rounded-[10px] p-[10px_12px]" style={{ background: 'var(--wc-card)', border: '1px solid var(--wc-border)' }}>
              <div className="font-data text-[8px] uppercase tracking-[.1em]" style={{ color: 'var(--wc-t3)' }}>Total Vehicle</div>
              <div className="font-heading font-black text-[20px] leading-[1.2]" style={{ color: 'var(--wc-y)' }}>${reportData.totalVehicle.toFixed(0)}</div>
            </div>
            <div className="flex-1 rounded-[10px] p-[10px_12px]" style={{ background: 'var(--wc-card)', border: '1px solid var(--wc-border)' }}>
              <div className="font-data text-[8px] uppercase tracking-[.1em]" style={{ color: 'var(--wc-t3)' }}>Biz Use</div>
              <div className="font-heading font-black text-[20px] leading-[1.2]" style={{ color: 'var(--wc-gr)' }}>{bizPct}%</div>
            </div>
            <div className="flex-1 rounded-[10px] p-[10px_12px]" style={{ background: 'var(--wc-card)', border: '1px solid var(--wc-border)' }}>
              <div className="font-data text-[8px] uppercase tracking-[.1em]" style={{ color: 'var(--wc-t3)' }}>Deductible</div>
              <div className="font-heading font-black text-[20px] leading-[1.2]" style={{ color: 'var(--wc-gr)' }}>${reportData.deductible.toFixed(0)}</div>
            </div>
          </div>

          {ATO_CATEGORIES.map(cat => {
            const amt = reportData.map[cat] || 0;
            const isEstimated = cat === 'Fuel / Electricity' || cat === 'Depreciation';
            const pct = reportData.totalVehicle > 0 ? (amt / reportData.totalVehicle * 100) : 0;
            return (
              <div key={cat} className="rounded-[12px] p-[12px_14px]" style={{ background: 'var(--wc-card)', border: '1px solid var(--wc-border)' }}>
                <div className="flex items-center justify-between mb-[4px]">
                  <div className="flex items-center gap-[6px]">
                    <span className="font-semibold text-[14px] text-white">{cat}</span>
                    {isEstimated && (
                      <span className="font-data text-[8px] uppercase tracking-[.1em] px-[5px] py-[2px] rounded-[4px]" style={{ background: 'rgba(153,153,153,.1)', color: 'var(--wc-am)', border: '1px solid rgba(153,153,153,.2)' }}>
                        Est.
                      </span>
                    )}
                  </div>
                  <div className="font-heading font-bold text-[14px]" style={{ color: amt > 0 ? 'var(--wc-y)' : 'var(--wc-t3)' }}>
                    {amt > 0 ? `$${amt.toFixed(2)}` : '—'}
                    {cat === 'Fuel / Electricity' && amt > 0 ? '*' : ''}
                  </div>
                </div>
                <div className="h-[4px] rounded-full overflow-hidden" style={{ background: 'rgba(255,255,255,.04)' }}>
                  <div className="h-full rounded-full transition-all" style={{ width: `${pct}%`, background: isEstimated ? 'var(--wc-am)' : 'var(--wc-y)' }} />
                </div>
              </div>
            );
          })}

          <div className="rounded-[12px] p-[12px_14px]" style={{ background: 'rgba(255,255,255,.04)', border: '1.5px solid rgba(255,255,255,.25)' }}>
            <div className="flex items-center justify-between">
              <span className="font-heading font-bold text-[15px] uppercase text-white">Total Vehicle Expenses</span>
              <span className="font-heading font-black text-[18px]" style={{ color: 'var(--wc-y)' }}>${reportData.totalVehicle.toFixed(2)}</span>
            </div>
            <div className="flex items-center justify-between mt-[6px]">
              <span className="text-[12px]" style={{ color: 'var(--wc-t3)' }}>Business use ({bizPct}%)</span>
              <span className="font-heading font-bold text-[14px]" style={{ color: 'var(--wc-gr)' }}>${reportData.deductible.toFixed(2)}</span>
            </div>
          </div>

          <div className="rounded-[10px] p-[10px_12px] flex items-start gap-[8px]" style={{ background: 'rgba(153,153,153,.04)', border: '1px solid rgba(153,153,153,.15)' }}>
            <AlertTriangle className="w-[16px] h-[16px] flex-shrink-0 mt-[1px]" style={{ color: 'var(--wc-am)' }} />
            <div className="text-[11px] leading-[1.4]" style={{ color: 'var(--wc-t3)' }}>
              * Fuel estimate is based on {bizKm.toFixed(0)} business km, {litresPer100}L/100km consumption, and ${avgFuelPrice.toFixed(2)}/L avg price. Your tax agent can update these figures at tax time.
            </div>
          </div>

          <button
            className="w-full rounded-[12px] py-[14px] font-heading font-bold text-[15px] uppercase tracking-[.04em] flex items-center justify-center gap-[8px] cursor-pointer transition-all active:scale-[.98] mb-[4px]"
            style={{ background: 'rgba(255,255,255,.08)', border: '1.5px solid rgba(255,255,255,.3)', color: 'var(--wc-y)' }}
            onClick={handleExportCSV}
            data-testid="button-export-expenses"
          >
            <Download className="w-[18px] h-[18px]" />
            Export for Accountant
          </button>
        </div>
      )}

      {tab === 'entries' && (
        <div className="px-[14px] py-[8px] flex-shrink-0">
          <button
            className="w-full rounded-[14px] py-[15px] font-heading font-black text-[17px] tracking-[.07em] uppercase text-black cursor-pointer flex items-center justify-center gap-3 transition-all active:scale-[.98]"
            style={{ background: 'var(--wc-y)', boxShadow: '0 4px 20px rgba(255,255,255,.25)' }}
            onClick={() => setAdding(true)}
            data-testid="button-add-expense"
          >
            <Plus className="w-[20px] h-[20px]" strokeWidth={2.5} />
            Add Expense
          </button>
        </div>
      )}

      <BottomNav />
    </div>
  );
}
