import { useState, useRef, useEffect } from 'react';
import { useApp } from '@/lib/app-context';
import { BottomNav } from './bottom-nav';
import { ArrowLeft, ArrowRight, Check, MessageSquarePlus, Lightbulb, ChevronDown, ChevronUp } from 'lucide-react';

const SUGGESTIONS = [
  'Client: ',
  'Site: ',
  'Store: ',
  'Picked up ',
  'Quote for ',
  'Meeting with ',
  'Delivered to ',
  'Inspected ',
];

export function NotesScreen() {
  const { state, dispatch } = useApp();
  const [editingTrip, setEditingTrip] = useState<number | null>(null);
  const [noteText, setNoteText] = useState('');
  const inputRef = useRef<HTMLTextAreaElement>(null);

  const bizTrips = state.trips
    .map((t, i) => ({ trip: t, idx: i }))
    .filter(({ trip }) => trip.type === 'business' && !trip.autoGenerated);

  const withNotes = bizTrips.filter(({ trip }) => trip.notes && trip.notes.length > 0).length;
  const withoutNotes = bizTrips.length - withNotes;

  useEffect(() => {
    if (editingTrip !== null && inputRef.current) {
      inputRef.current.focus();
    }
  }, [editingTrip]);

  const startEditing = (tripIdx: number) => {
    setEditingTrip(tripIdx);
    setNoteText(state.trips[tripIdx].notes || '');
  };

  const saveNote = () => {
    if (editingTrip === null) return;
    dispatch({ type: 'UPDATE_TRIP', tripIndex: editingTrip, updates: { notes: noteText.trim() } });
    setEditingTrip(null);
    setNoteText('');
  };

  const applySuggestion = (suggestion: string) => {
    setNoteText(prev => prev + suggestion);
    inputRef.current?.focus();
  };

  return (
    <div className="flex flex-col h-full" data-testid="notes-screen">
      <div className="flex items-center gap-[10px] px-4 pt-2 pb-[5px] flex-shrink-0">
        <button
          className="w-[30px] h-[30px] rounded-lg flex items-center justify-center"
          style={{ background: 'rgba(255,255,255,.06)', border: '1px solid var(--wc-border)' }}
          onClick={() => dispatch({ type: 'GO_SCREEN', screen: 'review' })}
          data-testid="button-back-notes"
        >
          <ArrowLeft className="w-[15px] h-[15px]" style={{ color: 'var(--wc-t2)' }} />
        </button>
        <span className="font-heading font-extrabold text-[20px] uppercase tracking-[.04em] text-white">Trip Notes</span>
        <span className="ml-auto text-[11px]" style={{ color: 'var(--wc-t3)' }}>{bizTrips.length} business</span>
      </div>

      <div className="flex px-[14px] pb-[5px] flex-shrink-0 gap-0">
        <div className="flex items-center gap-[10px]">
          {[
            { id: 'step1', label: 'Sort', done: true },
            { id: 'step2', label: 'Classify', done: true },
            { id: 'step3', label: 'Review', done: true },
            { id: 'step4', label: 'Notes', active: true },
            { id: 'step5', label: 'Odometer' },
          ].map((step, i, arr) => (
            <div key={step.id} className="flex flex-col items-center flex-1 relative">
              {i < arr.length - 1 && (
                <div className="absolute top-[8px] left-1/2 right-[-50%] h-px z-0" style={{ background: step.done ? 'rgba(245,196,0,.4)' : 'var(--wc-border)' }} />
              )}
              <div
                className="w-4 h-4 rounded-full flex items-center justify-center font-heading text-[9px] font-bold relative z-[1] transition-all"
                style={{
                  background: step.active ? 'var(--wc-y)' : step.done ? 'rgba(245,196,0,.15)' : 'var(--wc-bg)',
                  border: step.active ? '1.5px solid var(--wc-y)' : step.done ? '1.5px solid rgba(245,196,0,.5)' : '1.5px solid var(--wc-border)',
                  color: step.active ? '#000' : step.done ? 'var(--wc-y)' : 'var(--wc-t3)',
                }}
              >
                {step.done ? '\u2713' : i + 1}
              </div>
              <div className="font-data text-[7px] uppercase tracking-[.07em] mt-[3px] text-center" style={{ color: step.active ? 'var(--wc-y)' : step.done ? 'rgba(245,196,0,.55)' : 'var(--wc-t3)' }}>
                {step.label}
              </div>
            </div>
          ))}
        </div>
      </div>

      <div className="mx-[14px] mb-[6px] rounded-[10px] p-[10px_12px] flex-shrink-0" style={{ background: 'rgba(245,196,0,.06)', border: '1px solid rgba(245,196,0,.2)' }}>
        <div className="flex items-start gap-[8px]">
          <Lightbulb className="w-[16px] h-[16px] flex-shrink-0 mt-[1px]" style={{ color: 'var(--wc-y)' }} />
          <div>
            <div className="font-heading font-bold text-[12px] uppercase tracking-[.04em] mb-[2px]" style={{ color: 'var(--wc-y)' }}>
              Add trip details for the ATO
            </div>
            <div className="text-[10px] leading-[1.5]" style={{ color: 'var(--wc-t2)' }}>
              The ATO likes to see context on business trips. Add client names, store names, job site details, or what you picked up. It strengthens your claim.
            </div>
          </div>
        </div>
      </div>

      {withoutNotes > 0 && (
        <div className="mx-[14px] mb-[4px] flex items-center gap-[6px] flex-shrink-0">
          <div className="w-[6px] h-[6px] rounded-full" style={{ background: 'var(--wc-am)' }} />
          <span className="font-data text-[9px] uppercase tracking-[.08em]" style={{ color: 'var(--wc-am)' }}>
            {withoutNotes} trip{withoutNotes !== 1 ? 's' : ''} without notes
          </span>
          <div className="flex-1 h-px" style={{ background: 'var(--wc-border)' }} />
          <span className="font-data text-[9px] uppercase tracking-[.08em]" style={{ color: 'var(--wc-gr)' }}>
            {withNotes} done
          </span>
        </div>
      )}

      <div className="flex-1 px-[14px] pb-1 flex flex-col gap-[5px] overflow-y-auto scrollbar-thin">
        {bizTrips.map(({ trip, idx }) => {
          const isEditing = editingTrip === idx;
          const hasNote = trip.notes && trip.notes.length > 0;

          return (
            <div
              key={idx}
              className="rounded-[12px] transition-all"
              style={{
                background: 'var(--wc-card)',
                border: isEditing ? '1.5px solid rgba(245,196,0,.5)' : hasNote ? '1px solid rgba(34,197,94,.25)' : '1px solid rgba(245,158,11,.3)',
                borderLeft: isEditing ? '3px solid var(--wc-y)' : hasNote ? '3px solid rgba(34,197,94,.5)' : '3px solid rgba(245,158,11,.5)',
              }}
              data-testid={`notes-trip-${idx}`}
            >
              <div
                className="flex items-center gap-[8px] p-[10px_12px] cursor-pointer"
                onClick={() => isEditing ? saveNote() : startEditing(idx)}
              >
                <div className="flex-1 min-w-0">
                  <div className="font-semibold text-[12px] text-white truncate">
                    {trip.from} &rarr; {trip.to}
                  </div>
                  <div className="text-[10px]" style={{ color: 'var(--wc-t3)' }}>
                    {trip.date} &middot; {trip.km} km
                    {trip.purposeLabel && <span style={{ color: 'var(--wc-y)' }}> &middot; {trip.purposeLabel}</span>}
                  </div>
                </div>

                {hasNote && !isEditing && (
                  <div className="flex items-center gap-[4px] px-[6px] py-[2px] rounded-[5px]" style={{ background: 'rgba(34,197,94,.1)', border: '1px solid rgba(34,197,94,.2)' }}>
                    <Check className="w-[10px] h-[10px]" style={{ color: 'var(--wc-gr)' }} />
                    <span className="font-data text-[8px] uppercase" style={{ color: 'var(--wc-gr)' }}>Noted</span>
                  </div>
                )}

                {!hasNote && !isEditing && (
                  <div className="flex items-center gap-[4px] px-[6px] py-[2px] rounded-[5px]" style={{ background: 'rgba(245,158,11,.08)', border: '1px solid rgba(245,158,11,.2)' }}>
                    <MessageSquarePlus className="w-[10px] h-[10px]" style={{ color: 'var(--wc-am)' }} />
                    <span className="font-data text-[8px] uppercase" style={{ color: 'var(--wc-am)' }}>Add</span>
                  </div>
                )}

                {isEditing ? (
                  <ChevronUp className="w-[14px] h-[14px] flex-shrink-0" style={{ color: 'var(--wc-y)' }} />
                ) : (
                  <ChevronDown className="w-[14px] h-[14px] flex-shrink-0" style={{ color: 'var(--wc-t3)' }} />
                )}
              </div>

              {isEditing && (
                <div className="px-[12px] pb-[10px] border-t" style={{ borderColor: 'rgba(245,196,0,.15)' }}>
                  <textarea
                    ref={inputRef}
                    className="w-full rounded-lg p-[8px_10px] text-[12px] text-white outline-none resize-none mt-[8px] font-sans"
                    style={{ background: 'rgba(255,255,255,.05)', border: '1px solid rgba(245,196,0,.25)', minHeight: '60px' }}
                    value={noteText}
                    onChange={e => setNoteText(e.target.value)}
                    placeholder="e.g. Client: John Smith, picked up tiles from Bunnings for bathroom reno"
                    data-testid={`notes-input-${idx}`}
                  />

                  <div className="flex flex-wrap gap-[4px] mt-[6px]">
                    {SUGGESTIONS.map((s) => (
                      <button
                        key={s}
                        className="rounded-[5px] px-[7px] py-[3px] font-data text-[8px] uppercase tracking-[.04em] cursor-pointer transition-all"
                        style={{ background: 'rgba(255,255,255,.05)', border: '1px solid var(--wc-border)', color: 'var(--wc-t2)' }}
                        onClick={() => applySuggestion(s)}
                        data-testid={`notes-suggest-${s.replace(/[^a-zA-Z]/g, '').toLowerCase()}`}
                      >
                        {s.trim().replace(/:$/, '')}
                      </button>
                    ))}
                  </div>

                  <div className="flex gap-[6px] mt-[8px]">
                    <button
                      className="flex-1 py-[7px] rounded-[8px] font-heading font-bold text-[11px] uppercase tracking-[.04em] cursor-pointer transition-all"
                      style={{ background: 'rgba(255,255,255,.04)', border: '1px solid var(--wc-border)', color: 'var(--wc-t3)' }}
                      onClick={() => { setEditingTrip(null); setNoteText(''); }}
                      data-testid={`notes-cancel-${idx}`}
                    >
                      Cancel
                    </button>
                    <button
                      className="flex-1 py-[7px] rounded-[8px] font-heading font-bold text-[11px] uppercase tracking-[.04em] text-black cursor-pointer transition-all"
                      style={{ background: 'var(--wc-y)' }}
                      onClick={saveNote}
                      data-testid={`notes-save-${idx}`}
                    >
                      Save Note
                    </button>
                  </div>

                  {hasNote && (
                    <div className="mt-[4px] text-[9px] italic truncate" style={{ color: 'var(--wc-t3)' }}>
                      Current: {trip.notes}
                    </div>
                  )}
                </div>
              )}
            </div>
          );
        })}

        {bizTrips.length === 0 && (
          <div className="flex flex-col items-center justify-center py-[30px]">
            <MessageSquarePlus className="w-[32px] h-[32px] mb-[8px]" style={{ color: 'var(--wc-t3)' }} />
            <div className="font-heading font-bold text-[14px] uppercase text-center" style={{ color: 'var(--wc-t3)' }}>No business trips yet</div>
            <div className="text-[11px] text-center mt-[3px]" style={{ color: 'var(--wc-t3)' }}>Sort and classify trips first, then come back to add notes.</div>
          </div>
        )}
      </div>

      <div className="px-[14px] py-[6px] flex-shrink-0">
        <button
          className="w-full rounded-[13px] py-[13px] font-heading font-black text-[17px] tracking-[.07em] uppercase text-black cursor-pointer flex items-center justify-center gap-2 transition-all"
          style={{ background: 'var(--wc-y)', boxShadow: '0 4px 20px rgba(245,196,0,.25)' }}
          onClick={() => dispatch({ type: 'GO_SCREEN', screen: 'odometer' })}
          data-testid="button-done-notes"
        >
          <ArrowRight className="w-[18px] h-[18px]" strokeWidth={2.5} />
          Continue to Odometer
        </button>
      </div>

      <BottomNav activeOverride="review" />
    </div>
  );
}
