import { useState, useRef, useEffect, useMemo } from 'react';
import { useApp } from '@/lib/app-context';
import { BottomNav } from './bottom-nav';
import { ArrowLeft, ArrowRight, Check, MessageSquarePlus, Lightbulb, Clock, MapPin, User, X, ChevronDown, ChevronUp, Pencil } from 'lucide-react';

const PREFIXES = ['Client', 'Site', 'Store', 'Picked up', 'Quote for', 'Meeting with', 'Delivered to', 'Inspected', 'Other'] as const;

const KNOWN_PLACES: Record<string, string> = {
  bunnings: 'Store: Bunnings — picked up ',
  reece: 'Store: Reece Plumbing — picked up ',
  'trade depot': 'Store: Trade Depot — picked up ',
  officeworks: 'Store: Officeworks — ',
  mitre: 'Store: Mitre 10 — picked up ',
  tradelink: 'Store: Tradelink — picked up ',
  'total tools': 'Store: Total Tools — picked up ',
  sydneytools: 'Store: Sydney Tools — picked up ',
  'masters': 'Store: Masters — picked up ',
  coles: 'Store: Coles — ',
  woolworths: 'Store: Woolworths — ',
};

function getStoredHistory(): string[] {
  try {
    const raw = localStorage.getItem('wc_note_history');
    return raw ? JSON.parse(raw) : [];
  } catch { return []; }
}

function addToHistory(note: string) {
  if (!note || note.length < 3) return;
  const history = getStoredHistory();
  const clean = note.trim();
  const filtered = history.filter(h => h !== clean);
  filtered.unshift(clean);
  localStorage.setItem('wc_note_history', JSON.stringify(filtered.slice(0, 100)));
}

function getStoredNames(prefix: string): string[] {
  try {
    const raw = localStorage.getItem('wc_names_' + prefix.toLowerCase());
    return raw ? JSON.parse(raw) : [];
  } catch { return []; }
}

function addToNames(prefix: string, name: string) {
  if (!name || name.length < 2) return;
  const names = getStoredNames(prefix);
  const clean = name.trim();
  const filtered = names.filter(n => n !== clean);
  filtered.unshift(clean);
  localStorage.setItem('wc_names_' + prefix.toLowerCase(), JSON.stringify(filtered.slice(0, 50)));
}

function extractNamesFromNote(note: string) {
  for (const prefix of PREFIXES) {
    const pattern = new RegExp(`^${prefix}:\\s*(.+?)(?:\\s*[—–-]|$)`, 'i');
    const match = note.match(pattern);
    if (match && match[1]?.trim()) {
      addToNames(prefix, match[1].trim());
    }
  }
}

function suggestFromDestination(to: string, toSub: string, purposeLabel: string | null): string | null {
  const dest = (to + ' ' + toSub).toLowerCase();
  for (const [key, template] of Object.entries(KNOWN_PLACES)) {
    if (dest.includes(key)) return template;
  }
  if (purposeLabel) {
    const label = purposeLabel.toLowerCase();
    if (label.includes('client') || label.includes('site visit')) {
      return `Client: — ${purposeLabel.toLowerCase()} at ${to}`;
    }
    if (label.includes('supplier') || label.includes('materials')) {
      return `Store: ${to} — picked up `;
    }
    return `${purposeLabel} — ${to}`;
  }
  if (dest.includes('home') || dest.includes('gym') || dest.includes('school')) return null;
  return `Site: ${to} — `;
}

export function NotesScreen() {
  const { state, dispatch } = useApp();
  const [focusedTrip, setFocusedTrip] = useState<number | null>(null);
  const [expandedDone, setExpandedDone] = useState<Set<number>>(new Set());
  const [finishedNotes, setFinishedNotes] = useState<Set<number>>(() => {
    const initial = new Set<number>();
    state.trips.forEach((t, i) => {
      if (t.type === 'business' && !t.autoGenerated && t.notes && t.notes.trim().length > 0) {
        initial.add(i);
      }
    });
    return initial;
  });
  const [noteTexts, setNoteTexts] = useState<Record<number, string>>(() => {
    const initial: Record<number, string> = {};
    state.trips.forEach((t, i) => {
      if (t.type === 'business' && !t.autoGenerated) {
        initial[i] = t.notes || '';
      }
    });
    return initial;
  });
  const [activePrefix, setActivePrefix] = useState<string | null>(null);
  const inputRefs = useRef<Record<number, HTMLTextAreaElement | null>>({});

  const bizTrips = state.trips
    .map((t, i) => ({ trip: t, idx: i }))
    .filter(({ trip }) => trip.type === 'business' && !trip.autoGenerated);

  const allHaveNotes = bizTrips.every(({ idx }) => finishedNotes.has(idx));
  const withNotes = bizTrips.filter(({ idx }) => finishedNotes.has(idx)).length;
  const withoutNotes = bizTrips.length - withNotes;

  const recentHistory = useMemo(() => getStoredHistory().slice(0, 8), [focusedTrip]);
  const prefixNames = useMemo(() => activePrefix ? getStoredNames(activePrefix) : [], [activePrefix, focusedTrip]);

  const focusedTripData = focusedTrip !== null ? state.trips[focusedTrip] : null;
  const smartSuggestion = useMemo(() => {
    if (!focusedTripData) return null;
    return suggestFromDestination(focusedTripData.to, focusedTripData.toSub, focusedTripData.purposeLabel);
  }, [focusedTripData?.to, focusedTripData?.toSub, focusedTripData?.purposeLabel]);

  const updateNoteText = (idx: number, text: string) => {
    setNoteTexts(prev => ({ ...prev, [idx]: text }));
    setActivePrefix(null);
  };

  const saveNote = (idx: number) => {
    const trimmed = (noteTexts[idx] ?? '').trim();
    dispatch({ type: 'UPDATE_TRIP', tripIndex: idx, updates: { notes: trimmed } });
    if (trimmed) {
      addToHistory(trimmed);
      extractNamesFromNote(trimmed);
      setFinishedNotes(prev => new Set(prev).add(idx));
      setExpandedDone(prev => {
        const next = new Set(prev);
        next.delete(idx);
        return next;
      });
      setFocusedTrip(prev => prev === idx ? null : prev);
    } else {
      setFinishedNotes(prev => {
        const next = new Set(prev);
        next.delete(idx);
        return next;
      });
    }
  };

  const saveAllAndContinue = () => {
    bizTrips.forEach(({ idx }) => saveNote(idx));
    dispatch({ type: 'GO_SCREEN', screen: 'odometer' });
  };

  const handlePrefixTap = (prefix: string, idx: number) => {
    if (prefix === 'Other') {
      updateNoteText(idx, (noteTexts[idx] ?? '') + 'Other: ');
      setActivePrefix(null);
      inputRefs.current[idx]?.focus();
      return;
    }
    const names = getStoredNames(prefix);
    if (names.length > 0) {
      setActivePrefix(activePrefix === prefix ? null : prefix);
    } else {
      updateNoteText(idx, (noteTexts[idx] ?? '') + prefix + ': ');
      setActivePrefix(null);
      inputRefs.current[idx]?.focus();
    }
  };

  const handleNameSelect = (prefix: string, name: string, idx: number) => {
    updateNoteText(idx, (noteTexts[idx] ?? '') + `${prefix}: ${name} — `);
    setActivePrefix(null);
    inputRefs.current[idx]?.focus();
  };

  const handleHistorySelect = (note: string, idx: number) => {
    updateNoteText(idx, note);
    setActivePrefix(null);
  };

  const useSuggestion = (idx: number) => {
    if (smartSuggestion) {
      updateNoteText(idx, smartSuggestion);
      inputRefs.current[idx]?.focus();
    }
  };

  return (
    <div className="flex flex-col h-full" data-testid="notes-screen">
      <div className="flex items-center gap-[8px] px-[14px] pt-[6px] pb-[4px] flex-shrink-0">
        <button
          className="w-[36px] h-[36px] rounded-lg flex items-center justify-center"
          style={{ background: 'rgb(var(--wc-ink) / .06)', border: '1px solid var(--wc-border)' }}
          onClick={() => dispatch({ type: 'GO_SCREEN', screen: 'review' })}
          data-testid="button-back-notes"
        >
          <ArrowLeft className="w-[18px] h-[18px]" style={{ color: 'var(--wc-t2)' }} />
        </button>
        <span className="font-heading font-extrabold text-[18px] uppercase tracking-[.04em]" style={{ color: 'var(--wc-text)' }}>Trip Notes</span>
        <div className="ml-auto flex gap-[6px] items-center">
          {withoutNotes > 0 && (
            <span className="font-data text-[11px] font-bold" style={{ color: 'var(--wc-am)' }}>{withoutNotes} remaining</span>
          )}
          {withNotes > 0 && (
            <span className="font-data text-[11px]" style={{ color: 'var(--wc-gr)' }}>{withNotes} done</span>
          )}
        </div>
      </div>

      <div className="flex-1 px-[14px] pb-1 flex flex-col gap-[8px] overflow-y-auto scrollbar-thin" style={{ WebkitOverflowScrolling: 'touch' }}>
        {bizTrips.map(({ trip, idx }) => {
          const noteText = noteTexts[idx] ?? '';
          const hasNote = noteText.trim().length > 0;
          const isFocused = focusedTrip === idx;
          const isCollapsed = finishedNotes.has(idx) && !expandedDone.has(idx);

          const toggleDoneExpand = () => {
            setExpandedDone(prev => {
              const next = new Set(prev);
              if (next.has(idx)) {
                next.delete(idx);
                setFocusedTrip(null);
              } else {
                next.add(idx);
              }
              return next;
            });
          };

          return (
            <div
              key={idx}
              className="rounded-[14px] transition-all flex-shrink-0"
              style={{
                background: 'var(--wc-card)',
                border: hasNote ? '1px solid rgba(34,197,94,.25)' : '1px solid rgba(153,153,153,.3)',
                borderLeft: hasNote ? '4px solid rgba(34,197,94,.5)' : '4px solid rgba(153,153,153,.5)',
              }}
              data-testid={`notes-trip-${idx}`}
            >
              <div
                className="flex items-center gap-[8px] p-[12px_14px]"
                style={{ cursor: finishedNotes.has(idx) ? 'pointer' : 'default' }}
                onClick={() => finishedNotes.has(idx) && toggleDoneExpand()}
              >
                <div className="flex-1 min-w-0">
                  <div className="font-semibold text-[14px] truncate" style={{ color: 'var(--wc-text)' }}>
                    {trip.from} &rarr; {trip.to}
                  </div>
                  <div className="text-[11px] mt-[2px]" style={{ color: 'var(--wc-t3)' }}>
                    {trip.date} &middot; {trip.km} km
                    {trip.purposeLabel && <span style={{ color: 'var(--wc-y)' }}> &middot; {trip.purposeLabel}</span>}
                  </div>
                  {isCollapsed && (
                    <div className="text-[12px] mt-[4px] italic truncate" style={{ color: 'var(--wc-gr)' }}>
                      {noteText.trim()}
                    </div>
                  )}
                </div>
                {finishedNotes.has(idx) ? (
                  <div className="flex items-center gap-[5px] px-[10px] py-[6px] rounded-[8px]" style={{ background: 'rgba(34,197,94,.1)', border: '1px solid rgba(34,197,94,.2)' }}>
                    <Check className="w-[14px] h-[14px]" style={{ color: 'var(--wc-gr)' }} />
                    <span className="font-data text-[11px] uppercase" style={{ color: 'var(--wc-gr)' }}>Done</span>
                  </div>
                ) : (
                  <div className="flex items-center gap-[5px] px-[10px] py-[6px] rounded-[8px]" style={{ background: 'rgba(153,153,153,.08)', border: '1px solid rgba(153,153,153,.2)' }}>
                    <MessageSquarePlus className="w-[14px] h-[14px]" style={{ color: 'var(--wc-am)' }} />
                    <span className="font-data text-[11px] uppercase" style={{ color: 'var(--wc-am)' }}>Required</span>
                  </div>
                )}
                {finishedNotes.has(idx) && (
                  <div className="w-[28px] h-[28px] rounded-[8px] flex items-center justify-center flex-shrink-0" style={{ background: 'rgb(var(--wc-ink) / .05)' }}>
                    {isCollapsed ? (
                      <ChevronDown className="w-[15px] h-[15px]" style={{ color: 'var(--wc-t3)' }} />
                    ) : (
                      <ChevronUp className="w-[15px] h-[15px]" style={{ color: 'var(--wc-t3)' }} />
                    )}
                  </div>
                )}
              </div>

              {!isCollapsed && (
                <div className="px-[14px] pb-[10px]">
                  {isFocused && smartSuggestion && !noteText && (
                    <button
                      className="w-full mb-[8px] rounded-[12px] p-[12px_14px] text-left cursor-pointer transition-all flex items-start gap-[10px]"
                      style={{ background: 'rgb(var(--wc-ink) / .06)', border: '1px solid rgb(var(--wc-ink) / .2)' }}
                      onClick={() => useSuggestion(idx)}
                      data-testid={`notes-suggestion-${idx}`}
                    >
                      <Lightbulb className="w-[18px] h-[18px] flex-shrink-0 mt-[1px]" style={{ color: 'var(--wc-y)' }} />
                      <div>
                        <div className="font-heading font-bold text-[12px] uppercase tracking-[.04em] mb-[2px]" style={{ color: 'var(--wc-y)' }}>Suggested</div>
                        <div className="text-[14px]" style={{ color: 'var(--wc-t2)' }}>{smartSuggestion}</div>
                      </div>
                    </button>
                  )}

                  <textarea
                    ref={el => { inputRefs.current[idx] = el; }}
                    className="w-full rounded-[10px] p-[10px] text-[14px] outline-none resize-none font-sans leading-[1.5]"
                    style={{ background: 'rgb(var(--wc-ink) / .05)', border: isFocused ? '1.5px solid rgb(var(--wc-ink) / .35)' : '1px solid rgb(var(--wc-ink) / .12)', minHeight: '52px', color: 'var(--wc-text)' }}
                    value={noteText}
                    onChange={e => updateNoteText(idx, e.target.value)}
                    onFocus={() => { setFocusedTrip(idx); setActivePrefix(null); }}
                    onBlur={() => saveNote(idx)}
                    placeholder="Add a note for this trip..."
                    data-testid={`notes-input-${idx}`}
                  />

                  {isFocused && (
                    <>
                      <div className="flex flex-wrap gap-[6px] mt-[8px]">
                        {PREFIXES.map((s) => {
                          const names = getStoredNames(s);
                          const isActive = activePrefix === s;
                          return (
                            <button
                              key={s}
                              className="rounded-[10px] px-[14px] py-[10px] font-heading font-bold text-[14px] uppercase tracking-[.03em] cursor-pointer transition-all flex items-center gap-[5px]"
                              style={{
                                background: isActive ? 'rgb(var(--wc-ink) / .15)' : 'rgb(var(--wc-ink) / .06)',
                                border: isActive ? '1.5px solid rgb(var(--wc-ink) / .4)' : '1px solid var(--wc-border)',
                                color: isActive ? 'var(--wc-y)' : 'var(--wc-t2)',
                              }}
                              onMouseDown={e => e.preventDefault()}
                              onClick={() => handlePrefixTap(s, idx)}
                              data-testid={`notes-prefix-${s.replace(/[^a-zA-Z]/g, '').toLowerCase()}-${idx}`}
                            >
                              {s}
                              {names.length > 0 && (
                                <span className="font-data text-[10px] rounded-full w-[18px] h-[18px] flex items-center justify-center" style={{ background: isActive ? 'var(--wc-y)' : 'rgb(var(--wc-ink) / .1)', color: isActive ? 'var(--wc-bg)' : 'var(--wc-t3)' }}>
                                  {names.length}
                                </span>
                              )}
                            </button>
                          );
                        })}
                      </div>

                      {activePrefix && prefixNames.length > 0 && (
                        <div className="mt-[8px] rounded-[12px] overflow-hidden" style={{ background: 'rgb(var(--wc-ink) / .03)', border: '1px solid rgb(var(--wc-ink) / .2)' }}>
                          <div className="flex items-center justify-between px-[14px] py-[10px]" style={{ borderBottom: '1px solid rgb(var(--wc-ink) / .1)' }}>
                            <span className="font-heading font-bold text-[13px] uppercase tracking-[.04em]" style={{ color: 'var(--wc-y)' }}>
                              <User className="w-[14px] h-[14px] inline mr-[5px]" />
                              Your {activePrefix}s
                            </span>
                            <button onMouseDown={e => e.preventDefault()} onClick={() => setActivePrefix(null)} className="w-[32px] h-[32px] rounded-[8px] flex items-center justify-center cursor-pointer" style={{ background: 'rgb(var(--wc-ink) / .06)' }} data-testid={`notes-close-names-${idx}`}>
                              <X className="w-[16px] h-[16px]" style={{ color: 'var(--wc-t3)' }} />
                            </button>
                          </div>
                          {prefixNames.map((name, ni) => (
                            <button
                              key={ni}
                              className="w-full text-left px-[14px] py-[12px] text-[15px] cursor-pointer transition-all flex items-center gap-[10px]"
                              style={{ color: 'var(--wc-text)', borderBottom: ni < prefixNames.length - 1 ? '1px solid rgb(var(--wc-ink) / .04)' : 'none' }}
                              onMouseDown={e => e.preventDefault()}
                              onClick={() => handleNameSelect(activePrefix, name, idx)}
                              data-testid={`notes-name-${idx}-${ni}`}
                            >
                              <MapPin className="w-[16px] h-[16px] flex-shrink-0" style={{ color: 'var(--wc-y)' }} />
                              {name}
                            </button>
                          ))}
                        </div>
                      )}

                      {recentHistory.length > 0 && !noteText && !activePrefix && (
                        <div className="mt-[8px]">
                          <div className="flex items-center gap-[6px] mb-[6px]">
                            <Clock className="w-[13px] h-[13px]" style={{ color: 'var(--wc-t3)' }} />
                            <span className="font-data text-[11px] uppercase tracking-[.08em]" style={{ color: 'var(--wc-t3)' }}>Recent</span>
                          </div>
                          <div className="flex flex-col gap-[5px]">
                            {recentHistory.slice(0, 4).map((h, hi) => (
                              <button
                                key={hi}
                                className="w-full text-left rounded-[10px] px-[14px] py-[12px] text-[14px] cursor-pointer transition-all truncate"
                                style={{ background: 'rgb(var(--wc-ink) / .03)', border: '1px solid var(--wc-border)', color: 'var(--wc-t2)' }}
                                onMouseDown={e => e.preventDefault()}
                                onClick={() => handleHistorySelect(h, idx)}
                                data-testid={`notes-history-${idx}-${hi}`}
                              >
                                {h}
                              </button>
                            ))}
                          </div>
                        </div>
                      )}
                    </>
                  )}
                </div>
              )}
            </div>
          );
        })}

        {bizTrips.length === 0 && (
          <div className="flex flex-col items-center justify-center py-[30px]">
            <MessageSquarePlus className="w-[36px] h-[36px] mb-[10px]" style={{ color: 'var(--wc-t3)' }} />
            <div className="font-heading font-bold text-[16px] uppercase text-center" style={{ color: 'var(--wc-t3)' }}>No business trips</div>
            <div className="text-[12px] text-center mt-[4px]" style={{ color: 'var(--wc-t3)' }}>Sort and classify trips first.</div>
          </div>
        )}
      </div>

      <div className="px-[14px] py-[6px] flex-shrink-0">
        <button
          className="w-full rounded-[12px] py-[13px] font-heading font-black text-[16px] tracking-[.07em] uppercase flex items-center justify-center gap-2 transition-all"
          style={{
            background: allHaveNotes ? 'var(--wc-y)' : 'rgb(var(--wc-ink) / .15)',
            color: allHaveNotes ? 'var(--wc-bg)' : 'rgb(var(--wc-ink) / .35)',
            boxShadow: allHaveNotes ? '0 4px 20px rgb(var(--wc-ink) / .25)' : 'none',
            cursor: allHaveNotes ? 'pointer' : 'not-allowed',
          }}
          onClick={() => allHaveNotes && saveAllAndContinue()}
          disabled={!allHaveNotes}
          data-testid="button-done-notes"
        >
          <ArrowRight className="w-[17px] h-[17px]" strokeWidth={2.5} />
          {allHaveNotes ? 'Continue to Odometer' : `${withoutNotes} note${withoutNotes !== 1 ? 's' : ''} remaining`}
        </button>
      </div>

      <BottomNav activeOverride="review" />
    </div>
  );
}
