import { useState, useEffect, useCallback } from 'react';
import { useApp } from '@/lib/app-context';
import { getTripOdoStart, getTripOdoEnd } from '@/lib/trip-data';
import { BottomNav } from './bottom-nav';
import { ArrowLeft, AlertTriangle, Check, Trash2, Loader2, ChevronDown } from 'lucide-react';

const MAPS_KEY = import.meta.env.VITE_GOOGLE_MAPS_API_KEY || '';

function loadGMaps(): Promise<void> {
  if ((window as any)._gmapsLoaded) return Promise.resolve();
  if ((window as any)._gmapsPromise) return (window as any)._gmapsPromise;
  (window as any)._gmapsPromise = new Promise<void>((resolve, reject) => {
    if (!MAPS_KEY) { reject(new Error('No key')); return; }
    const script = document.createElement('script');
    script.src = `https://maps.googleapis.com/maps/api/js?key=${MAPS_KEY}&libraries=places,geometry`;
    script.async = true;
    script.onload = () => { (window as any)._gmapsLoaded = true; resolve(); };
    script.onerror = () => reject(new Error('Failed'));
    document.head.appendChild(script);
  });
  return (window as any)._gmapsPromise;
}

function calcGapDistance(from: string, fromSub: string, to: string, toSub: string): Promise<number | null> {
  return loadGMaps().then(() => {
    const ds = new (window as any).google.maps.DirectionsService();
    const origin = fromSub ? `${from}, ${fromSub}` : from;
    const dest = toSub ? `${to}, ${toSub}` : to;
    return new Promise<number | null>((resolve) => {
      ds.route({
        origin,
        destination: dest,
        travelMode: (window as any).google.maps.TravelMode.DRIVING,
        region: 'au',
      }, (result: any, status: string) => {
        if (status === 'OK' && result?.routes?.[0]) {
          let totalM = 0;
          result.routes[0].legs.forEach((leg: any) => { totalM += leg.distance?.value || 0; });
          resolve(totalM / 1000);
        } else {
          resolve(null);
        }
      });
    });
  }).catch(() => null);
}

export function ReviewScreen() {
  const { state, dispatch } = useApp();
  const [expandedTrip, setExpandedTrip] = useState<number | null>(null);
  const [gapKmInputs, setGapKmInputs] = useState<Record<number, string>>({});
  const [gapCalcStatus, setGapCalcStatus] = useState<Record<number, 'idle' | 'loading' | 'done' | 'error'>>({});
  const [calcedGaps, setCalcedGaps] = useState<Set<number>>(new Set());

  const sorted = state.trips.filter(t => t.type !== null);
  const biz = sorted.filter(t => t.type === 'business');
  const per = sorted.filter(t => t.type === 'personal');
  const unclassified = biz.filter(t => !t.purposeLabel).length;
  const gapTrips = sorted.filter(t => t.autoGenerated);
  const unconfirmedGaps = gapTrips.filter(t => !t.gapConfirmed).length;
  const canContinue = unconfirmedGaps === 0;

  useEffect(() => {
    const unconfirmedGapIndices = state.trips
      .map((t, i) => ({ t, i }))
      .filter(({ t, i }) => t.autoGenerated && !t.gapConfirmed && !calcedGaps.has(i));
    if (unconfirmedGapIndices.length === 0) return;
    unconfirmedGapIndices.forEach(({ t, i: idx }) => {
      setGapCalcStatus(prev => ({ ...prev, [idx]: 'loading' }));
      calcGapDistance(t.from, t.fromSub, t.to, t.toSub).then(km => {
        if (km != null) {
          const rounded = Math.round(km * 10) / 10;
          setGapKmInputs(prev => ({ ...prev, [idx]: rounded.toString() }));
          setGapCalcStatus(prev => ({ ...prev, [idx]: 'done' }));
        } else {
          setGapCalcStatus(prev => ({ ...prev, [idx]: 'error' }));
        }
        setCalcedGaps(prev => new Set(prev).add(idx));
      });
    });
  }, [state.trips, calcedGaps]);

  return (
    <div className="flex flex-col h-full" data-testid="review-screen">
      <div className="flex items-center gap-[10px] px-4 pt-[8px] pb-[6px] flex-shrink-0">
        <button
          className="w-[32px] h-[32px] rounded-lg flex items-center justify-center"
          style={{ background: 'rgb(var(--wc-ink) / .06)', border: '1px solid var(--wc-border)' }}
          onClick={() => dispatch({ type: 'GO_SCREEN', screen: 'sort' })}
          data-testid="button-back-review"
        >
          <ArrowLeft className="w-[16px] h-[16px]" style={{ color: 'var(--wc-t2)' }} />
        </button>
        <span className="font-heading font-extrabold text-[22px] uppercase tracking-[.04em]" style={{ color: 'var(--wc-text)' }}>Review</span>
        <span className="ml-auto font-data text-[12px]" style={{ color: 'var(--wc-t3)' }}>{sorted.length} trips</span>
      </div>

      <div className="flex gap-[6px] px-[14px] pb-[8px] flex-shrink-0">
        <div className="flex-1 rounded-[12px] p-[10px_12px]" style={{ background: 'var(--wc-card)', border: '1px solid var(--wc-border)' }}>
          <div className="font-data text-[9px] uppercase tracking-[.1em]" style={{ color: 'var(--wc-t3)' }}>Business</div>
          <div className="font-heading font-black text-[20px] leading-[1.2]" style={{ color: 'var(--wc-y)' }} data-testid="text-review-biz">{biz.length}</div>
        </div>
        <div className="flex-1 rounded-[12px] p-[10px_12px]" style={{ background: 'var(--wc-card)', border: '1px solid var(--wc-border)' }}>
          <div className="font-data text-[9px] uppercase tracking-[.1em]" style={{ color: 'var(--wc-t3)' }}>Personal</div>
          <div className="font-heading font-black text-[20px] leading-[1.2]" style={{ color: 'var(--wc-t2)' }}>{per.length}</div>
        </div>
        <div className="flex-1 rounded-[12px] p-[10px_12px]" style={{ background: 'var(--wc-card)', border: '1px solid var(--wc-border)' }}>
          <div className="font-data text-[9px] uppercase tracking-[.1em]" style={{ color: 'var(--wc-t3)' }}>Deduction*</div>
          <div className="font-heading font-black text-[20px] leading-[1.2]" style={{ color: 'var(--wc-gr)' }}>${Math.round(state.dedTotal).toLocaleString('en-AU')}</div>
        </div>
      </div>

      {unclassified > 0 && (
        <div className="mx-[14px] mb-[6px] flex items-center gap-[8px] rounded-[10px] p-[10px_14px] flex-shrink-0" style={{ background: 'rgb(var(--wc-ink) / .07)', border: '1px solid rgb(var(--wc-ink) / .25)' }}>
          <AlertTriangle className="w-[15px] h-[15px] flex-shrink-0" stroke="rgb(var(--wc-ink) / .9)" />
          <div className="text-[12px] leading-[1.4]" style={{ color: 'rgb(var(--wc-ink) / .85)' }}>
            <strong style={{ color: 'var(--wc-y)' }}>{unclassified} business trip{unclassified > 1 ? 's' : ''}</strong> need a purpose — tap to expand.
          </div>
        </div>
      )}

      {unconfirmedGaps > 0 && (
        <div className="mx-[14px] mb-[6px] flex items-center gap-[8px] rounded-[10px] p-[10px_14px] flex-shrink-0" style={{ background: 'rgba(153,153,153,.07)', border: '1px solid rgba(153,153,153,.25)' }}>
          <AlertTriangle className="w-[15px] h-[15px] flex-shrink-0" stroke="rgba(153,153,153,.9)" />
          <div className="text-[12px] leading-[1.4]" style={{ color: 'rgba(153,153,153,.85)' }}>
            <strong style={{ color: 'var(--wc-am)' }}>{unconfirmedGaps} gap{unconfirmedGaps > 1 ? 's' : ''}</strong> need confirmation — expand each and tap Confirm.
          </div>
        </div>
      )}

      <div className="flex-1 px-[14px] pb-1 flex flex-col gap-[8px] overflow-y-auto scrollbar-thin">
        {sorted.map((t) => {
          const origIdx = state.trips.indexOf(t);
          const baseOdo = state.lastOdoReading || state.baseOdo;
          const oStart = Math.round(getTripOdoStart(state.trips, origIdx, baseOdo));
          const oEnd = Math.round(getTripOdoEnd(state.trips, origIdx, baseOdo));
          const isExpanded = expandedTrip === origIdx;
          const isGap = !!t.autoGenerated;
          const gapConfirmed = isGap && !!t.gapConfirmed;
          const showGapStyle = isGap && !gapConfirmed;

          return (
            <div
              key={origIdx}
              className="rounded-[14px] cursor-pointer transition-all"
              style={{
                background: showGapStyle ? 'rgba(153,153,153,.03)' : 'var(--wc-card)',
                border: showGapStyle ? '1px dashed rgba(153,153,153,.3)' : '1px solid var(--wc-border)',
                borderLeft: showGapStyle ? '3px dashed rgba(153,153,153,.5)' : t.type === 'business' ? '3px solid rgb(var(--wc-ink) / .6)' : '3px solid rgba(180,180,180,.25)',
              }}
              data-testid={`review-trip-${origIdx}`}
            >
              <div className="flex items-center gap-[10px] p-[14px_16px]" onClick={() => setExpandedTrip(isExpanded ? null : origIdx)}>
                <div className="flex-1 min-w-0">
                  <div className={`font-semibold text-[15px] mb-[4px] leading-[1.3] ${isExpanded ? '' : 'truncate'}`} style={{ color: showGapStyle ? 'var(--wc-am)' : 'var(--wc-text)' }}>
                    {isGap && <span className="font-data text-[9px] uppercase tracking-[.08em] mr-[6px] px-[5px] py-[2px] rounded-[4px]" style={{ background: gapConfirmed ? 'rgba(34,197,94,.1)' : 'rgba(153,153,153,.12)', color: gapConfirmed ? 'var(--wc-gr)' : 'var(--wc-am)', border: gapConfirmed ? '1px solid rgba(34,197,94,.25)' : '1px solid rgba(153,153,153,.2)' }}>{gapConfirmed ? 'GAP \u2713' : 'GAP'}</span>}
                    {t.from} &rarr; {t.to}
                  </div>
                  <div className="text-[12px]" style={{ color: 'var(--wc-t3)' }}>
                    {isGap ? (gapConfirmed ? `Confirmed · ${t.km > 0 ? t.km + ' km' : ''}` : (gapKmInputs[origIdx] ? `${gapKmInputs[origIdx]} km — tap to confirm` : 'Unlogged gap')) : `${t.date} · ${t.km} km · ${t.duration}`}
                  </div>
                </div>
                <span
                  className="font-heading font-bold text-[12px] px-[10px] py-[5px] rounded-[8px] uppercase tracking-[.04em] flex-shrink-0"
                  style={{
                    background: t.type === 'business' ? 'var(--wc-yd)' : 'rgba(180,180,180,.08)',
                    color: t.type === 'business' ? 'var(--wc-y)' : 'rgba(180,180,180,.7)',
                    border: t.type === 'business' ? '1px solid rgb(var(--wc-ink) / .22)' : '1px solid rgba(180,180,180,.15)',
                  }}
                >
                  {t.type === 'business' ? 'Biz' : 'Per'}
                </span>
                <ChevronDown className="w-[16px] h-[16px] flex-shrink-0 transition-transform" style={{ color: 'var(--wc-t3)', transform: isExpanded ? 'rotate(180deg)' : 'none' }} />
              </div>
              {isExpanded && (
                <div className="p-[12px_16px_14px] flex flex-col gap-[8px] border-t" style={{ borderColor: showGapStyle ? 'rgba(153,153,153,.15)' : 'var(--wc-border)' }}>
                  {isGap ? (
                    <div className="text-[12px] leading-[1.6]" style={{ color: 'var(--wc-t3)' }}>
                      {!gapConfirmed && (() => {
                        const status = gapCalcStatus[origIdx] || 'idle';
                        return (
                          <>
                            <div className="rounded-[10px] px-[12px] py-[8px] mb-[8px]" style={{ background: 'rgba(153,153,153,.06)', border: '1px solid rgba(153,153,153,.15)' }}>
                              <div className="font-heading font-bold text-[11px] uppercase tracking-[.04em] mb-[3px]" style={{ color: 'var(--wc-am)' }}>Auto-generated connector</div>
                              {status === 'loading' && (
                                <div className="flex items-center gap-[6px] text-[11px]" style={{ color: 'var(--wc-am)' }}>
                                  <Loader2 className="w-[13px] h-[13px] animate-spin" />
                                  Calculating route distance...
                                </div>
                              )}
                              {status === 'done' && (
                                <div className="text-[11px]" style={{ color: 'var(--wc-gr)' }}>
                                  Route calculated: {gapKmInputs[origIdx]} km
                                </div>
                              )}
                              {status === 'error' && (
                                <div className="text-[11px]" style={{ color: 'var(--wc-t3)' }}>
                                  Could not auto-calculate. Enter distance manually.
                                </div>
                              )}
                              {status === 'idle' && (
                                <div className="text-[11px]" style={{ color: 'var(--wc-t3)' }}>
                                  Preparing to calculate...
                                </div>
                              )}
                            </div>
                            <strong style={{ color: 'var(--wc-am)' }}>From:</strong> {t.from}, {t.fromSub}<br />
                            <strong style={{ color: 'var(--wc-am)' }}>To:</strong> {t.to}, {t.toSub}<br />
                            <div className="mt-[8px]">
                              <label className="font-data text-[9px] uppercase tracking-[.1em] block mb-[4px]" style={{ color: status === 'done' ? 'var(--wc-gr)' : 'var(--wc-am)' }}>
                                {status === 'done' ? 'Calculated distance (editable)' : 'Gap distance (km)'}
                              </label>
                              <input
                                type="number"
                                step="0.1"
                                min="0"
                                className="w-full rounded-[10px] p-[10px_12px] text-[14px] outline-none font-data"
                                style={{ background: 'rgb(var(--wc-ink) / .06)', border: status === 'done' ? '1px solid rgba(34,197,94,.25)' : '1px solid rgba(153,153,153,.25)', color: 'var(--wc-text)' }}
                                value={gapKmInputs[origIdx] ?? ''}
                                onChange={e => setGapKmInputs(prev => ({ ...prev, [origIdx]: e.target.value }))}
                                onClick={e => e.stopPropagation()}
                                placeholder={status === 'loading' ? 'Calculating...' : 'Enter km'}
                                data-testid={`gap-km-input-${origIdx}`}
                              />
                            </div>
                          </>
                        );
                      })()}
                      {gapConfirmed && (
                        <>
                          <div className="rounded-[10px] px-[12px] py-[8px] mb-[8px]" style={{ background: 'rgba(34,197,94,.06)', border: '1px solid rgba(34,197,94,.15)' }}>
                            <div className="font-heading font-bold text-[11px] uppercase tracking-[.04em]" style={{ color: 'var(--wc-gr)' }}>Confirmed &mdash; {t.km} km added to odometer chain</div>
                          </div>
                          <strong style={{ color: 'var(--wc-text)' }}>From:</strong> {t.from}, {t.fromSub}<br />
                          <strong style={{ color: 'var(--wc-text)' }}>To:</strong> {t.to}, {t.toSub}<br />
                        </>
                      )}
                      <strong style={{ color: gapConfirmed ? 'var(--wc-text)' : 'var(--wc-am)' }}>Odometer:</strong> {oStart.toLocaleString('en-AU')} &rarr; {oEnd.toLocaleString('en-AU')} km
                    </div>
                  ) : (
                    <div className="text-[13px] leading-[1.8]" style={{ color: 'var(--wc-t2)' }}>
                      <strong style={{ color: 'var(--wc-text)' }}>From:</strong> {t.from}, {t.fromSub}<br />
                      <strong style={{ color: 'var(--wc-text)' }}>To:</strong> {t.to}, {t.toSub}<br />
                      <strong style={{ color: 'var(--wc-text)' }}>Time:</strong> {t.time} &middot; <strong style={{ color: 'var(--wc-text)' }}>Duration:</strong> {t.duration}<br />
                      <strong style={{ color: 'var(--wc-text)' }}>Odometer:</strong> {oStart.toLocaleString('en-AU')} &rarr; {oEnd.toLocaleString('en-AU')} km
                    </div>
                  )}
                  {t.purposeLabel && (
                    <div className="text-[13px] italic" style={{ color: 'var(--wc-gr)' }}>Purpose: {t.purposeLabel}</div>
                  )}
                  {t.notes && (
                    <div className="text-[12px] rounded-[8px] p-[6px_10px]" style={{ background: 'rgb(var(--wc-ink) / .03)', border: '1px solid var(--wc-border)', color: 'var(--wc-t2)' }}>
                      <span className="font-data text-[9px] uppercase tracking-[.08em]" style={{ color: 'var(--wc-t3)' }}>Notes: </span>{t.notes}
                    </div>
                  )}
                  {isGap && !gapConfirmed && (
                    <div className="flex gap-[8px]">
                      <button
                        className="flex-1 py-[12px] rounded-[10px] font-heading font-bold text-[14px] tracking-[.05em] uppercase cursor-pointer transition-all flex items-center justify-center gap-[6px]"
                        style={{
                          background: (parseFloat(gapKmInputs[origIdx] || '0') > 0) ? 'rgba(153,153,153,.15)' : 'rgba(153,153,153,.06)',
                          border: '1.5px solid rgba(153,153,153,.35)',
                          color: 'var(--wc-am)',
                          opacity: (parseFloat(gapKmInputs[origIdx] || '0') > 0) ? 1 : 0.5,
                          cursor: (parseFloat(gapKmInputs[origIdx] || '0') > 0) ? 'pointer' : 'not-allowed',
                        }}
                        onClick={(e) => {
                          e.stopPropagation();
                          const km = parseFloat(gapKmInputs[origIdx] || '0');
                          if (km <= 0) return;
                          dispatch({ type: 'CONFIRM_GAP', tripIndex: origIdx, km });
                        }}
                        data-testid={`confirm-gap-${origIdx}`}
                      >
                        <Check className="w-[15px] h-[15px]" strokeWidth={2.5} />
                        Confirm Gap
                      </button>
                      <button
                        className="py-[12px] px-[16px] rounded-[10px] font-heading font-bold text-[14px] tracking-[.05em] uppercase cursor-pointer transition-all flex items-center justify-center gap-[6px]"
                        style={{ background: 'rgba(239,68,68,.08)', border: '1.5px solid rgba(239,68,68,.3)', color: 'var(--wc-re)' }}
                        onClick={(e) => {
                          e.stopPropagation();
                          dispatch({ type: 'DELETE_GAP', tripIndex: origIdx });
                          setExpandedTrip(null);
                        }}
                        data-testid={`delete-gap-${origIdx}`}
                      >
                        <Trash2 className="w-[15px] h-[15px]" strokeWidth={2.5} />
                        Delete
                      </button>
                    </div>
                  )}
                  <div className="flex gap-[8px]">
                    <button
                      className="flex-1 py-[10px] rounded-[10px] font-heading font-bold text-[13px] tracking-[.05em] uppercase cursor-pointer transition-all"
                      style={{ color: 'rgba(180,180,180,.7)', background: t.type === 'personal' ? 'rgba(180,180,180,.1)' : 'transparent', border: '1.5px solid rgba(180,180,180,.25)' }}
                      onClick={(e) => { e.stopPropagation(); dispatch({ type: 'RECLASSIFY', tripIndex: origIdx, tripType: 'personal' }); }}
                      data-testid={`reclassify-personal-${origIdx}`}
                    >
                      &larr; Personal
                    </button>
                    <button
                      className="flex-1 py-[10px] rounded-[10px] font-heading font-bold text-[13px] tracking-[.05em] uppercase cursor-pointer transition-all"
                      style={{ color: 'var(--wc-y)', background: 'var(--wc-yd)', border: '1.5px solid rgb(var(--wc-ink) / .4)' }}
                      onClick={(e) => { e.stopPropagation(); dispatch({ type: 'RECLASSIFY', tripIndex: origIdx, tripType: 'business' }); }}
                      data-testid={`reclassify-business-${origIdx}`}
                    >
                      Business &rarr;
                    </button>
                    <button
                      className="py-[10px] px-[14px] rounded-[10px] font-heading font-bold text-[13px] tracking-[.05em] uppercase cursor-pointer transition-all"
                      style={{ border: '1px solid var(--wc-border)', background: 'rgb(var(--wc-ink) / .04)', color: 'var(--wc-t2)' }}
                      onClick={(e) => { e.stopPropagation(); dispatch({ type: 'OPEN_EDIT', tripIndex: origIdx }); }}
                      data-testid={`edit-trip-${origIdx}`}
                    >
                      Edit
                    </button>
                  </div>
                </div>
              )}
            </div>
          );
        })}
      </div>

      <div className="px-[14px] py-[8px] flex-shrink-0">
        <button
          className="w-full rounded-[14px] py-[14px] font-heading font-black text-[17px] tracking-[.07em] uppercase flex items-center justify-center gap-2 transition-all"
          style={{
            background: canContinue ? 'var(--wc-y)' : 'rgb(var(--wc-ink) / .25)',
            color: canContinue ? 'var(--wc-bg)' : 'rgb(var(--wc-ink) / .4)',
            boxShadow: canContinue ? '0 4px 20px rgb(var(--wc-ink) / .25)' : 'none',
            cursor: canContinue ? 'pointer' : 'not-allowed',
          }}
          onClick={() => canContinue && dispatch({ type: 'GO_SCREEN', screen: 'notes' })}
          disabled={!canContinue}
          data-testid="button-done-review"
        >
          <Check className="w-[18px] h-[18px]" strokeWidth={2.5} />
          {canContinue ? 'Continue to Notes \u2192' : `Confirm ${unconfirmedGaps} Gap${unconfirmedGaps > 1 ? 's' : ''} First`}
        </button>
      </div>

      <BottomNav activeOverride="review" />
    </div>
  );
}
