import { useMemo } from 'react';
import { useApp } from '@/lib/app-context';
import { calcLogbookDeduction } from '@/lib/trip-data';
import { BottomNav } from './bottom-nav';
import { ArrowLeft, TrendingUp, MapPin, DollarSign, Fuel, Route, Target } from 'lucide-react';

interface TripLike {
  from: string;
  to: string;
  km: number;
  date: string;
  type: 'business' | 'personal' | null;
  autoGenerated?: boolean;
  year?: number;
  month?: number;
  day?: number;
}

function getDayNameFromDate(t: TripLike): string | null {
  if (t.year !== undefined && t.month !== undefined && t.day !== undefined) {
    const d = new Date(t.year, t.month, t.day);
    return ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'][d.getDay()];
  }
  const match = t.date.match(/^(Mon|Tue|Wed|Thu|Fri|Sat|Sun)/i);
  return match ? match[1].charAt(0).toUpperCase() + match[1].slice(1).toLowerCase() : null;
}

function getDateKey(t: TripLike): string {
  if (t.year !== undefined && t.month !== undefined && t.day !== undefined) {
    return `${t.year}-${String(t.month + 1).padStart(2, '0')}-${String(t.day).padStart(2, '0')}`;
  }
  const months: Record<string, string> = { Jan: '01', Feb: '02', Mar: '03', Apr: '04', May: '05', Jun: '06', Jul: '07', Aug: '08', Sep: '09', Oct: '10', Nov: '11', Dec: '12' };
  const m = t.date.match(/(\d{1,2})\s+(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)/i);
  if (m) return `2026-${months[m[2]] || '01'}-${m[1].padStart(2, '0')}`;
  return t.date;
}

function DonutChart({ bizPct, size = 90, stroke = 10 }: { bizPct: number; size?: number; stroke?: number }) {
  const r = (size - stroke) / 2;
  const circ = 2 * Math.PI * r;
  const bizLen = (bizPct / 100) * circ;
  const perLen = circ - bizLen;
  return (
    <svg width={size} height={size} viewBox={`0 0 ${size} ${size}`}>
      <circle cx={size / 2} cy={size / 2} r={r} fill="none" stroke="rgb(var(--wc-ink) / .06)" strokeWidth={stroke} />
      {bizPct > 0 && (
        <circle
          cx={size / 2} cy={size / 2} r={r} fill="none"
          stroke="var(--wc-y)" strokeWidth={stroke}
          strokeDasharray={`${bizLen} ${perLen}`}
          strokeDashoffset={circ / 4}
          strokeLinecap="round"
          style={{ transition: 'stroke-dasharray .6s ease' }}
        />
      )}
      {bizPct > 0 && bizPct < 100 && (
        <circle
          cx={size / 2} cy={size / 2} r={r} fill="none"
          stroke="rgb(var(--wc-ink) / .15)" strokeWidth={stroke}
          strokeDasharray={`${perLen} ${bizLen}`}
          strokeDashoffset={circ / 4 - bizLen}
          strokeLinecap="round"
          style={{ transition: 'stroke-dasharray .6s ease' }}
        />
      )}
    </svg>
  );
}

function LineChart({ data, width = 300, height = 100 }: { data: { label: string; value: number }[]; width?: number; height?: number }) {
  if (data.length === 0) return null;
  const maxVal = Math.max(1, ...data.map(d => d.value));
  const padX = 6;
  const padY = 8;
  const w = width - padX * 2;
  const h = height - padY * 2;
  const points = data.map((d, i) => ({
    x: padX + (data.length > 1 ? (i / (data.length - 1)) * w : w / 2),
    y: padY + h - (d.value / maxVal) * h,
  }));
  const lineD = points.map((p, i) => `${i === 0 ? 'M' : 'L'}${p.x},${p.y}`).join(' ');
  const areaD = lineD + ` L${points[points.length - 1].x},${padY + h} L${points[0].x},${padY + h} Z`;

  return (
    <svg width="100%" height={height} viewBox={`0 0 ${width} ${height}`} preserveAspectRatio="none">
      <defs>
        <linearGradient id="lineGrad" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0%" stopColor="var(--wc-y)" stopOpacity="0.3" />
          <stop offset="100%" stopColor="var(--wc-y)" stopOpacity="0.02" />
        </linearGradient>
      </defs>
      <path d={areaD} fill="url(#lineGrad)" />
      <path d={lineD} fill="none" stroke="var(--wc-y)" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" />
      {points.map((p, i) => (
        <circle key={i} cx={p.x} cy={p.y} r="3.5" fill="var(--wc-bg)" stroke="var(--wc-y)" strokeWidth="2" />
      ))}
    </svg>
  );
}

export function StatsScreen() {
  const { state, dispatch } = useApp();

  const activeReports = useMemo(() =>
    state.savedReports.filter(r => !r.supersedes),
    [state.savedReports]
  );

  const currentSessionHasReport = useMemo(() =>
    activeReports.some(r => r.sessionId === state.sessionId),
    [activeReports, state.sessionId]
  );

  const allTrips: TripLike[] = useMemo(() => {
    const trips: TripLike[] = [];
    for (const r of activeReports) {
      if (currentSessionHasReport && r.sessionId === state.sessionId) {
        trips.push(...r.trips.filter(t => t.type !== null && !t.autoGenerated));
      } else if (r.sessionId !== state.sessionId) {
        trips.push(...r.trips.filter(t => t.type !== null && !t.autoGenerated));
      }
    }
    if (!currentSessionHasReport) {
      trips.push(...state.trips.filter(t => t.type !== null && !t.autoGenerated));
    }
    return trips;
  }, [activeReports, currentSessionHasReport, state.sessionId, state.trips]);

  const sorted = allTrips;
  const biz = sorted.filter(t => t.type === 'business');
  const per = sorted.filter(t => t.type === 'personal');
  const totalKm = sorted.reduce((s, t) => s + t.km, 0);
  const bizKm = biz.reduce((s, t) => s + t.km, 0);
  const perKm = per.reduce((s, t) => s + t.km, 0);
  const bizPct = totalKm > 0 ? (bizKm / totalKm * 100) : 0;
  const avgTripKm = sorted.length > 0 ? totalKm / sorted.length : 0;
  const avgBizTripKm = biz.length > 0 ? bizKm / biz.length : 0;

  const { projectedDeductibles, weeksTracked } = useMemo(() => {
    const dateKeys = sorted.map(t => getDateKey(t)).filter(k => /^\d{4}-\d{2}-\d{2}$/.test(k));
    if (dateKeys.length === 0) return { projectedDeductibles: 0, weeksTracked: 0 };
    const sorted_ = [...dateKeys].sort();
    const earliest = new Date(sorted_[0]);
    const latest = new Date(sorted_[sorted_.length - 1]);
    const daySpan = Math.max(1, Math.ceil((latest.getTime() - earliest.getTime()) / (1000 * 60 * 60 * 24)) + 1);
    const wks = Math.min(12, Math.max(1, daySpan / 7));
    const workingDaysInSpan = Math.max(1, Math.round(daySpan * 5 / 7));
    const logbookDed = calcLogbookDeduction(bizKm, totalKm);
    const dailyRate = logbookDed / workingDaysInSpan;
    const annualWorkingDays = 48 * 5;
    return { projectedDeductibles: Math.round(dailyRate * annualWorkingDays), weeksTracked: Math.round(wks * 10) / 10 };
  }, [sorted, bizKm, totalKm]);

  const dayStats = useMemo(() => {
    const days: Record<string, { biz: number; per: number; bizKm: number; perKm: number }> = {};
    const dayNames = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];
    dayNames.forEach(d => { days[d] = { biz: 0, per: 0, bizKm: 0, perKm: 0 }; });
    sorted.forEach(t => {
      const dayName = getDayNameFromDate(t);
      if (dayName && days[dayName]) {
        if (t.type === 'business') { days[dayName].biz += 1; days[dayName].bizKm += t.km; }
        else { days[dayName].per += 1; days[dayName].perKm += t.km; }
      }
    });
    return dayNames.map(name => ({ name, ...days[name] }));
  }, [sorted]);

  const maxDayTotal = Math.max(1, ...dayStats.map(d => d.biz + d.per));

  const dailyKmTrend = useMemo(() => {
    const map: Record<string, number> = {};
    sorted.forEach(t => {
      const key = getDateKey(t);
      map[key] = (map[key] || 0) + t.km;
    });
    const entries = Object.entries(map).sort((a, b) => a[0].localeCompare(b[0]));
    return entries.map(([label, value]) => ({ label, value }));
  }, [sorted]);

  const topDestinations = useMemo(() => {
    const map: Record<string, { count: number; km: number }> = {};
    sorted.forEach(t => {
      if (!map[t.to]) map[t.to] = { count: 0, km: 0 };
      map[t.to].count += 1;
      map[t.to].km += t.km;
    });
    return Object.entries(map).sort((a, b) => b[1].count - a[1].count).slice(0, 5);
  }, [sorted]);

  const maxDestCount = Math.max(1, ...topDestinations.map(([, d]) => d.count));

  const expenses = useMemo(() => {
    try {
      const raw = localStorage.getItem('wc_expenses');
      return raw ? JSON.parse(raw) : [];
    } catch { return []; }
  }, []);
  const totalExpenses = expenses.reduce((s: number, e: any) => s + (e.amount || 0), 0);
  const fuelCost = expenses.filter((e: any) => e.category === 'Fuel & Oil').reduce((s: number, e: any) => s + (e.amount || 0), 0);
  const costPerKm = totalKm > 0 ? (totalExpenses / totalKm) : 0;

  return (
    <div className="flex flex-col h-full" data-testid="stats-screen">
      <div className="flex items-center gap-[10px] px-4 pt-2 pb-[5px] flex-shrink-0">
        <button
          className="w-[34px] h-[34px] rounded-lg flex items-center justify-center"
          style={{ background: 'rgb(var(--wc-ink) / .06)', border: '1px solid var(--wc-border)' }}
          onClick={() => dispatch({ type: 'GO_SCREEN', screen: 'dashboard' })}
          data-testid="button-back-stats"
        >
          <ArrowLeft className="w-[16px] h-[16px]" style={{ color: 'var(--wc-t2)' }} />
        </button>
        <span className="font-heading font-extrabold text-[22px] uppercase tracking-[.04em]" style={{ color: 'var(--wc-text)' }}>My Stats</span>
        <TrendingUp className="ml-auto w-[18px] h-[18px]" style={{ color: 'var(--wc-y)' }} />
      </div>

      <div className="flex-1 px-[14px] pb-[80px] flex flex-col gap-[10px] overflow-y-auto scrollbar-thin" style={{ overscrollBehavior: 'contain', WebkitOverflowScrolling: 'touch' } as any}>

        <div className="grid grid-cols-2 gap-[6px]">
          <div className="rounded-[12px] p-[12px]" style={{ background: 'var(--wc-card)', border: '1px solid var(--wc-border)' }}>
            <MapPin className="w-[16px] h-[16px] mb-[4px]" style={{ color: 'var(--wc-y)' }} />
            <div className="font-heading font-black text-[26px] leading-none" style={{ color: 'var(--wc-y)' }}>{sorted.length}</div>
            <div className="font-data text-[9px] uppercase tracking-[.1em] mt-[2px]" style={{ color: 'var(--wc-t3)' }}>Total Trips</div>
          </div>
          <div className="rounded-[12px] p-[12px]" style={{ background: 'var(--wc-card)', border: '1px solid var(--wc-border)' }}>
            <DollarSign className="w-[16px] h-[16px] mb-[4px]" style={{ color: 'var(--wc-gr)' }} />
            <div className="font-heading font-black text-[24px] leading-none" style={{ color: 'var(--wc-gr)' }}>
              ${projectedDeductibles.toLocaleString('en-AU')}
            </div>
            <div className="font-data text-[8px] uppercase tracking-[.06em] mt-[2px] leading-[1.4]" style={{ color: 'var(--wc-t3)' }}>
              Claimable Est.
            </div>
            <div className="font-data text-[7px] mt-[1px] leading-[1.3]" style={{ color: 'var(--wc-t3)', opacity: 0.7 }}>
              Projected from {weeksTracked} wk avg
            </div>
          </div>
          <div className="rounded-[12px] p-[12px]" style={{ background: 'var(--wc-card)', border: '1px solid var(--wc-border)' }}>
            <Route className="w-[16px] h-[16px] mb-[4px]" style={{ color: 'var(--wc-y)' }} />
            <div className="font-heading font-black text-[26px] leading-none" style={{ color: 'var(--wc-text)' }}>{totalKm.toFixed(0)}<span className="text-[13px] font-bold" style={{ color: 'var(--wc-t3)' }}> km</span></div>
            <div className="font-data text-[9px] uppercase tracking-[.1em] mt-[2px]" style={{ color: 'var(--wc-t3)' }}>Total Distance</div>
          </div>
          <div className="rounded-[12px] p-[12px]" style={{ background: 'var(--wc-card)', border: '1px solid var(--wc-border)' }}>
            <Fuel className="w-[16px] h-[16px] mb-[4px]" style={{ color: 'var(--wc-am)' }} />
            <div className="font-heading font-black text-[26px] leading-none" style={{ color: 'var(--wc-am)' }}>${fuelCost > 0 ? fuelCost.toFixed(0) : '—'}</div>
            <div className="font-data text-[9px] uppercase tracking-[.1em] mt-[2px]" style={{ color: 'var(--wc-t3)' }}>Fuel Costs</div>
          </div>
        </div>

        {projectedDeductibles > 0 && (
          <div className="rounded-[8px] px-[10px] py-[6px] flex items-start gap-[6px]" style={{ background: 'rgb(var(--wc-ink) / .03)', border: '1px solid rgb(var(--wc-ink) / .06)' }}>
            <DollarSign className="w-[12px] h-[12px] flex-shrink-0 mt-[1px]" style={{ color: 'var(--wc-t3)' }} />
            <div className="font-data text-[9px] leading-[1.5]" style={{ color: 'var(--wc-t3)' }}>
              Claimable deductibles estimated at <strong style={{ color: 'var(--wc-gr)' }}>${projectedDeductibles.toLocaleString('en-AU')}</strong> — projected from your {weeksTracked}-week logbook average over a 5-day working week, across 48 weeks. This is an estimate only.
            </div>
          </div>
        )}

        <div className="rounded-[12px] p-[14px]" style={{ background: 'var(--wc-card)', border: '1px solid var(--wc-border)' }}>
          <div className="font-heading font-bold text-[12px] uppercase tracking-[.06em] mb-[12px]" style={{ color: 'var(--wc-t2)' }}>Business vs Personal</div>
          <div className="flex items-center gap-[16px]">
            <div className="flex-shrink-0 relative">
              <DonutChart bizPct={bizPct} size={84} stroke={9} />
              <div className="absolute inset-0 flex flex-col items-center justify-center">
                <div className="font-heading font-black text-[18px] leading-none" style={{ color: 'var(--wc-y)' }}>{Math.round(bizPct)}%</div>
                <div className="font-data text-[7px] uppercase tracking-[.08em]" style={{ color: 'var(--wc-t3)' }}>Business</div>
              </div>
            </div>
            <div className="flex-1 flex flex-col gap-[8px]">
              <div className="flex items-center gap-[8px]">
                <div className="w-[8px] h-[8px] rounded-full flex-shrink-0" style={{ background: 'var(--wc-y)' }} />
                <div className="flex-1">
                  <div className="font-heading font-bold text-[13px]" style={{ color: 'var(--wc-text)' }}>{biz.length} Business</div>
                  <div className="font-data text-[10px]" style={{ color: 'var(--wc-t3)' }}>{bizKm.toFixed(1)} km</div>
                </div>
              </div>
              <div className="flex items-center gap-[8px]">
                <div className="w-[8px] h-[8px] rounded-full flex-shrink-0" style={{ background: 'rgb(var(--wc-ink) / .15)' }} />
                <div className="flex-1">
                  <div className="font-heading font-bold text-[13px]" style={{ color: 'var(--wc-text)' }}>{per.length} Personal</div>
                  <div className="font-data text-[10px]" style={{ color: 'var(--wc-t3)' }}>{perKm.toFixed(1)} km</div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div className="rounded-[12px] p-[14px]" style={{ background: 'var(--wc-card)', border: '1px solid var(--wc-border)' }}>
          <div className="flex items-center justify-between mb-[12px]">
            <div className="font-heading font-bold text-[12px] uppercase tracking-[.06em]" style={{ color: 'var(--wc-t2)' }}>Trips by Day</div>
            <div className="flex items-center gap-[10px]">
              <div className="flex items-center gap-[3px]">
                <div className="w-[6px] h-[6px] rounded-[2px]" style={{ background: 'var(--wc-y)' }} />
                <span className="font-data text-[8px] uppercase" style={{ color: 'var(--wc-t3)' }}>Biz</span>
              </div>
              <div className="flex items-center gap-[3px]">
                <div className="w-[6px] h-[6px] rounded-[2px]" style={{ background: 'rgb(var(--wc-ink) / .12)' }} />
                <span className="font-data text-[8px] uppercase" style={{ color: 'var(--wc-t3)' }}>Per</span>
              </div>
            </div>
          </div>
          <div className="flex items-end gap-[5px]" style={{ height: '80px' }}>
            {dayStats.map(d => {
              const total = d.biz + d.per;
              const barH = total > 0 ? Math.max(8, (total / maxDayTotal) * 68) : 4;
              const bizH = total > 0 ? (d.biz / total) * barH : 0;
              const perH = barH - bizH;
              return (
                <div key={d.name} className="flex-1 flex flex-col items-center justify-end h-full">
                  <div className="w-full flex flex-col rounded-[4px] overflow-hidden" style={{ height: `${barH}px` }}>
                    {perH > 0 && <div style={{ height: `${perH}px`, background: 'rgb(var(--wc-ink) / .1)' }} />}
                    {bizH > 0 && <div style={{ height: `${bizH}px`, background: 'var(--wc-y)' }} />}
                    {total === 0 && <div className="h-full" style={{ background: 'rgb(var(--wc-ink) / .04)' }} />}
                  </div>
                  <div className="font-data text-[8px] uppercase mt-[4px]" style={{ color: total > 0 ? 'var(--wc-text)' : 'var(--wc-t3)' }}>{d.name}</div>
                  <div className="font-data text-[9px] font-bold" style={{ color: total > 0 ? 'var(--wc-y)' : 'var(--wc-t3)' }}>{total}</div>
                </div>
              );
            })}
          </div>
        </div>

        {dailyKmTrend.length > 1 && (
          <div className="rounded-[12px] p-[14px]" style={{ background: 'var(--wc-card)', border: '1px solid var(--wc-border)' }}>
            <div className="flex items-center justify-between mb-[8px]">
              <div className="font-heading font-bold text-[12px] uppercase tracking-[.06em]" style={{ color: 'var(--wc-t2)' }}>Daily KM Trend</div>
              <div className="font-data text-[10px]" style={{ color: 'var(--wc-t3)' }}>{dailyKmTrend.length} days</div>
            </div>
            <div className="rounded-[8px] overflow-hidden" style={{ background: 'rgb(var(--wc-ink) / .02)' }}>
              <LineChart data={dailyKmTrend} height={110} />
            </div>
            <div className="flex justify-between mt-[6px]">
              <div className="font-data text-[9px]" style={{ color: 'var(--wc-t3)' }}>
                {dailyKmTrend[0]?.label.replace(/^\d{4}-/, '').replace('-', '/')}
              </div>
              <div className="font-data text-[9px]" style={{ color: 'var(--wc-t3)' }}>
                {dailyKmTrend[dailyKmTrend.length - 1]?.label.replace(/^\d{4}-/, '').replace('-', '/')}
              </div>
            </div>
          </div>
        )}

        <div className="rounded-[12px] p-[14px]" style={{ background: 'var(--wc-card)', border: '1px solid var(--wc-border)' }}>
          <div className="flex items-center justify-between mb-[8px]">
            <div className="font-heading font-bold text-[12px] uppercase tracking-[.06em]" style={{ color: 'var(--wc-t2)' }}>KM by Day</div>
          </div>
          <div className="flex flex-col gap-[6px]">
            {dayStats.map(d => {
              const totalDayKm = d.bizKm + d.perKm;
              const maxKm = Math.max(1, ...dayStats.map(dd => dd.bizKm + dd.perKm));
              const pct = totalDayKm > 0 ? (totalDayKm / maxKm) * 100 : 0;
              return (
                <div key={d.name} className="flex items-center gap-[8px]">
                  <div className="font-data text-[9px] uppercase w-[26px] flex-shrink-0 text-right" style={{ color: totalDayKm > 0 ? 'var(--wc-text)' : 'var(--wc-t3)' }}>{d.name}</div>
                  <div className="flex-1 h-[14px] rounded-[4px] overflow-hidden relative" style={{ background: 'rgb(var(--wc-ink) / .04)' }}>
                    {pct > 0 && (
                      <div
                        className="h-full rounded-[4px] flex items-center"
                        style={{ width: `${Math.max(2, pct)}%`, background: 'linear-gradient(90deg, var(--wc-y), rgb(var(--wc-ink) / .08))', transition: 'width .5s ease' }}
                      />
                    )}
                  </div>
                  <div className="font-data text-[10px] font-bold w-[36px] text-right" style={{ color: totalDayKm > 0 ? 'var(--wc-y)' : 'var(--wc-t3)' }}>
                    {totalDayKm > 0 ? totalDayKm.toFixed(0) : '—'}
                  </div>
                </div>
              );
            })}
          </div>
        </div>

        <div className="rounded-[12px] p-[14px]" style={{ background: 'var(--wc-card)', border: '1px solid var(--wc-border)' }}>
          <div className="flex items-center gap-[6px] mb-[10px]">
            <Target className="w-[14px] h-[14px]" style={{ color: 'var(--wc-y)' }} />
            <div className="font-heading font-bold text-[12px] uppercase tracking-[.06em]" style={{ color: 'var(--wc-t2)' }}>Top Destinations</div>
          </div>
          {topDestinations.map(([dest, data], i) => (
            <div key={dest} className="mb-[8px] last:mb-0">
              <div className="flex items-center justify-between mb-[3px]">
                <div className="flex items-center gap-[6px] flex-1 min-w-0">
                  <div
                    className="w-[18px] h-[18px] rounded-full flex items-center justify-center font-data text-[9px] font-bold flex-shrink-0"
                    style={{ background: i === 0 ? 'var(--wc-y)' : 'rgb(var(--wc-ink) / .08)', color: i === 0 ? 'var(--wc-bg)' : 'var(--wc-t2)' }}
                  >{i + 1}</div>
                  <div className="text-[12px] truncate font-heading font-bold" style={{ color: 'var(--wc-text)' }}>{dest}</div>
                </div>
                <div className="font-data text-[10px] flex-shrink-0 ml-[8px]" style={{ color: 'var(--wc-t3)' }}>{data.count} trip{data.count !== 1 ? 's' : ''} / {data.km.toFixed(0)} km</div>
              </div>
              <div className="h-[6px] rounded-full overflow-hidden" style={{ background: 'rgb(var(--wc-ink) / .04)' }}>
                <div
                  className="h-full rounded-full"
                  style={{
                    width: `${Math.max(3, (data.count / maxDestCount) * 100)}%`,
                    background: i === 0 ? 'var(--wc-y)' : `rgb(var(--wc-ink) / ${0.15 - i * 0.02})`,
                    transition: 'width .5s ease',
                  }}
                />
              </div>
            </div>
          ))}
          {topDestinations.length === 0 && (
            <div className="text-[12px] py-[6px]" style={{ color: 'var(--wc-t3)' }}>No trips sorted yet</div>
          )}
        </div>

        <div className="rounded-[12px] p-[14px]" style={{ background: 'var(--wc-card)', border: '1px solid var(--wc-border)' }}>
          <div className="font-heading font-bold text-[12px] uppercase tracking-[.06em] mb-[10px]" style={{ color: 'var(--wc-t2)' }}>Averages</div>
          <div className="grid grid-cols-3 gap-[8px]">
            <div className="text-center rounded-[10px] p-[10px]" style={{ background: 'rgb(var(--wc-ink) / .03)' }}>
              <div className="font-heading font-black text-[20px] leading-none" style={{ color: 'var(--wc-y)' }}>{avgTripKm.toFixed(1)}</div>
              <div className="font-data text-[8px] uppercase tracking-[.06em] mt-[4px]" style={{ color: 'var(--wc-t3)' }}>km / trip</div>
            </div>
            <div className="text-center rounded-[10px] p-[10px]" style={{ background: 'rgb(var(--wc-ink) / .03)' }}>
              <div className="font-heading font-black text-[20px] leading-none" style={{ color: 'var(--wc-gr)' }}>{avgBizTripKm.toFixed(1)}</div>
              <div className="font-data text-[8px] uppercase tracking-[.06em] mt-[4px]" style={{ color: 'var(--wc-t3)' }}>km / biz</div>
            </div>
            <div className="text-center rounded-[10px] p-[10px]" style={{ background: 'rgb(var(--wc-ink) / .03)' }}>
              <div className="font-heading font-black text-[20px] leading-none" style={{ color: 'var(--wc-am)' }}>${costPerKm > 0 ? costPerKm.toFixed(2) : '—'}</div>
              <div className="font-data text-[8px] uppercase tracking-[.06em] mt-[4px]" style={{ color: 'var(--wc-t3)' }}>cost / km</div>
            </div>
          </div>
        </div>

      </div>

      <BottomNav />
    </div>
  );
}
