import { useMemo } from 'react';
import { useApp } from '@/lib/app-context';
import { calcLogbookDeduction } from '@/lib/trip-data';
import { BottomNav } from './bottom-nav';
import { ArrowLeft, TrendingUp, Calendar, MapPin, DollarSign, Clock, Fuel } from 'lucide-react';

export function StatsScreen() {
  const { state, dispatch } = useApp();

  const sorted = state.trips.filter(t => t.type !== null && !t.autoGenerated);
  const biz = sorted.filter(t => t.type === 'business');
  const per = sorted.filter(t => t.type === 'personal');
  const totalKm = sorted.reduce((s, t) => s + t.km, 0);
  const bizKm = biz.reduce((s, t) => s + t.km, 0);
  const perKm = per.reduce((s, t) => s + t.km, 0);
  const totalDed = calcLogbookDeduction(bizKm, totalKm);
  const bizPct = totalKm > 0 ? (bizKm / totalKm * 100) : 0;
  const avgTripKm = sorted.length > 0 ? totalKm / sorted.length : 0;
  const avgBizTripKm = biz.length > 0 ? bizKm / biz.length : 0;

  const dayStats = useMemo(() => {
    const days: Record<string, { trips: number; km: number }> = {};
    const dayNames = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
    dayNames.forEach(d => { days[d] = { trips: 0, km: 0 }; });
    sorted.forEach(t => {
      const d = new Date(t.year, t.month, t.day);
      const dayName = dayNames[d.getDay()];
      days[dayName].trips += 1;
      days[dayName].km += t.km;
    });
    return dayNames.map(name => ({ name, ...days[name] }));
  }, [sorted]);

  const maxDayTrips = Math.max(1, ...dayStats.map(d => d.trips));

  const topDestinations = useMemo(() => {
    const map: Record<string, number> = {};
    sorted.forEach(t => {
      const dest = t.to;
      map[dest] = (map[dest] || 0) + 1;
    });
    return Object.entries(map).sort((a, b) => b[1] - a[1]).slice(0, 5);
  }, [sorted]);

  const expenses = useMemo(() => {
    try {
      const raw = localStorage.getItem('wc_expenses');
      return raw ? JSON.parse(raw) : [];
    } catch { return []; }
  }, []);
  const totalExpenses = expenses.reduce((s: number, e: any) => s + (e.amount || 0), 0);
  const fuelCost = expenses.filter((e: any) => e.category === 'Fuel & Oil').reduce((s: number, e: any) => s + (e.amount || 0), 0);
  const costPerKm = totalKm > 0 ? (totalExpenses / totalKm) : 0;

  return (
    <div className="flex flex-col h-full" data-testid="stats-screen">
      <div className="flex items-center gap-[10px] px-4 pt-2 pb-[5px] flex-shrink-0">
        <button
          className="w-[34px] h-[34px] rounded-lg flex items-center justify-center"
          style={{ background: 'rgba(255,255,255,.06)', border: '1px solid var(--wc-border)' }}
          onClick={() => dispatch({ type: 'GO_SCREEN', screen: 'dashboard' })}
          data-testid="button-back-stats"
        >
          <ArrowLeft className="w-[16px] h-[16px]" style={{ color: 'var(--wc-t2)' }} />
        </button>
        <span className="font-heading font-extrabold text-[22px] uppercase tracking-[.04em] text-white">My Stats</span>
        <TrendingUp className="ml-auto w-[18px] h-[18px]" style={{ color: 'var(--wc-y)' }} />
      </div>

      <div className="flex-1 px-[14px] pb-[80px] flex flex-col gap-[8px] overflow-y-auto scrollbar-thin" style={{ overscrollBehavior: 'contain', WebkitOverflowScrolling: 'touch' } as any}>
        <div className="grid grid-cols-2 gap-[6px]">
          <div className="rounded-[12px] p-[12px]" style={{ background: 'var(--wc-card)', border: '1px solid var(--wc-border)' }}>
            <MapPin className="w-[18px] h-[18px] mb-[6px]" style={{ color: 'var(--wc-y)' }} />
            <div className="font-heading font-black text-[24px] leading-none" style={{ color: 'var(--wc-y)' }}>{sorted.length}</div>
            <div className="font-data text-[9px] uppercase tracking-[.1em] mt-[3px]" style={{ color: 'var(--wc-t3)' }}>Total Trips</div>
          </div>
          <div className="rounded-[12px] p-[12px]" style={{ background: 'var(--wc-card)', border: '1px solid var(--wc-border)' }}>
            <DollarSign className="w-[18px] h-[18px] mb-[6px]" style={{ color: 'var(--wc-gr)' }} />
            <div className="font-heading font-black text-[24px] leading-none" style={{ color: 'var(--wc-gr)' }}>${totalDed.toFixed(0)}</div>
            <div className="font-data text-[9px] uppercase tracking-[.1em] mt-[3px]" style={{ color: 'var(--wc-t3)' }}>Deduction Est.</div>
          </div>
          <div className="rounded-[12px] p-[12px]" style={{ background: 'var(--wc-card)', border: '1px solid var(--wc-border)' }}>
            <TrendingUp className="w-[18px] h-[18px] mb-[6px]" style={{ color: 'var(--wc-y)' }} />
            <div className="font-heading font-black text-[24px] leading-none">{totalKm.toFixed(0)}<span className="text-[14px] font-bold" style={{ color: 'var(--wc-t3)' }}> km</span></div>
            <div className="font-data text-[9px] uppercase tracking-[.1em] mt-[3px]" style={{ color: 'var(--wc-t3)' }}>Total Distance</div>
          </div>
          <div className="rounded-[12px] p-[12px]" style={{ background: 'var(--wc-card)', border: '1px solid var(--wc-border)' }}>
            <Fuel className="w-[18px] h-[18px] mb-[6px]" style={{ color: 'var(--wc-am)' }} />
            <div className="font-heading font-black text-[24px] leading-none" style={{ color: 'var(--wc-am)' }}>${fuelCost > 0 ? fuelCost.toFixed(0) : '—'}</div>
            <div className="font-data text-[9px] uppercase tracking-[.1em] mt-[3px]" style={{ color: 'var(--wc-t3)' }}>Fuel Costs</div>
          </div>
        </div>

        <div className="rounded-[12px] p-[14px]" style={{ background: 'var(--wc-card)', border: '1px solid var(--wc-border)' }}>
          <div className="font-heading font-bold text-[13px] uppercase tracking-[.04em] mb-[10px]" style={{ color: 'var(--wc-t2)' }}>Business vs Personal</div>
          <div className="h-[10px] rounded-full overflow-hidden flex" style={{ background: 'rgba(255,255,255,.06)' }}>
            {bizPct > 0 && <div className="h-full" style={{ width: `${bizPct}%`, background: 'var(--wc-y)' }} />}
            {bizPct < 100 && <div className="h-full" style={{ width: `${100 - bizPct}%`, background: 'rgba(180,180,180,.3)' }} />}
          </div>
          <div className="flex justify-between mt-[6px]">
            <div className="text-[12px]"><span style={{ color: 'var(--wc-y)' }}>{biz.length} business</span> <span style={{ color: 'var(--wc-t3)' }}>({bizKm.toFixed(0)} km)</span></div>
            <div className="text-[12px]"><span style={{ color: 'var(--wc-t2)' }}>{per.length} personal</span> <span style={{ color: 'var(--wc-t3)' }}>({perKm.toFixed(0)} km)</span></div>
          </div>
        </div>

        <div className="rounded-[12px] p-[14px]" style={{ background: 'var(--wc-card)', border: '1px solid var(--wc-border)' }}>
          <div className="font-heading font-bold text-[13px] uppercase tracking-[.04em] mb-[10px]" style={{ color: 'var(--wc-t2)' }}>Trips by Day</div>
          <div className="flex items-end gap-[6px]">
            {dayStats.map(d => (
              <div key={d.name} className="flex-1 flex flex-col items-center">
                <div className="w-full rounded-[4px] transition-all" style={{ height: `${Math.max(4, (d.trips / maxDayTrips) * 50)}px`, background: d.trips > 0 ? 'var(--wc-y)' : 'rgba(255,255,255,.06)' }} />
                <div className="font-data text-[8px] uppercase mt-[4px]" style={{ color: d.trips > 0 ? 'var(--wc-y)' : 'var(--wc-t3)' }}>{d.name}</div>
                <div className="font-data text-[9px] font-bold" style={{ color: 'var(--wc-t2)' }}>{d.trips}</div>
              </div>
            ))}
          </div>
        </div>

        <div className="rounded-[12px] p-[14px]" style={{ background: 'var(--wc-card)', border: '1px solid var(--wc-border)' }}>
          <div className="font-heading font-bold text-[13px] uppercase tracking-[.04em] mb-[8px]" style={{ color: 'var(--wc-t2)' }}>Top Destinations</div>
          {topDestinations.map(([dest, count], i) => (
            <div key={dest} className="flex items-center gap-[8px] py-[6px]" style={{ borderTop: i > 0 ? '1px solid rgba(255,255,255,.04)' : 'none' }}>
              <div className="w-[22px] h-[22px] rounded-full flex items-center justify-center font-data text-[10px] font-bold" style={{ background: 'rgba(245,196,0,.1)', color: 'var(--wc-y)' }}>{i + 1}</div>
              <div className="flex-1 text-[13px] text-white truncate">{dest}</div>
              <div className="font-data text-[12px]" style={{ color: 'var(--wc-t3)' }}>{count} trip{count !== 1 ? 's' : ''}</div>
            </div>
          ))}
          {topDestinations.length === 0 && (
            <div className="text-[12px] py-[6px]" style={{ color: 'var(--wc-t3)' }}>No trips sorted yet</div>
          )}
        </div>

        <div className="rounded-[12px] p-[14px]" style={{ background: 'var(--wc-card)', border: '1px solid var(--wc-border)' }}>
          <div className="font-heading font-bold text-[13px] uppercase tracking-[.04em] mb-[8px]" style={{ color: 'var(--wc-t2)' }}>Averages</div>
          <div className="grid grid-cols-3 gap-[8px]">
            <div>
              <div className="font-heading font-bold text-[18px]" style={{ color: 'var(--wc-y)' }}>{avgTripKm.toFixed(1)}</div>
              <div className="font-data text-[8px] uppercase" style={{ color: 'var(--wc-t3)' }}>km/trip</div>
            </div>
            <div>
              <div className="font-heading font-bold text-[18px]" style={{ color: 'var(--wc-gr)' }}>{avgBizTripKm.toFixed(1)}</div>
              <div className="font-data text-[8px] uppercase" style={{ color: 'var(--wc-t3)' }}>km/biz trip</div>
            </div>
            <div>
              <div className="font-heading font-bold text-[18px]" style={{ color: 'var(--wc-am)' }}>${costPerKm > 0 ? costPerKm.toFixed(2) : '—'}</div>
              <div className="font-data text-[8px] uppercase" style={{ color: 'var(--wc-t3)' }}>cost/km</div>
            </div>
          </div>
        </div>
      </div>

      <BottomNav />
    </div>
  );
}
